### ISSUE TITLE
Forgot my admin password and cannot recover it

### ISSUE THREAD

**Issue by Pcsl** [cantino/huginn#1102]
Hi (again lol),
I forgot my admin password and I cannot recover it as the SMTP from Gmail seems not to be working. Is there any way to modify the password from the MySQL database?

**Comment by level20peon** [comment]
create another user, pick a password, copy that user's password field in the database to your account.

**Comment by cantino** [comment]
What @level20peon said would likely work.  Or use `rails console` (`heroku run rails console` on Heroku) and something like

```ruby
user = User.find_by(email: EMAIL)
user.password = new_password
user.password_confirmation = new_password
user.save!
```

**Comment by Pcsl** [comment]
Thank you for your suggestions. I tried the @level20peon but as my account seems to be locked it's not working anyway.

So I was thinking maybe I could try to fix the SMTP problem instead. Every time I use the "reset password" function I get this message: "We're sorry, but something went wrong." The SMTP mailing has never worked even if the gmail server is supposed to be set up as expected.

**Comment by cantino** [comment]
Where are you hosting Huginn?

**Comment by Pcsl** [comment]
I'm hosting it at Cloud At Cost

**Comment by cantino** [comment]
Did you try the `RAILS_ENV=production bundle exec rails console` solution?

**Comment by Pcsl** [comment]
Running that I get

```
/home/huginn/huginn/config/routes.rb:80:in `block in <top (required)>': uninitialized constant LetterOpenerWeb (NameError)
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:412:in `draw'
        from /home/huginn/huginn/config/routes.rb:1:in `<top (required)>'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `each'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:16:in `reload!'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:26:in `block in updater'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `call'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `execute'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:27:in `updater'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing'
        from /home/huginn/huginn/config/environment.rb:8:in `<top (required)>'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:67:in `console'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by cantino** [comment]
Add RAILS_ENV=production to that since you're on the server.

**Comment by Pcsl** [comment]
Oh, right, that one is working. After that? 

I tried this one but I get this error:
```
user = User.find_by(email: myemail@addres.com)
(irb):5: syntax error, unexpected ')', expecting end-of-input
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by cantino** [comment]
The email address needs to be in quotes, since it's a string.

```ruby
user = User.find_by(email: "myemail@addres.com")
```

**Comment by Pcsl** [comment]
That one works but the next line doesn't work as you can see:
```
irb(main):009:0> user.password = new_password
NameError: undefined local variable or method `new_password' for main:Object
        from (irb):9
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by cantino** [comment]
```ruby
new_password = "PUT THE NEW PASSWORD HERE"
user.password = new_password
user.password_confirmation = new_password
user.save!
```

and replace `PUT THE NEW PASSWORD HERE` with your new password.

**Comment by Pcsl** [comment]
Worked! Again, thank you very much!

**Comment by cantino** [comment]
You're very welcome :)

**Comment by hexigen** [comment]
Hey guys thanks for your help. I know this is simple but maybe it will save someone time.
If you installed huginn on the server not inside the container make sure to first CD into the directory of huginn.
In my case it's
```
cd /home/huginn/huginn/
sudo RAILS_ENV=production bundle exec rails console
user = User.find_by(email: "myemail@addres.com")
new_password = "PUT THE NEW PASSWORD HERE"
user.password = new_password
user.password_confirmation = new_password
user.save!
```
This worked for me, and like others I had issues with Chrome error "The change you wanted was rejected". Opening in Firefox allows me to login.
