### ISSUE TITLE
Huginn Crashed in Heroku

### ISSUE THREAD

**Issue by jn11** [cantino/huginn#1140]
After running huggin for some time in Heroku, the application crashed and when I restart I'm getting all the time the error in the log below. 

I checked the PG stats in heroku and I'm inside the required limits in connections and rows. Anybody experience this issue before?

Log:

2015-11-10T10:16:08.353247+00:00 heroku[web.1]: State changed from starting to up
2015-11-10T10:16:08.334479+00:00 app[web.1]: I, [2015-11-10T10:16:08.334398 #3]  INFO -- : listening on addr=0.0.0.0:23355 fd=9
2015-11-10T10:16:08.355110+00:00 app[web.1]: E, [2015-11-10T10:16:08.354966 #3] ERROR -- : FATAL:  remaining connection slots are reserved for non-replication superuser connections
2015-11-10T10:16:08.355114+00:00 app[web.1]:  (PG::ConnectionBad)
2015-11-10T10:16:08.355115+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `initialize'
2015-11-10T10:16:08.355120+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `new'
2015-11-10T10:16:08.355120+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
2015-11-10T10:16:08.355121+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
2015-11-10T10:16:08.355122+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
2015-11-10T10:16:08.355122+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
2015-11-10T10:16:08.355123+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
2015-11-10T10:16:08.355124+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
2015-11-10T10:16:08.355125+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
2015-11-10T10:16:08.355127+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
2015-11-10T10:16:08.355128+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
2015-11-10T10:16:08.355128+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
2015-11-10T10:16:08.355129+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
2015-11-10T10:16:08.355130+00:00 app[web.1]: /app/vendor/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
2015-11-10T10:16:08.355131+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
2015-11-10T10:16:08.355131+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
2015-11-10T10:16:08.355132+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
2015-11-10T10:16:08.355133+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:87:in `connection'
2015-11-10T10:16:08.355133+00:00 app[web.1]: ./deployment/heroku/unicorn.rb:36:in `block in reload'
2015-11-10T10:16:08.355134+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:523:in `call'
2015-11-10T10:16:08.355135+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:523:in `spawn_missing_workers'
2015-11-10T10:16:08.355136+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
2015-11-10T10:16:08.355137+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
2015-11-10T10:16:08.355137+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
2015-11-10T10:16:08.355138+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
2015-11-10T10:16:08.973026+00:00 heroku[web.1]: State changed from up to crashed
2015-11-10T10:16:08.958648+00:00 heroku[web.1]: Process exited with status 1

**Comment by cantino** [comment]
Wow, that's weird.  It looks like a Heroku infrastructure issue to me.  Have you sent them a ticket?

**Comment by jn11** [comment]
Yes, I'm still waiting for their feedback.

**Comment by brianpetro** [comment]
@jn11 

1) Install (heroku-pg-extras)[https://github.com/heroku/heroku-pg-extras]

2) `heroku pg:killall`

3) `heroku restart`

That should fix it.
