### ISSUE TITLE
Apache2 Error 503 Service Unavailable

### ISSUE THREAD

**Issue by virse** [cantino/huginn#1162]
Hey folks,

I followed the installation instruction step by step (https://github.com/cantino/huginn/blob/master/doc/manual/installation.md). Everything worked as expected. I also configured my apache2-installation as provided in the Wiki with an own Subdomain (https://github.com/cantino/huginn/wiki/Apache-Huginn-configuration).

When I try do start huginn via console, I get this one

```
/home/huginn/huginn# bundle exec foreman start
14:55:27 web.1  | started with pid 28172
14:55:27 jobs.1 | started with pid 28174
14:55:28 web.1  | exited with code 1
14:55:28 system | sending SIGTERM to all processes
14:55:28 jobs.1 | terminated by SIGTERM
```
When I try to verify if huginn is working via *netstat --listen* I see online that huginn ist listening on socket not on port 3000.

I use the production enviroment.

Here are my config-files:

.env
```
# ==== Required configuration settings for Huginn ====

# Replace the following with the output from "rake secret"
APP_SECRET_TOKEN=xyz


# This is the domain where your Huginn instance will be running. The default should work
# for development, but it needs to be changed to your Huginn domain when you deploy to a
# production environment (e.g., yourdomain.com, possibly including a port).
DOMAIN=localhost:3000

# Optionally set an asset host
# ASSET_HOST=http://assets.example.com

############################
#      Database Setup      #
############################

DATABASE_ADAPTER=mysql2
DATABASE_ENCODING=utf8mb4
DATABASE_RECONNECT=true
DATABASE_NAME=huginn_production
DATABASE_POOL=20
DATABASE_USERNAME=huginn
DATABASE_PASSWORD="xyz"
#DATABASE_HOST=127.0.0.1
#DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock

# MySQL only: If you are running a MySQL server >=5.5.3, you should
# set DATABASE_ENCODING to utf8mb4 instead of utf8 so that the
# database can hold 4-byte UTF-8 characters like emoji.
#DATABASE_ENCODING=utf8mb4

# ==== Additional required production settings ====

# Configure Rails environment.  This should only be needed in production and may cause errors in development.
RAILS_ENV=production

# Should Rails force all requests to use SSL?
FORCE_SSL=true

############################
#     Allowing Signups     #
############################

# This invitation code will be required for users to signup with your Huginn installation.
# You can see its use in user.rb.  PLEASE CHANGE THIS!
INVITATION_CODE=teste-huginn

# If you don't want to require new users to have an invitation code in order to sign up, set this to true.
SKIP_INVITATION_CODE=false

#############################
#    Email Configuration    #
#############################

# Outgoing email settings.  To use Gmail or Google Apps, put your Google Apps domain or gmail.com
# as the SMTP_DOMAIN and your Gmail username and password as the SMTP_USER_NAME and SMTP_PASSWORD.
#
# PLEASE NOTE: In order to enable sending real emails via SMTP locally (e.g., when not in the production Rails environment),
# you must also set SEND_EMAIL_IN_DEVELOPMENT to true below.
#
# If you have trouble with port 587 on Gmail, you can also try setting
# SMTP_AUTHENTICATION to login and the SMTP_PORT to 465.

SMTP_DOMAIN=xyz.de
SMTP_USER_NAME=huginn@xyz.de
SMTP_PASSWORD=xyz
SMTP_SERVER=xyz.de
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# Set to true to send real emails via SMTP when running in the development Rails environment.
# Set to false to have emails intercepted in development and displayed at http://localhost:3000/letter_opener
SEND_EMAIL_IN_DEVELOPMENT=true

# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=huginn@xyz.de

###########################
#      Agent Logging      #
###########################

# Number of lines of log messages to keep per Agent
AGENT_LOG_LENGTH=200

########################################################################################################
#    OAuth Configuration                                                                               #
#  More information at the wiki: https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications #
########################################################################################################

TWITTER_OAUTH_KEY=xyz
TWITTER_OAUTH_SECRET=xyz

THIRTY_SEVEN_SIGNALS_OAUTH_KEY=
THIRTY_SEVEN_SIGNALS_OAUTH_SECRET=

GITHUB_OAUTH_KEY=
GITHUB_OAUTH_SECRET=

TUMBLR_OAUTH_KEY=
TUMBLR_OAUTH_SECRET=

DROPBOX_OAUTH_KEY=
DROPBOX_OAUTH_SECRET=

WUNDERLIST_OAUTH_KEY=
WUNDERLIST_OAUTH_SECRET=

EVERNOTE_OAUTH_KEY=
EVERNOTE_OAUTH_SECRET=
# Set to true in development, false in production
USE_EVERNOTE_SANDBOX=true

#############################
#  AWS and Mechanical Turk  #
#############################

# AWS Credentials for MTurk
AWS_ACCESS_KEY_ID="your aws access key id"
AWS_ACCESS_KEY="your aws access key"

# Set AWS_SANDBOX to true if you're developing Huginn code.
AWS_SANDBOX=false

########################
#   Various Settings   #
########################

# Specify the HTTP backend library for Faraday, commonly used by
# WebsiteAgent, RssAgent and PostAgent.  You can change this depending
# on the performance and stability you need for your service.  Any
# choice other than "typhoeus", "net_http", or "em_http" should
# require you to bundle a corresponding gem via Gemfile.
FARADAY_HTTP_BACKEND=typhoeus

# Specify the default User-Agent header value for HTTP requests made
# by Agents that allow overriding the User-Agent header value.
DEFAULT_HTTP_USER_AGENT="Huginn - https://github.com/cantino/huginn"

# Allow JSONPath eval expresions. i.e., $..price[?(@ < 20)]
# You should not allow this on a shared Huginn box because it is not secure.
ALLOW_JSONPATH_EVAL=false

# Enable this setting to allow insecure Agents like the ShellCommandAgent.  Only do this
# when you trust everyone using your Huginn installation.
ENABLE_INSECURE_AGENTS=false

# Enable this setting to allow second precision schedule in
# SchedulerAgent.  By default, the use of the "second" field is
# restricted so that any value other than a single zero (which means
# "on the minute") is disallowed to prevent abuse of service.
ENABLE_SECOND_PRECISION_SCHEDULE=false

# Specify the scheduler frequency in seconds (default: 0.3).
# Increasing this value will help reduce the use of system resources
# at the expense of time accuracy.
SCHEDULER_FREQUENCY=0.3

# Specify the frequency with which the scheduler checks for and cleans up expired events.
# You can use `m` for minutes, `h` for hours, and `d` for days.
EVENT_EXPIRATION_CHECK=6h

# Use Graphviz for generating diagrams instead of using Google Chart
# Tools.  Specify a dot(1) command path built with SVG support
# enabled.
#USE_GRAPHVIZ_DOT=dot

# Default layout for agent flow diagrams generated by Graphviz.
# Choose from `circo`, `dot` (default), `fdp`, `neato`, `osage`,
# `patchwork`, `sfdp`, or `twopi`.  Note that not all layouts are
# supported by Graphviz depending on the build options.
#DIAGRAM_DEFAULT_LAYOUT=dot

# Timezone. Use `rake time:zones:local` or `rake time:zones:all` to get your zone name
TIMEZONE="Berlin"

# Number of failed jobs to keep in the database
FAILED_JOBS_TO_KEEP=100

# Maximum runtime of background jobs in minutes
DELAYED_JOB_MAX_RUNTIME=2

# Amount of seconds for delayed_job to sleep before checking for new jobs
DELAYED_JOB_SLEEP_DELAY=10

###############################################################
# Capistrano deployment, read the documentation:              #
# https://github.com/cantino/huginn/doc/manual/capistrano.md  #
###############################################################

#CAPISTRANO_DEPLOY_SERVER=
#CAPISTRANO_DEPLOY_USER=
#CAPISTRANO_DEPLOY_REPO_URL=
```
I also tried the DOMAIN=localhost:3000 part with the subdomain. Same error.

Procfile
```
###############################
#         DEVELOPMENT         #
###############################

# Procfile for development using the new threaded worker (scheduler, twitter stream and delayed job)
#web: bundle exec rails server -b0.0.0.0
#jobs: bundle exec rails runner bin/threaded.rb

# Old version with separate processes (use this if you have issues with the threaded version)
# web: bundle exec rails server
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb
# dj: bundle exec script/delayed_job run

###############################
#         PRODUCTION          #
###############################

# You need to copy or link config/unicorn.rb.example to config/unicorn.rb for both production versions.
# Have a look at the deployment guides, if you want to set up huginn on your server:
# https://github.com/cantino/huginn/doc

# Using the threaded worker (consumes less RAM but can run slower)
web: bundle exec unicorn -c config/unicorn.rb
jobs: bundle exec rails runner bin/threaded.rb

# Old version with separate processes (use this if you have issues with the threaded version)
# web: bundle exec unicorn -c config/unicorn.rb
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb
# dj: bundle exec script/delayed_job run

###############################
# Multiple DelayedJob workers #
###############################
# Per default Huginn can just run one agent at a time. Using a lot of agents or calling slow
# external services frequently might require more DelayedJob workers (an indicator for this is
# a backlog in your 'Job Management' page).
# Every uncommented line starts an additional DelayedJob worker. This works for development, production
# and for the threaded and separate worker processes. Keep in mind one worker needs about 300MB of RAM.
#
#dj2: bundle exec script/delayed_job -i 2 run
#dj3: bundle exec script/delayed_job -i 3 run
#dj4: bundle exec script/delayed_job -i 4 run
#dj5: bundle exec script/delayed_job -i 5 run
#dj6: bundle exec script/delayed_job -i 6 run
#dj7: bundle exec script/delayed_job -i 7 run
#dj8: bundle exec script/delayed_job -i 8 run
#dj9: bundle exec script/delayed_job -i 9 run
#dj10: bundle exec script/delayed_job -i 10 run
```
*sudo rake production:status* gives me
```
run: huginn-web-1: (pid 27201) 2545s; run: log: (pid 27200) 2545s
run: huginn-jobs-1: (pid 27204) 2545s; run: log: (pid 27203) 2545s
```

And the unicorn-log this:

```
I, [2015-11-25T13:41:05.934741 #24316]  INFO -- : reaped #<Process::Status: pid 24345 exit 0> worker=0
I, [2015-11-25T13:41:05.937443 #24316]  INFO -- : master complete
I, [2015-11-25T13:44:12.950205 #25324]  INFO -- : Refreshing Gem list
I, [2015-11-25T13:44:17.955981 #25324]  INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
I, [2015-11-25T13:44:17.956182 #25324]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=8
I, [2015-11-25T13:44:17.967592 #25324]  INFO -- : master process ready
I, [2015-11-25T13:44:17.973915 #25340]  INFO -- : worker=0 ready
I, [2015-11-25T14:18:52.567339 #25324]  INFO -- : reaped #<Process::Status: pid 25340 exit 0> worker=0
I, [2015-11-25T14:18:52.589680 #25324]  INFO -- : master complete
I, [2015-11-25T14:25:31.067920 #27172]  INFO -- : Refreshing Gem list
I, [2015-11-25T14:25:35.369221 #27172]  INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
I, [2015-11-25T14:25:35.389109 #27172]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=8
I, [2015-11-25T14:25:35.399365 #27172]  INFO -- : master process ready
I, [2015-11-25T14:25:35.430045 #27183]  INFO -- : worker=0 ready
I, [2015-11-25T14:25:38.739938 #27172]  INFO -- : reaped #<Process::Status: pid 27183 exit 0> worker=0
I, [2015-11-25T14:25:38.740139 #27172]  INFO -- : master complete
I, [2015-11-25T14:25:41.245856 #27201]  INFO -- : Refreshing Gem list
I, [2015-11-25T14:25:46.134970 #27201]  INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
I, [2015-11-25T14:25:46.135152 #27201]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=8
I, [2015-11-25T14:25:46.149208 #27201]  INFO -- : master process ready
I, [2015-11-25T14:25:46.156357 #27220]  INFO -- : worker=0 ready
```

and the apache error-log that 

```
[Wed Nov 25 14:55:40.325421 2015] [proxy:error] [pid 25523] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Wed Nov 25 14:55:40.325460 2015] [proxy_http:error] [pid 25523] [client 87.175.149.248:59568] AH01114: HTTP: failed to make connection to backend: 127.0.0.1
```

So it seems that Apche2 couldn't address the Huginn via Proxy, because it is obviously not running.

Any help on that is deeply appreciated.

Greets, mike

**Comment by dsander** [comment]
Hi mike,

that is correct, the default unicorn (application server) configuration uses a unix socket to communicate with nginx because it is faster. To make it work with apache (which does not support proxing through unix sockets) you you need to modify `/home/huginn/huginn/config/unicorn.rb` to listen to a port by replacing line 8 with `listen "127.0.0.1:3000"`

**Comment by dsander** [comment]
Forgot to mention, after you did the change huginn needs to be restarted with `sudo rake production:restart`

**Comment by virse** [comment]
Hi sdander,

thx a lot *listen "127.0.0.1:3000"* did the trick, though I already tried that before - but without the *sudo rake production:restart* ;o)

For all other users having the some problem with Huginn and Apache2: You also have to change the options in your virtual host file as mentioned on this site: http://tecadmin.net/authz-core-error-client-denied-by-server-configuration/# because otherwise images and the css-file won't be loaded.

Maybe the guide on https://github.com/cantino/huginn/wiki/Apache-Huginn-configuration should be adjusted from 

```
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>

    <Directory /path/to/huginn/public>
        Allow from all
        AllowOverride all
        Options -MultiViews
    </Directory>
```

to 

```
    <Proxy *>
         Require all granted
    </Proxy>

    <Directory /path/to/huginn/public>
        Require all granted
        AllowOverride all
        Options -MultiViews
    </Directory>
```

Greets, mike

**Comment by dsander** [comment]
Great that it works! Would you mind updating the wiki with changes you needed to make and add a note about the unicorn configuration change?

**Comment by virse** [comment]
Done ;o)

**Comment by dsander** [comment]
Awesome, thank you!

**Comment by vivagonna** [comment]
Hi, I just came across with this problem too, when I `sudo rake production:restart` I got an error like this:

> rake aborted!
> Gem::LoadError: You have already activated rake 11.1.2, but your Gemfile requires rake 10.5.0. Prepending `bundle exec` to your command may solve this.
> /home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
> /home/huginn/huginn/config/application.rb:1:in `<top (required)>'
> /home/huginn/huginn/Rakefile:5:in `<top (required)>'
> LoadError: cannot load such file -- bundler/setup
> /home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
> /home/huginn/huginn/config/application.rb:1:in `<top (required)>'
> /home/huginn/huginn/Rakefile:5:in `<top (required)>'
> (See full trace by running task with --trace)

**Comment by dsander** [comment]
`sudo bundle exec  rake production:restart` should work, we might need to update the installation guide.
