### ISSUE TITLE
Weathe Agent Broken Pipe

### ISSUE THREAD

**Issue by virse** [cantino/huginn#1163]
Sorry for asking maybe a stupid question, but I'm totally new to Ruby and Huginn.

Huginn in up and running. But when I try to start the Weather Agent I get this error message:

```               
Broken pipe @ io_write - <STDOUT>
/home/huginn/huginn/app/models/agent_log.rb:18:in `write'
/home/huginn/huginn/app/models/agent_log.rb:18:in `puts'
/home/huginn/huginn/app/models/agent_log.rb:18:in `puts'
/home/huginn/huginn/app/models/agent_log.rb:18:in `log_for_agent'
/home/huginn/huginn/app/models/agent.rb:212:in `log'
/home/huginn/huginn/app/concerns/dry_runnable.rb:61:in `log'
/home/huginn/huginn/app/models/agent.rb:216:in `error'
/home/huginn/huginn/app/jobs/agent_check_job.rb:11:in `rescue in perform'
/home/huginn/huginn/app/jobs/agent_check_job.rb:5:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:32:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:31:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:21:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call'
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
```
Using this agent:

```
{
  "location": "zmw:00000.27.10761?sp=IBAYERNM57",
  "api_key": "247bb96f5ff8272f",
  "which_day": "0",
  "expected_update_period_in_days": "1"
}
```
Thx for some hints for a newbie ;o)

Mike

**Comment by cantino** [comment]
Welcome @virse.

A `Broken pipe @ io_write - <STDOUT>` error in agent_log.rb is new to me.  It looks like that line of code is a `puts` statement where Ruby is trying to write to standard output (the terminal or log file). How are you running Huginn? It's pretty strange for this to error.

**Comment by virse** [comment]
Hi cantino,

thx for answering me.

I'm running Huginn on a VServer with Ubuntu 14.04 LTS on a subdomain. Webserver is an Apache 2.4.
What kind of information do you need? Special log files, config files?

Thx in advance for your help!

Greetz

**Comment by cantino** [comment]
And how are you running it? Foreman?

**Comment by virse** [comment]
Yes via *foreman start*

**Comment by dsander** [comment]
@virse Are you piping to output into less or head?

**Comment by virse** [comment]
Sorry where do I have to look? Any config-file? Sorry I'm a newbie to huginn.

**Comment by dsander** [comment]
How do you start huginn, just `foreman start` inside a ssh shell and when does the exception happen?

**Comment by virse** [comment]
I start Huginn with the command
```
bundle exec foreman start
```
as mentioned in the installation guide via console. In the console there is only
```
bundle exec foreman start
07:38:13 web.1  | started with pid 32751
07:38:13 jobs.1 | started with pid 32753
07:38:14 web.1  | exited with code 1
07:38:14 system | sending SIGTERM to all processes
07:38:14 jobs.1 | terminated by SIGTERM
```
The exeption started right away when Huginn wants to perform the agent.

**Comment by dsander** [comment]
It looks like something is sending the TERM signal to foreman which it then stopping huginn. I would suggest you install huginn using the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md) which will also allow you to properly start and daemonize the processes.

**Comment by virse** [comment]
Hi dsander,

the problem is that I used the guide you mentioned above. 
When i check the installation with
```
sudo rake production:check
```
I get a 
```
[  OK  ] Everything is fine
```
back.

Maybe you can give me hint with foreman? I tried 
```
foreman start
```
and also
```
bundle exec foreman start
```
I can open Huginn in the webbrowser, login and create an agent but the errors are still there.

**Comment by dsander** [comment]
Oh I see, then `sudo rake production:start` should start huginn. foreman is not supposed to be used in production.

**Comment by virse** [comment]
Thx a stopped and restarted Huggin with *sudo rake production_start*, created a new agent but the error is still there
```
Broken pipe @ io_write - <STDOUT>
/home/huginn/huginn/app/models/agent_log.rb:18:in `write'
/home/huginn/huginn/app/models/agent_log.rb:18:in `puts'
/home/huginn/huginn/app/models/agent_log.rb:18:in `puts'
/home/huginn/huginn/app/models/agent_log.rb:18:in `log_for_agent'
/home/huginn/huginn/app/models/agent.rb:212:in `log'
/home/huginn/huginn/app/concerns/dry_runnable.rb:61:in `log'
/home/huginn/huginn/app/models/agent.rb:216:in `error'
/home/huginn/huginn/app/jobs/agent_check_job.rb:11:in `rescue in perform'
/home/huginn/huginn/app/jobs/agent_check_job.rb:5:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:32:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:31:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:21:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call'
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
```
Do you need more information? To be honest the error log says nothing to me.

**Comment by dsander** [comment]
In which log file is the `Broken pipe @ io_write - <STDOUT>` error written?

I think the second exception is caused by the location you are using, try replacing it with `zmw:00000.27.10761`

**Comment by virse** [comment]
Thx! Replacing the zmw did the trick and also the other error disappeared!
