### ISSUE TITLE
Getting the Error: "We're sorry, but something went wrong." when creating an agent.

### ISSUE THREAD

**Issue by wootwoot1234** [cantino/huginn#1167]
I'm getting the error ```We're sorry, but something went wrong.``` when I click save when creating any agent.  I thought it might have been that I was running an older version so I followed the update instructions in the docs folder but I'm still getting the error after the update.  I'm running it on the Heroku free plan but I can't tell if I'm hitting any limits.

What could be causing this error?

**Comment by dsander** [comment]
Hi @wootwoot1234,

`We're sorry, but something went wrong` almost always means a exception occurred. Can you run `heroku logs` right after you triggered the error again and paste the output here? This should give us an idea what is happening.

**Comment by wootwoot1234** [comment]
WootWoot:huginn-app-here Tom$ heroku logs
    2015-11-28T19:35:04.053010+00:00 app[web.1]:   70270143227400       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
    2015-11-28T19:35:04.053031+00:00 app[web.1]:   70270143227400       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
    2015-11-28T19:35:04.053034+00:00 app[web.1]:   70270143227400       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `loop'
    2015-11-28T19:35:04.053053+00:00 app[web.1]:   70270143227400       /app/vendor/bundle/ruby/2.2.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
    2015-11-28T19:35:04.053056+00:00 app[web.1]:   70270143227400   tz:
    2015-11-28T19:35:04.053077+00:00 app[web.1]:   70270143227400     ENV['TZ']:
    2015-11-28T19:35:04.053140+00:00 app[web.1]:   70270143227400     Time.now: 2015-11-28 19:35:04 +0000
    2015-11-28T19:35:04.053141+00:00 app[web.1]:   70270143227400   scheduler:
    2015-11-28T19:35:04.053142+00:00 app[web.1]:   70270143227400     object_id: 70270109650920
    2015-11-28T19:35:04.053143+00:00 app[web.1]:   70270143227400     opts:
    2015-11-28T19:35:04.053168+00:00 app[web.1]:   70270143227400       {:frequency=>0.3}
    2015-11-28T19:35:04.053187+00:00 app[web.1]:   70270143227400       frequency: 0.3
    2015-11-28T19:35:04.053215+00:00 app[web.1]:   70270143227400       scheduler_lock: #<Rufus::Scheduler::NullLock:0x007fd211d911c0>
    2015-11-28T19:35:04.053218+00:00 app[web.1]:   70270143227400       trigger_lock: #<Rufus::Scheduler::NullLock:0x007fd211d91170>
    2015-11-28T19:35:04.053299+00:00 app[web.1]:   70270143227400     uptime: 28598.644580089 (7h56m38s644)
    2015-11-28T19:35:04.053300+00:00 app[web.1]:   70270143227400     down?: false
    2015-11-28T19:35:04.053330+00:00 app[web.1]:   70270143227400     threads: 5
    2015-11-28T19:35:04.053348+00:00 app[web.1]:   70270143227400       thread: #<Thread:0x007fd211d910a8>
    2015-11-28T19:35:04.053351+00:00 app[web.1]:   70270143227400       thread_key: rufus_scheduler_70270109650920
    2015-11-28T19:35:04.053383+00:00 app[web.1]:   70270143227400       work_threads: 4
    2015-11-28T19:35:04.053413+00:00 app[web.1]:   70270143227400         active: 1
    2015-11-28T19:35:04.053445+00:00 app[web.1]:   70270143227400         vacant: 3
    2015-11-28T19:35:04.053449+00:00 app[web.1]:   70270143227400         max_work_threads: 28
    2015-11-28T19:35:04.053488+00:00 app[web.1]:   70270143227400       mutexes: {}
    2015-11-28T19:35:04.053588+00:00 app[web.1]:   70270143227400     jobs: 42
    2015-11-28T19:35:04.053664+00:00 app[web.1]:   70270143227400       at_jobs: 0
    2015-11-28T19:35:04.053753+00:00 app[web.1]:   70270143227400       in_jobs: 0
    2015-11-28T19:35:04.053823+00:00 app[web.1]:   70270143227400       every_jobs: 18
    2015-11-28T19:35:04.053887+00:00 app[web.1]:   70270143227400       interval_jobs: 0
    2015-11-28T19:35:04.054001+00:00 app[web.1]:   70270143227400       cron_jobs: 24
    2015-11-28T19:35:04.054178+00:00 app[web.1]:   70270143227400     running_jobs: 1
    2015-11-28T19:35:04.054179+00:00 app[web.1]:   70270143227400     work_queue: 0
    2015-11-28T19:35:04.054180+00:00 app[web.1]: } 70270143227400 .
    2015-11-28T19:35:15.850159+00:00 app[web.1]: [401aed7c-b475-4a59-8436-fb1496387144]   Rendered scenarios/index.html.erb within layouts/application (80.9ms)
    2015-11-28T19:35:15.745789+00:00 app[web.1]: [401aed7c-b475-4a59-8436-fb1496387144] Started GET "/scenarios" for 73.241.186.22 at 2015-11-28 19:35:15 +0000
    2015-11-28T19:35:15.853226+00:00 app[web.1]: [401aed7c-b475-4a59-8436-fb1496387144]   Rendered layouts/_messages.html.erb (0.1ms)
    2015-11-28T19:35:15.866182+00:00 app[web.1]: [401aed7c-b475-4a59-8436-fb1496387144] Completed 200 OK in 116ms (Views: 84.6ms | ActiveRecord: 22.0ms)
    2015-11-28T19:35:15.749618+00:00 app[web.1]: [401aed7c-b475-4a59-8436-fb1496387144] Processing by ScenariosController#index as HTML
    2015-11-28T19:35:15.852862+00:00 app[web.1]: [401aed7c-b475-4a59-8436-fb1496387144]   Rendered layouts/_navigation.html.erb (1.9ms)
    2015-11-28T19:35:15.854681+00:00 app[web.1]: [401aed7c-b475-4a59-8436-fb1496387144]   Rendered application/_upgrade_warning.html.erb (0.1ms)
    2015-11-28T19:35:15.884963+00:00 heroku[router]: at=info method=GET path="/scenarios" host=huginn-app-here.herokuapp.com request_id=401aed7c-b475-4a59-8436-fb1496387144 fwd="73.241.186.22" dyno=web.1 connect=1ms service=138ms status=200 bytes=14766
    2015-11-28T19:35:16.679516+00:00 heroku[router]: at=info method=GET path="/assets/application-217f07c27970aab29070e0ef3564a0242db68b651934ce399e1a559bc7db8500.css" host=huginn-app-here.herokuapp.com request_id=24e7367f-37fc-40c8-b438-242b5e6dac31 fwd="73.241.186.22" dyno=web.1 connect=0ms service=2ms status=304 bytes=156
    2015-11-28T19:35:16.790785+00:00 heroku[router]: at=info method=GET path="/assets/application-3a776c51c9d8ef85fcd6bede5509e7125ee8f0f7f224863320f679c876c1881c.js" host=huginn-app-here.herokuapp.com request_id=4a49edd1-30b9-4d00-a64f-9b29b75b805c fwd="73.241.186.22" dyno=web.1 connect=0ms service=1ms status=304 bytes=156
    2015-11-28T19:35:16.884307+00:00 heroku[router]: at=info method=GET path="/assets/spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif" host=huginn-app-here.herokuapp.com request_id=9c3d2195-cae8-48b1-a603-617ba3c6ffce fwd="73.241.186.22" dyno=web.1 connect=0ms service=1ms status=304 bytes=156
    2015-11-28T19:35:16.989115+00:00 heroku[router]: at=info method=GET path="/assets/font-awesome/fontawesome-webfont-aadc3580d2b64ff5a7e6f1425587db4e8b033efcbf8f5c332ca52a5ed580c87c.woff2" host=huginn-app-here.herokuapp.com request_id=a3005fb0-8764-419a-9a9e-12344f27388a fwd="73.241.186.22" dyno=web.1 connect=0ms service=4ms status=304 bytes=156
    2015-11-28T19:35:17.081509+00:00 heroku[router]: at=info method=GET path="/assets/glyphicons-halflings-regular-fc969dc1c6ff531abcf368089dcbaf5775133b0626ff56b52301a059fc0f9e1e.woff" host=huginn-app-here.herokuapp.com request_id=d52e1ec4-35ed-4e68-aa45-3a540a5da16d fwd="73.241.186.22" dyno=web.1 connect=0ms service=1ms status=304 bytes=156
    2015-11-28T19:35:17.214076+00:00 heroku[router]: at=info method=GET path="/worker_status" host=huginn-app-here.herokuapp.com request_id=7ee38c50-e9ba-43f3-b1e4-3aca6bb3b67e fwd="73.241.186.22" dyno=web.1 connect=1ms service=65ms status=200 bytes=1102
    2015-11-28T19:35:17.270499+00:00 heroku[router]: at=info method=GET path="/android-chrome-192x192.png" host=huginn-app-here.herokuapp.com request_id=a8eb1f21-a815-4038-8415-1a1e7a276eaa fwd="73.241.186.22" dyno=web.1 connect=0ms service=1ms status=304 bytes=156
    2015-11-28T19:35:17.460061+00:00 heroku[router]: at=info method=GET path="/android-chrome-48x48.png" host=huginn-app-here.herokuapp.com request_id=51958e54-5383-449c-91fc-45db4423c8c2 fwd="73.241.186.22" dyno=web.1 connect=0ms service=1ms status=304 bytes=156
    2015-11-28T19:35:18.848355+00:00 app[web.1]: [d6d6dafd-19ac-41ca-8c62-70f90cfe60e0] Started GET "/" for 52.0.196.119 at 2015-11-28 19:35:18 +0000
    2015-11-28T19:35:18.854235+00:00 app[web.1]: [d6d6dafd-19ac-41ca-8c62-70f90cfe60e0]   Rendered home/_signed_out_index.html.erb (0.6ms)
    2015-11-28T19:35:18.854374+00:00 app[web.1]: [d6d6dafd-19ac-41ca-8c62-70f90cfe60e0]   Rendered home/index.html.erb within layouts/application (1.0ms)
    2015-11-28T19:35:18.856317+00:00 app[web.1]: [d6d6dafd-19ac-41ca-8c62-70f90cfe60e0]   Rendered layouts/_navigation.html.erb (0.8ms)
    2015-11-28T19:35:18.857576+00:00 app[web.1]: [d6d6dafd-19ac-41ca-8c62-70f90cfe60e0] Completed 200 OK in 6ms (Views: 4.9ms | ActiveRecord: 0.0ms)
    2015-11-28T19:35:18.851687+00:00 app[web.1]: [d6d6dafd-19ac-41ca-8c62-70f90cfe60e0] Processing by HomeController#index as */*
    2015-11-28T19:35:18.856699+00:00 app[web.1]: [d6d6dafd-19ac-41ca-8c62-70f90cfe60e0]   Rendered layouts/_messages.html.erb (0.2ms)
    2015-11-28T19:35:18.861467+00:00 heroku[router]: at=info method=GET path="/" host=huginn-app-here.herokuapp.com request_id=d6d6dafd-19ac-41ca-8c62-70f90cfe60e0 fwd="52.0.196.119" dyno=web.1 connect=1ms service=14ms status=200 bytes=4865
    2015-11-28T19:35:19.563741+00:00 heroku[router]: at=info method=GET path="/worker_status?since_id=93554" host=huginn-app-here.herokuapp.com request_id=823c52f3-07e0-4d60-89bb-3dbbe2211e17 fwd="73.241.186.22" dyno=web.1 connect=0ms service=24ms status=200 bytes=1076
    2015-11-28T19:35:21.706512+00:00 heroku[router]: at=info method=GET path="/worker_status?since_id=93554" host=huginn-app-here.herokuapp.com request_id=c63e64ce-86c6-4d3a-a9ae-238b0c0bbc06 fwd="73.241.186.22" dyno=web.1 connect=1ms service=38ms status=200 bytes=1076
    2015-11-28T19:35:22.837301+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e] Started GET "/agents/new" for 73.241.186.22 at 2015-11-28 19:35:22 +0000
    2015-11-28T19:35:22.840594+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e] Processing by AgentsController#new as HTML
    2015-11-28T19:35:23.840072+00:00 heroku[router]: at=info method=GET path="/worker_status?since_id=93554" host=huginn-app-here.herokuapp.com request_id=fb340d27-5370-47f0-8268-4b612539c224 fwd="73.241.186.22" dyno=web.1 connect=1ms service=27ms status=200 bytes=1076
    2015-11-28T19:35:24.175996+00:00 heroku[router]: at=info method=GET path="/agents/new" host=huginn-app-here.herokuapp.com request_id=8c75a51f-ab6e-4e07-8a84-2ad15943808e fwd="73.241.186.22" dyno=web.1 connect=0ms service=1338ms status=200 bytes=35180
    2015-11-28T19:35:24.104239+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e]   Rendered agents/_oauth_dropdown.html.erb (0.6ms)
    2015-11-28T19:35:24.160134+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e]   Rendered agents/_form.html.erb (1309.5ms)
    2015-11-28T19:35:24.163385+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e]   Rendered layouts/_navigation.html.erb (2.1ms)
    2015-11-28T19:35:24.163954+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e]   Rendered application/_upgrade_warning.html.erb (0.0ms)
    2015-11-28T19:35:24.159632+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e]   Rendered agents/_options.erb (1.5ms)
    2015-11-28T19:35:24.163664+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e]   Rendered layouts/_messages.html.erb (0.1ms)
    2015-11-28T19:35:24.172058+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e] Completed 200 OK in 1331ms (Views: 1304.2ms | ActiveRecord: 22.8ms)
    2015-11-28T19:35:24.160489+00:00 app[web.1]: [8c75a51f-ab6e-4e07-8a84-2ad15943808e]   Rendered agents/new.html.erb within layouts/application (1311.8ms)
    2015-11-28T19:35:24.457896+00:00 heroku[router]: at=info method=GET path="/assets/ace-6bab685c062b6636acfe234f963c5abb547c373835e5092eaf523b949a835b06.js" host=huginn-app-here.herokuapp.com request_id=86cb2229-a50c-45b1-927d-5ea0964197c3 fwd="73.241.186.22" dyno=web.1 connect=1ms service=3ms status=304 bytes=156
    2015-11-28T19:35:25.009473+00:00 heroku[router]: at=info method=GET path="/assets/json-editor/add-c06a52df3361df380a02a45159a0858d6f7cd8cbc3f71ff732a65d6c25ea6af6.png" host=huginn-app-here.herokuapp.com request_id=24f155bd-0dfb-4830-868a-a5bc3453b6c3 fwd="73.241.186.22" dyno=web.1 connect=0ms service=13ms status=304 bytes=156
    2015-11-28T19:35:24.989313+00:00 heroku[router]: at=info method=GET path="/assets/select2x2-6fe28d687dc0ed4d96016238c608ba1e7198c9c9accfa0b360b78018b9fb9bc2.png" host=huginn-app-here.herokuapp.com request_id=22fcd113-a62b-46b0-be32-144b2cfa7bb2 fwd="73.241.186.22" dyno=web.1 connect=1ms service=2ms status=304 bytes=156
    2015-11-28T19:35:24.852682+00:00 heroku[router]: at=info method=GET path="/worker_status" host=huginn-app-here.herokuapp.com request_id=e404c8b2-5092-4c41-a307-395d515e33dd fwd="73.241.186.22" dyno=web.1 connect=0ms service=62ms status=200 bytes=1102
    2015-11-28T19:35:26.900453+00:00 heroku[router]: at=info method=GET path="/agents/type_details?type=Agents%3A%3APublicTransportAgent" host=huginn-app-here.herokuapp.com request_id=0b070417-551d-4458-9847-1ae113c0ead7 fwd="73.241.186.22" dyno=web.1 connect=0ms service=20ms status=200 bytes=5749
    2015-11-28T19:35:26.981097+00:00 heroku[router]: at=info method=GET path="/worker_status?since_id=93554" host=huginn-app-here.herokuapp.com request_id=77302ee1-b58f-4fd9-9d1b-4f09688f88ea fwd="73.241.186.22" dyno=web.1 connect=1ms service=24ms status=200 bytes=1076
    2015-11-28T19:35:26.879126+00:00 app[web.1]: [0b070417-551d-4458-9847-1ae113c0ead7] Started GET "/agents/type_details?type=Agents%3A%3APublicTransportAgent" for 73.241.186.22 at 2015-11-28 19:35:26 +0000
    2015-11-28T19:35:26.895990+00:00 app[web.1]: [0b070417-551d-4458-9847-1ae113c0ead7]   Rendered agents/_options.erb (0.4ms)
    2015-11-28T19:35:26.882164+00:00 app[web.1]: [0b070417-551d-4458-9847-1ae113c0ead7] Processing by AgentsController#type_details as JSON
    2015-11-28T19:35:26.882195+00:00 app[web.1]: [0b070417-551d-4458-9847-1ae113c0ead7]   Parameters: {"type"=>"Agents::PublicTransportAgent"}
    2015-11-28T19:35:26.895441+00:00 app[web.1]: [0b070417-551d-4458-9847-1ae113c0ead7]   Rendered agents/_oauth_dropdown.html.erb (0.1ms)
    2015-11-28T19:35:26.896710+00:00 app[web.1]: [0b070417-551d-4458-9847-1ae113c0ead7] Completed 200 OK in 14ms (Views: 0.5ms | ActiveRecord: 1.9ms)
    2015-11-28T19:35:27.301546+00:00 heroku[router]: at=info method=GET path="/assets/json-editor/delete-ce07a8b5022e59a1bde9690b720a6bf10fc9767db6512d14ebff2782ec62b5bf.png" host=huginn-app-here.herokuapp.com request_id=4f545757-9f85-4099-b5f3-1bc94fd665ed fwd="73.241.186.22" dyno=web.1 connect=1ms service=1ms status=304 bytes=156
    2015-11-28T19:35:29.126445+00:00 heroku[router]: at=info method=GET path="/worker_status?since_id=93554" host=huginn-app-here.herokuapp.com request_id=13d3d4df-88e1-4457-bcac-c9899ce3c3f9 fwd="73.241.186.22" dyno=web.1 connect=0ms service=22ms status=200 bytes=1076
    2015-11-28T19:35:30.623137+00:00 app[web.1]: [b8776e32-fee4-4a71-9cb2-acb76901e8dd] Started POST "/agents" for 73.241.186.22 at 2015-11-28 19:35:30 +0000
    2015-11-28T19:35:30.706042+00:00 app[web.1]: [b8776e32-fee4-4a71-9cb2-acb76901e8dd]
    2015-11-28T19:35:30.706045+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::InsufficientPrivilege: ERROR:  permission denied for relation agents
    2015-11-28T19:35:30.706046+00:00 app[web.1]: : INSERT INTO "agents" ("type", "name", "schedule", "options", "user_id", "guid", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"):
    2015-11-28T19:35:30.706047+00:00 app[web.1]:   app/concerns/dry_runnable.rb:51:in `save'
    2015-11-28T19:35:30.706048+00:00 app[web.1]:   app/controllers/agents_controller.rb:171:in `block in create'
    2015-11-28T19:35:30.706049+00:00 app[web.1]:   app/controllers/agents_controller.rb:170:in `create'
    2015-11-28T19:35:30.706050+00:00 app[web.1]:   config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'
    2015-11-28T19:35:30.706051+00:00 app[web.1]:
    2015-11-28T19:35:30.706051+00:00 app[web.1]:
    2015-11-28T19:35:30.628068+00:00 app[web.1]: [b8776e32-fee4-4a71-9cb2-acb76901e8dd] Processing by AgentsController#create as HTML
    2015-11-28T19:35:30.628164+00:00 app[web.1]: [b8776e32-fee4-4a71-9cb2-acb76901e8dd]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"AKxmpbnJFYZA7Y1KB8BM8hR6M+2Rm5e79SmvJ2fRw4Y+vSrOLo8mxApLYns7sVqxpVe4/8T8nVOsZepB2N9tTg==", "return"=>"", "agent"=>{"type"=>"Agents::PublicTransportAgent", "name"=>"asdf", "schedule"=>"every_2m", "control_target_ids"=>[""], "keep_events_for"=>"0", "source_ids"=>[""], "propagate_immediately"=>"0", "scenario_ids"=>[""], "options"=>"{\r\n  \"agency\": \"sf-muni\",\r\n  \"stops\": [\r\n    \"N|5221\",\r\n    \"N|5215\"\r\n  ],\r\n  \"alert_window_in_minutes\": 5\r\n}"}, "commit"=>"Save"}
    2015-11-28T19:35:30.701330+00:00 app[web.1]: [b8776e32-fee4-4a71-9cb2-acb76901e8dd] PG::InsufficientPrivilege: ERROR:  permission denied for relation agents
    2015-11-28T19:35:30.701334+00:00 app[web.1]: : INSERT INTO "agents" ("type", "name", "schedule", "options", "user_id", "guid", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"
    2015-11-28T19:35:30.703718+00:00 app[web.1]: [b8776e32-fee4-4a71-9cb2-acb76901e8dd] Completed 500 Internal Server Error in 75ms (ActiveRecord: 44.3ms)
    2015-11-28T19:35:30.713341+00:00 heroku[router]: at=info method=POST path="/agents" host=huginn-app-here.herokuapp.com request_id=b8776e32-fee4-4a71-9cb2-acb76901e8dd fwd="73.241.186.22" dyno=web.1 connect=0ms service=103ms status=500 bytes=951
    WootWoot:huginn-app-here Tom$

**Comment by dsander** [comment]
It is possible that you exceeded the database limit of the free plan, `heroku pg:info` should give some information about that. To reduce the amount of database rows, you can change the `Keep events` option of your agents to something lower or delete some agent logs.

**Comment by wootwoot1234** [comment]
Thanks.  I ran ```heroku pg:info``` and got:

    === HEROKU_POSTGRESQL_NAVY_URL, DATABASE_URL
    Plan:        Hobby-dev
    Status:      Available
    Connections: 7/20
    PG Version:  9.3.9
    Created:     2015-03-20 20:58 UTC
    Data Size:   331.1 MB
    Tables:      12
    Rows:        76113/10000 (Write access revoked)
    Fork/Follow: Unsupported
    Rollback:    Unsupported


Then went though all the agents, deleted events and set them to only keep them for 1 day.  Now I'm getting:

    === HEROKU_POSTGRESQL_NAVY_URL, DATABASE_URL
    Plan:        Hobby-dev
    Status:      Available
    Connections: 7/20
    PG Version:  9.3.9
    Created:     2015-03-20 20:58 UTC
    Data Size:   331.1 MB
    Tables:      12
    Rows:        45449/10000 (Write access revoked)
    Fork/Follow: Unsupported
    Rollback:    Unsupported

So less rows but it doesn't look like I was ever at the 10000 row limit and still getting the error.  The "Write access revoked" doesn't look good.  Maybe it will take a few hours for heroku to give me write access again?  I'll check again in a few hours and report back.

**Comment by wootwoot1234** [comment]
@dsander Thanks for the help.  It just took about 10 minutes for Heroku to update and I now am "In compliance".

**Comment by dsander** [comment]
Great, glad it worked!

**Comment by cantino** [comment]
If this keeps happening to people, we could try to detect "PG::InsufficientPrivilege" and message about it.

**Comment by wootwoot1234** [comment]
That would be very helpful for someone who doesn't know there way around
Heroku.

**Comment by cantino** [comment]
Since this hasn't come up again, I'm going to leave this as-is.  Hopefully anyone else having this issue will find this post.
