### ISSUE TITLE
Crashes with Twitter

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#1191]
I've been getting a lot of intermittent crashes since we moved to @dsander's threaded worker system.  (Which otherwise works great!)  They seem to mostly happen around Twitter stream agents.  Here's a recent one:

```
(2015-12-27 02:04:42 -0800) Twitter News Event Source received: Amazing Fallout 4 news
Queuing schedule for every_1m
Queuing event propagation
Queuing schedule for every_2m
Restarting Agents::TwitterStreamAgent-9-ad7a059ed25bd3ad993dfa836be45e5a966f453c
Queuing schedule for every_1m
Queuing event propagation
Agent#48: Exception during check. execution expired: /home/huginn/app/shared/bundle/ruby/2.1.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:37:in `rescue in perform'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:32:in `perform'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:96:in `perform_request_with_objects'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:140:in `objects_from_response_with_user'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/twitter-5.14.0/lib/twitter/rest/timelines.rb:49:in `user_timeline'
/home/huginn/app/releases/20151219192304/app/models/agents/twitter_user_agent.rb:99:in `check'
/home/huginn/app/releases/20151219192304/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activejob-4.2.4/lib/active_job/execution.rb:32:in `block in perform_now'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/huginn/app/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
```

Then the stream agent never starts back up.

Are other people having this issue?  I've run out of ideas on how to debug it.

**Comment by dsander** [comment]
The timed out TwitterUserAgent killed the twitter stream? Are you sure the cause wasn't one of the other random issues we are seeing with the stream?

I am starting to think the problem could be DelayedJob not being thread safe, it uses [Timeout.timeout](https://github.com/collectiveidea/delayed_job/blob/5f914105c1c38ca73a486d63de8ad62f254b3d72/lib/delayed/worker.rb#L226) which is known to cause problems with threads.

**Comment by wasafiri** [comment]
I use Sidekiq in one of my apps with very good results. I run it on Heroku with just one dyno by using Unicorn and a before_fork method in its initializer. I see you use Unicorn, so it should work nicely. It does require Redis, however, which makes setup a little bit more complicated.

**Comment by dsander** [comment]
Thanks @wasafiri, certainly sidekiq is a good option to replace DJ but it would require some work to ensure all of our agent and their dependencies are thread safe, which they are probably not at the moment.

**Comment by ohingardail** [comment]
I too gets heaps of these (or similar) errors from the Twitter User Agent:
```
Exception during check. execution expired: /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:37:in `rescue in perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:32:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:96:in `perform_request_with_objects'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:140:in `objects_from_response_with_user'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/timelines.rb:49:in `user_timeline'
/home/huginn/huginn/app/models/agents/twitter_user_agent.rb:107:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
:
:
```
I also get something similar on the Twitter Action Agent, which returns events like this
```
{
  "success": false,
  "error": "execution expired",
  "tweets": {
    "764086890035236867": "Mark Morris plays at the centre for @ClubVelocity in September! https://t.co/nwAuKzfcl4"
  },
  "agent_ids": [
    191
  ],
  "event_ids": [
    186640
  ]
}
```
... but nothing in the that agent's log page, which seems a little unexpected.

Between them, these issues render tweeting from Huginn very unpredictable.

**Comment by cantino** [comment]
This is with sidekiq @ohingardail?

**Comment by ohingardail** [comment]
I don't have the sidekiq Ruby gem installed, so I guess not. I got the impression from previous comments on this issue, and other issues (#789), that using sidekiq was a non-standard and undocumented solution that may cause unexpected effects, so I am wary of making such a change.

**Comment by cantino** [comment]
Yes, @ohingardail, that's why I was asking. I wanted to make sure it wasn't SideKiq-related. 

This actually looks like a timeout on the Twitter side.  Does this happen consistently, or just during a short window when maybe they were having technical issues?

**Comment by ohingardail** [comment]
There doesn't appear to be a pattern - or any consistency - when it works or when it doesn't, except that it has been acting this way, on and off, ever since I set up Huginn retweeting a couple of weeks ago. It's actually very difficult to tell where the fault lies; the Twitter API status page (https://dev.twitter.com/overview/status) offers no insights into failure at their end. If you have any clues where I could look (in logs, or elsewhere) I would be grateful.

**Comment by dsander** [comment]
@cantino @ohingardail That looks like a timeout by `DelayedJob` probably because the Twitter API did not answer in time, you can increase `DELAYED_JOB_MAX_RUNTIME` but the default 2 minutes should be more then enough when the API is working.

**Comment by ohingardail** [comment]
@dsander Thanks, but I had already put ```DELAYED_JOB_MAX_RUNTIME``` to 30 mins in an attempt to remove this potential issue as a contender. My latest wheeze is to use the ```Old version with separate processes``` in ```Procfile``` instead of the standard threaded workers to see if that makes any difference - but this is only a wild guess.

**Comment by cantino** [comment]
@dsander But then how did the payload end up looking like `"error": "execution expired"`?

**Comment by dsander** [comment]
@cantino Oh, right the timeout are coming from the `twitter` gem, the [defaults look reasonable](https://github.com/sferik/twitter/blob/v5.14.0/lib/twitter/rest/client.rb#L36-L37), but will not match the DJ max runtime. 

@ohingardail We could try to increase the timeouts, but I am not sure if that will help, if the API does not finish in 30 seconds the request might just hang somewhere in their backend. Do you get failed jobs for the `TwitterUserAgent` or do the job succeed in one of the retries?

The real issue I see is the `TwitterActionAgent` rescuing the exceptions, which means the agent run can not be retried.

**Comment by ohingardail** [comment]
@dsander The ```TwitterUserAgent``` does work occasionally, although I don't know how to work out if this occurs "in one of the retries" or not. It's not apparent to me how to tie up a given emitted event to a set of retries - if you know how, please say!

**Comment by cantino** [comment]
I don't think it's retrying, because it's being caught by the Twitter gem.

**Comment by dsander** [comment]
@ohingardail When the `TwitterUserAgent` succeeds in one of its retries you will not see any failed jobs in the `Account -> Job Management` page. My user agent has some failed jobs listed about a month ago, since then everything looks fine.

@cantino The `TwitterUserAgent` and `TwitterActionAgent` work differently the user agent does not rescue exception and thus gets retried when it fails. The action agent [rescues the twitter gem exception](https://github.com/cantino/huginn/blob/master/app/models/agents/twitter_action_agent.rb#L56-L63) and emits an event and is never retried. I imagine it would require a very complex scenario to handle the "error events" and for most of the users it would be best to simply retry the Agent run.

**Comment by ohingardail** [comment]
@dsander @cantino In which case, yes, there have been failed jobs associated with the ```TwitterActionAgent``` showing 5 attempts and 'Execution expired' as the last error.

**Comment by cantino** [comment]
@dsander do you think we should change one of the implementations, then?

@ohingardail It's odd that only you're reporting this.  I wonder if your account is getting rate limited in a non-obvious way?

**Comment by dsander** [comment]
@ohingardail What is the time frame for the 5 failures?

@cantino Yes I think we should make the rescuing of the `TwitterActionAgent` optional, the normal retry workflow makes more sense to me. I might have time to work on this tomorrow.

**Comment by ohingardail** [comment]
@cantino The Twitter agents are behaving themselves today, after I restarted the VM Huginn was running on. 
@dsander Restarts were configured to 5 attempts with 60 secs between.

**Comment by dsander** [comment]
@ohingardail To my understanding the `TwitterActionAgent` should not create failed jobs in the `Job Management` page, I was asking about the `TwitterUserAgent`.

What kind of restarts do you mean?

**Comment by ohingardail** [comment]
@dsander I may have misspoke; all retries (that failed) had 5 attempts and I don't know where that 5 is configured. I think the 60 secs between comes from DELAYED_JOB_SLEEP_DELAY in .env, so the 'timeframe' for the 5 failures is 5 minutes.

**Comment by ohingardail** [comment]
@dsander @cantino Right; after a day and a bit following an upgrade to the latest Huginn and a VM reboot I've had no further issues with the ```TwitterActionAgent``` (although the ```TwitterUserAgent``` still returns "execution expired" in its log and retries successfully from time to time). Unless it happens again, I suspect there's nothing much anybody can do to track it down; it might have been a transient issue on my machine or (as mentioned above) with Twitter. If you get any lightbulb moments and want me to check a log or a setting for something, please say, otherwise I'm going to just keep an eye out for a re-occurrence.

**Comment by ohingardail** [comment]
@dsander @cantino OK; it happened again. The ```Twitter Action Agent ``` received three events at about the same time, successfully retweeted two of them and ```execution expired``` one of them:
```
{
  "success": false,
  "error": "execution expired",
  "tweets": {
    "768025786809024512": "Kabaret Kollective with @MariaBaroness returns on Saturday 3rd September! https://t.co/6CSRrzVOqb #rdguk"
  },
  "agent_ids": [
    191
  ],
  "event_ids": [
    193455
  ]
}
```
The log page of the errant agent showed no log data.There are currently no jobs outstanding (although I don't watch this page all the time, so I don't know what the job status was when this issue occurred).
The Twitter service status page https://dev.twitter.com/overview/status shows all OK except 'performance issues' on '/1.1/search/tweets' with an uptime of 97.1%.
Is there any other data I can extract that would be useful for diagnosis?

**Comment by cantino** [comment]
I just had the Twitter stream stop again. (My Gap Detector Agent notifies me now.)  No error in the log, it just has:

```
(2017-01-09 04:56:51 -0800) Twitter News Event Source received: Kung wala lang pasok at nasa Lemery ako .
(2017-01-09 04:56:51 -0800) Twitter News Event Source received: ¡Asombroso! Fotografían un OVNI en forma de la nav
e 'Enterprise' de Star Trek sobre una isla ca… https://t.co/P7cg2hTYQ3 vía @radio_santiago
(2017-01-09 04:56:51 -0800) Twitter News Event Source received: La NASA capta una espectacular imagen de la Tierra
 y la Luna desde Marte https://t.co/MjhDp5yl0e
Killing Agents::TwitterStreamAgent-28-9a12c2dc87c833fd37ada0808dabc98a8129a31f
Starting Agents::TwitterStreamAgent-28-f67f2fd0f014c856069abce1393fd8ed539d7cfe
Queuing event propagation
Queuing schedule for every_1m
Queuing schedule for every_5m
Queuing event propagation
```

As you can see, it kills the TwitterStreamAgent, then claims to bring it back up, but it never starts streaming again.  Any ideas where I should look to debug?

**Comment by dsander** [comment]
Did you modify the Agent just before that happened? The config hash changed for that Agent which should only happen when the options were modified or the oauth_token changed (which should never happen for twitter as far as I know).
Can you "revive" the stream by disabling the agent for a few minutes (to avoid reconnection rate limiting) and then enabling it again?

Debugging the threaded background process is really tricky, I only know either `strace`, `rbtrace` or `puts` debugging. Tracing works better when every background process is running on its own.

**Comment by cantino** [comment]
No, I wasn't using Huginn when it happened.

Next time it happens I'll try disabling and re-enabling.

**Comment by dsander** [comment]
Hmm am I missing some condition which would change the worker id? https://github.com/cantino/huginn/blob/master/app/models/agents/twitter_stream_agent.rb#L135-L146
Not sure if that is even the root cause. I am just curious to find a lead, because my TwitterStreamAgent has been working without issues for a long time now.

**Comment by cantino** [comment]
Maybe we should sort it?

**Comment by dsander** [comment]
Are you using postgres? I guess it could happen that the agents are returned in a different order without explicitly ordering them in the query.

**Comment by cantino** [comment]
I'm on PG, yes. Migrated from mysql a few months ago.

**Comment by dsander** [comment]
How is that working for you all? I did not notice any hiccups on my instances for quite some time now.

**Comment by cantino** [comment]
So far so good!
