### ISSUE TITLE
Difficulty deploying updates by capistrano

### ISSUE THREAD

**Issue by vx28643** [cantino/huginn#1255]
I am sorry to bother you with what is probably a very newbie question, but I am having trouble [deploying updates by capistrano](https://github.com/cantino/huginn/blob/master/doc/manual/capistrano.md) after following the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md)

The error I am getting is as follows:
```
root@huginn:/home/huginn/huginn# cap production deploy
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- capistrano/cli (LoadError)
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/bin/cap:3:in `<main>'
```

The guide does not mention how to install capistrano. You can see here I did `apt-get install capistrano` which perhaps was wrong.

```
root@huginn:/home/huginn/huginn# cap production deploy
The program 'cap' is currently not installed. You can install it by typing:
apt-get install capistrano

root@huginn:/home/huginn/huginn# apt-get install capistrano
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libruby1.9.1 ruby ruby-highline ruby-net-scp ruby-net-sftp ruby-net-ssh
  ruby-net-ssh-gateway ruby1.9.1
Suggested packages:
  ri ruby-dev ruby1.9.1-examples ri1.9.1 ruby1.9.1-dev ruby-switch
The following NEW packages will be installed:
  capistrano libruby1.9.1 ruby ruby-highline ruby-net-scp ruby-net-sftp
  ruby-net-ssh ruby-net-ssh-gateway ruby1.9.1
0 upgraded, 9 newly installed, 0 to remove and 11 not upgraded.
Need to get 2,963 kB of archives.
After this operation, 14.2 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://mirrors.digitalocean.com/ubuntu/ trusty-updates/main libruby1.9.1 amd64 1.9.3.484-2ubuntu1.2 [2,645 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu/ trusty-updates/main ruby1.9.1 amd64 1.9.3.484-2ubuntu1.2 [35.6 kB]
Get:3 http://mirrors.digitalocean.com/ubuntu/ trusty/main ruby all 1:1.9.3.4 [5,334 B]
Get:4 http://mirrors.digitalocean.com/ubuntu/ trusty/universe ruby-net-ssh all 1:2.6.8-1 [93.4 kB]
Get:5 http://mirrors.digitalocean.com/ubuntu/ trusty/universe ruby-net-sftp all 1:2.1.2-1 [41.0 kB]
Get:6 http://mirrors.digitalocean.com/ubuntu/ trusty/universe ruby-net-scp all 1.1.1-1 [15.9 kB]
Get:7 http://mirrors.digitalocean.com/ubuntu/ trusty/universe ruby-net-ssh-gateway all 1.2.0-1 [8,084 B]
Get:8 http://mirrors.digitalocean.com/ubuntu/ trusty/universe ruby-highline all 1.6.20-1 [40.0 kB]
Get:9 http://mirrors.digitalocean.com/ubuntu/ trusty/universe capistrano all 2.12.0-1 [78.7 kB]
Fetched 2,963 kB in 3s (926 kB/s)
Selecting previously unselected package libruby1.9.1.
(Reading database ... 98438 files and directories currently installed.)
Preparing to unpack .../libruby1.9.1_1.9.3.484-2ubuntu1.2_amd64.deb ...
Unpacking libruby1.9.1 (1.9.3.484-2ubuntu1.2) ...
Selecting previously unselected package ruby1.9.1.
Preparing to unpack .../ruby1.9.1_1.9.3.484-2ubuntu1.2_amd64.deb ...
Unpacking ruby1.9.1 (1.9.3.484-2ubuntu1.2) ...
Selecting previously unselected package ruby.
Preparing to unpack .../ruby_1%3a1.9.3.4_all.deb ...
Unpacking ruby (1:1.9.3.4) ...
Selecting previously unselected package ruby-net-ssh.
Preparing to unpack .../ruby-net-ssh_1%3a2.6.8-1_all.deb ...
Unpacking ruby-net-ssh (1:2.6.8-1) ...
Selecting previously unselected package ruby-net-sftp.
Preparing to unpack .../ruby-net-sftp_1%3a2.1.2-1_all.deb ...
Unpacking ruby-net-sftp (1:2.1.2-1) ...
Selecting previously unselected package ruby-net-scp.
Preparing to unpack .../ruby-net-scp_1.1.1-1_all.deb ...
Unpacking ruby-net-scp (1.1.1-1) ...
Selecting previously unselected package ruby-net-ssh-gateway.
Preparing to unpack .../ruby-net-ssh-gateway_1.2.0-1_all.deb ...
Unpacking ruby-net-ssh-gateway (1.2.0-1) ...
Selecting previously unselected package ruby-highline.
Preparing to unpack .../ruby-highline_1.6.20-1_all.deb ...
Unpacking ruby-highline (1.6.20-1) ...
Selecting previously unselected package capistrano.
Preparing to unpack .../capistrano_2.12.0-1_all.deb ...
Unpacking capistrano (2.12.0-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up ruby (1:1.9.3.4) ...
Setting up ruby-net-ssh (1:2.6.8-1) ...
Setting up ruby-net-sftp (1:2.1.2-1) ...
Setting up ruby-net-scp (1.1.1-1) ...
Setting up ruby-net-ssh-gateway (1.2.0-1) ...
Setting up ruby-highline (1.6.20-1) ...
Setting up capistrano (2.12.0-1) ...
Setting up ruby1.9.1 (1.9.3.484-2ubuntu1.2) ...
Setting up libruby1.9.1 (1.9.3.484-2ubuntu1.2) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...

root@huginn:/home/huginn/huginn# cap production deploy
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- capistrano/cli (LoadError)
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/bin/cap:3:in `<main>'
```
Any help to get me on track is appreciated :)

**Comment by signallhill** [comment]
Are you running production? If so then Capistrano will not work. Check #1092.

**Comment by vx28643** [comment]
Thank you for your reply, that may explain it. Perhaps I should not be running production - that's a little unclear to me. The installation is purely for my own use, installed on a VPN.

I will try the [manual](https://github.com/cantino/huginn/blob/master/doc/manual/update.md) procedure instead.

**Comment by cantino** [comment]
Capistrano is used to push updates from your local machine (development) to the production machine, so you always run it as a development user.
