### ISSUE TITLE
High load caused by runsvdir

### ISSUE THREAD

**Issue by xaxes** [cantino/huginn#1270]
![image](https://cloud.githubusercontent.com/assets/1886899/12843312/c26caaf2-cbf8-11e5-8188-42547996d298.png)
The highlighted process is the reason of such a high load. The full name is
```runsvdir -P /etc/service log: undler/friendly_errors.rb:3:in `<top (required)>' ?from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require' ?from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require' ?from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:16:in `<top (required)>' ?from /usr/local/bin/bundle:23:in `load' ?from /usr/local/bin/bundle:23:in `<main>'```

Here's my .env file
```
# ==== Required configuration settings for Huginn ====

# Replace the following with the output from "rake secret"
APP_SECRET_TOKEN=[RESTRICTED]

# This is the domain where your Huginn instance will be running. The default should work
# for development, but it needs to be changed to your Huginn domain when you deploy to a
# production environment (e.g., yourdomain.com, possibly including a port).
DOMAIN=localhost:3000

# Optionally set an asset host
# ASSET_HOST=http://assets.example.com

############################
#      Database Setup      #
############################

DATABASE_ADAPTER=mysql2
#DATABASE_ENCODING=utf8
DATABASE_RECONNECT=true
DATABASE_NAME=huginn_production
DATABASE_POOL=20
DATABASE_USERNAME=huginn
DATABASE_PASSWORD=[RESTRICTED]
#DATABASE_HOST=your-domain-here.com
#DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock

# MySQL only: If you are running a MySQL server >=5.5.3, you should
# set DATABASE_ENCODING to utf8mb4 instead of utf8 so that the
# database can hold 4-byte UTF-8 characters like emoji.
DATABASE_ENCODING=utf8mb4

# ==== Additional required production settings ====

# Configure Rails environment.  This should only be needed in production and may cause errors in development.
RAILS_ENV=production

# Should Rails force all requests to use SSL?
FORCE_SSL=false

############################
#     Allowing Signups     #
############################

# This invitation code will be required for users to signup with your Huginn installation.
# You can see its use in user.rb.  PLEASE CHANGE THIS!
INVITATION_CODE=[RESTRICTED]

# If you don't want to require new users to have an invitation code in order to sign up, set this to true.
SKIP_INVITATION_CODE=false

#############################
#    Email Configuration    #
#############################

# Outgoing email settings.  To use Gmail or Google Apps, put your Google Apps domain or gmail.com
# as the SMTP_DOMAIN and your Gmail username and password as the SMTP_USER_NAME and SMTP_PASSWORD.
#
# PLEASE NOTE: In order to enable sending real emails via SMTP locally (e.g., when not in the production Rails environment),
# you must also set SEND_EMAIL_IN_DEVELOPMENT to true below.
#
# If you have trouble with port 587 on Gmail, you can also try setting
# SMTP_AUTHENTICATION to login and the SMTP_PORT to 465.

SMTP_DOMAIN=gmail.com
SMTP_USER_NAME=xaxees@gmail.com
SMTP_PASSWORD=[RESTRICTED]
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# Set to true to send real emails via SMTP when running in the development Rails environment.
# Set to false to have emails intercepted in development and displayed at http://localhost:3000/letter_opener
SEND_EMAIL_IN_DEVELOPMENT=false

# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=xaxees@gmail.com

###########################
#      Agent Logging      #
###########################

# Number of lines of log messages to keep per Agent
AGENT_LOG_LENGTH=200

########################################################################################################
#    OAuth Configuration                                                                               #
#  More information at the wiki: https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications #
########################################################################################################

TWITTER_OAUTH_KEY=
TWITTER_OAUTH_SECRET=

THIRTY_SEVEN_SIGNALS_OAUTH_KEY=
THIRTY_SEVEN_SIGNALS_OAUTH_SECRET=

GITHUB_OAUTH_KEY=
GITHUB_OAUTH_SECRET=

TUMBLR_OAUTH_KEY=
TUMBLR_OAUTH_SECRET=

DROPBOX_OAUTH_KEY=
DROPBOX_OAUTH_SECRET=

WUNDERLIST_OAUTH_KEY=
WUNDERLIST_OAUTH_SECRET=

EVERNOTE_OAUTH_KEY=
EVERNOTE_OAUTH_SECRET=
# Set to true in development, false in production
USE_EVERNOTE_SANDBOX=true

#############################
#  AWS and Mechanical Turk  #
#############################

# AWS Credentials for MTurk
AWS_ACCESS_KEY_ID="your aws access key id"
AWS_ACCESS_KEY="your aws access key"

# Set AWS_SANDBOX to true if you're developing Huginn code.
AWS_SANDBOX=false

########################
#   Various Settings   #
########################

# Specify the HTTP backend library for Faraday, commonly used by
# WebsiteAgent, RssAgent and PostAgent.  You can change this depending
# on the performance and stability you need for your service.  Any
# choice other than "typhoeus", "net_http", or "em_http" should
# require you to bundle a corresponding gem via Gemfile.
FARADAY_HTTP_BACKEND=typhoeus

# Specify the default User-Agent header value for HTTP requests made
# by Agents that allow overriding the User-Agent header value.
DEFAULT_HTTP_USER_AGENT="Huginn - https://github.com/cantino/huginn"

# Allow JSONPath eval expresions. i.e., $..price[?(@ < 20)]
# You should not allow this on a shared Huginn box because it is not secure.
ALLOW_JSONPATH_EVAL=false

# Enable this setting to allow insecure Agents like the ShellCommandAgent.  Only do this
# when you trust everyone using your Huginn installation.
ENABLE_INSECURE_AGENTS=true

# Enable this setting to allow second precision schedule in
# SchedulerAgent.  By default, the use of the "second" field is
# restricted so that any value other than a single zero (which means
# "on the minute") is disallowed to prevent abuse of service.
ENABLE_SECOND_PRECISION_SCHEDULE=false

# Specify the scheduler frequency in seconds (default: 0.3).
# Increasing this value will help reduce the use of system resources
# at the expense of time accuracy.
SCHEDULER_FREQUENCY=0.3

# Specify the frequency with which the scheduler checks for and cleans up expired events.
# You can use `m` for minutes, `h` for hours, and `d` for days.
EVENT_EXPIRATION_CHECK=6h

# Use Graphviz for generating diagrams instead of using Google Chart
# Tools.  Specify a dot(1) command path built with SVG support
# enabled.
#USE_GRAPHVIZ_DOT=dot

# Default layout for agent flow diagrams generated by Graphviz.
# Choose from `circo`, `dot` (default), `fdp`, `neato`, `osage`,
# `patchwork`, `sfdp`, or `twopi`.  Note that not all layouts are
# supported by Graphviz depending on the build options.
#DIAGRAM_DEFAULT_LAYOUT=dot

# Timezone. Use `rake time:zones:local` or `rake time:zones:all` to get your zone name
TIMEZONE="Warsaw"

# Number of failed jobs to keep in the database
FAILED_JOBS_TO_KEEP=100

# Maximum runtime of background jobs in minutes
DELAYED_JOB_MAX_RUNTIME=2

# Amount of seconds for delayed_job to sleep before checking for new jobs
DELAYED_JOB_SLEEP_DELAY=10

###############################################################
# Capistrano deployment, read the documentation:              #
# https://github.com/cantino/huginn/doc/manual/capistrano.md  #
###############################################################

#CAPISTRANO_DEPLOY_SERVER=
#CAPISTRANO_DEPLOY_USER=
#CAPISTRANO_DEPLOY_REPO_URL=
```
I'm starting my Huginn with `sudo systemctl start huginn`. What is wrong with my setup?

**Comment by cantino** [comment]
What load are you seeing?  It looks like 3.8% CPU?

**Comment by xaxes** [comment]
Actually, there isn't any process highly using CPU, but when I kill this one, everything is normal again.

**Comment by dsander** [comment]
Do you have any suspicious entries in the [log files](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting)?

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
