### ISSUE TITLE
How to compile LibV8 in FreeBSD env.

### ISSUE THREAD

**Issue by alxcord** [cantino/huginn#1350]
Hi,

Sory I'm new on Unix world, I'm trying to complile Huginn on an FreeNAS jail. 

Following (as I can) the installation guid (https://github.com/cantino/huginn/blob/master/doc/manual/installation.md), when I compile the gems (sudo -u huginn -H bundle install --deployment --without development test) I got an error:
```

An error occurred while installing libv8 (3.16.14.13), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.16.14.13'` succeeds before bundling.
```

This is the second time I make this jail (yes, I deleted it and tried from the ground), I tried that option "--with-system-v8" in the previous try it complites Ok but got another error.in other bundle step.

running with debug (gem install libv8 -v '3.16.14.13' --backtrace --debug) I got an huge log:

..
```

Exception `Errno::EEXIST' at /usr/local/lib/ruby/2.1/fileutils.rb:250 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.1/extensions/amd64-freebsd-9/2.1/libv8-3.16.14.13
Exception `Gem::InstallError' at /usr/local/lib/ruby/site_ruby/2.1/rubygems/ext/builder.rb:91 - extconf failed, exit code 1
Exception `Errno::EEXIST' at /usr/local/lib/ruby/2.1/fileutils.rb:250 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.1/extensions/amd64-freebsd-9/2.1/libv8-3.16.14.13
Exception `Gem::Ext::BuildError' at /usr/local/lib/ruby/site_ruby/2.1/rubygems/ext/builder.rb:145 - ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.1/gems/libv8-3.16.14.13/ext/libv8
/usr/local/bin/ruby21 -r ./siteconf20160313-75292-1h2n6eh.rb extconf.rb
creating Makefile
```
...
```
|diff --git a/build/standalone.gypi b/build/standalone.gypi
|index 125c5bf..71641a3 100644
|--- a/build/standalone.gypi
|+++ b/build/standalone.gypi
--------------------------
Patching file build/standalone.gypi using Plan A...
Hunk #1 succeeded at 109 (offset 2 lines).
done
Compiling v8 for x64
Using python 2.7.9
Using compiler: /usr/bin/clang++ (clang version 3.4.1)
"Makefile", line 43: Missing dependency operator
"Makefile", line 45: Need an operator
"Makefile", line 46: Need an operator
"Makefile", line 48: Need an operator
"Makefile", line 50: Need an operator
"Makefile", line 52: Need an operator
"Makefile", line 54: Missing dependency operator
...
"Makefile", line 127: Missing dependency operator
"Makefile", line 129: Need an operator
Error expanding embedded variable.
/usr/local/lib/ruby/gems/2.1/gems/libv8-3.16.14.13/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/usr/local/lib/ruby/gems/2.1/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
        from /usr/local/lib/ruby/gems/2.1/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `each'
        from /usr/local/lib/ruby/gems/2.1/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `verify_installation!'
        from /usr/local/lib/ruby/gems/2.1/gems/libv8-3.16.14.13/ext/libv8/location.rb:26:in `install!'
        from extconf.rb:7:in `<main>'
```

```

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.1/gems/libv8-3.16.14.13 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.1/extensions/amd64-freebsd-9/2.1/libv8-3.16.14.13/gem_make.out
```

GEM ENV:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.1.8 (2015-12-16 patchlevel 440) [amd64-freebsd9]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.1
  - USER INSTALLATION DIRECTORY: /home/huginn/.gem/ruby/2.1
  - RUBY EXECUTABLE: /usr/local/bin/ruby21
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/huginn/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - amd64-freebsd-9
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.1
     - /home/huginn/.gem/ruby/2.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /usr/games
     - /usr/local/sbin
     - /usr/local/bin
     - /root/bin
     - /usr/local/fusion-io
```

**Comment by knu** [comment]
The error messages look like the default make(1) is used when GNU make needs to be used.  Do you have GNU make installed?  It should be at "/usr/local/bin/gmake" or something.

**Comment by knu** [comment]
Also, depending on the version of clang libv8 3.16.14.13 might not build due to its stricter warning/error options.  In that case, try creating the following wrapper script at `/somewhere/clang++` and let the gem/bundle command use it by prefixing `env PATH=/somewhere:$PATH` to the command line:
```sh
#!/bin/sh
/usr/bin/clang++ -Wno-unused-local-typedefs -Wno-tautological-undefined-compare "$@"
```

**Comment by alxcord** [comment]
Hi, the problem was the gmake missing, Thanks so much! Just compiled.
