### ISSUE TITLE
bundle exec rake db:create fails - cannot connect through default socket

### ISSUE THREAD

**Issue by dylankb** [cantino/huginn#1382]
When I run `bundle exec rake db:create` I get an error message saying MySQL `Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)>`

When I navigate to `/var/run` there is no mysqld directory, which may be the root of the problem. I successfully ran `bundle` on my locally cloned directory, so the `mysql2` gem should have installed correctly.  

I'm on Ubuntu 14.04 and believe I used `sudo apt-get install libmysqlclient-dev` command. I was following the Novice install guide up to this point. Most posts on SO about this issue involve troubleshooting a yml file, but I don't see one in the project. Full error message with trace is below:

```
dylan@devmachina:~/ruby/huginn$ bundle exec rake db:create --trace
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
#<Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_development", "pool"=>10, "username"=>"root", "password"=>nil, "host"=>nil, "port"=>nil, "socket"=>nil, "strict"=>false}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
#<Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_test", "pool"=>10, "username"=>"root", "password"=>nil, "socket"=>nil, "port"=>nil, "strict"=>false}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `connect'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `initialize'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_handling.rb:87:in `connection'
/home/dylan/ruby/huginn/lib/ar_mysql_column_charset.rb:7:in `block in establish_connection'
/home/dylan/ruby/huginn/lib/ar_mysql_column_charset.rb:6:in `tap'
/home/dylan/ruby/huginn/lib/ar_mysql_column_charset.rb:6:in `establish_connection'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:109:in `create_current'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/dylan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/dylan/.rbenv/versions/2.2.4/bin/rake:23:in `load'
/home/dylan/.rbenv/versions/2.2.4/bin/rake:23:in `<main>'
```

**Comment by dsander** [comment]
Hi @dylankb,

I recommend you have a look at the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md) it will guide you through all the steps needed to get Huginn up and running.

**Comment by dylankb** [comment]
Woops, missed the step where I actually installed MySQL :S
