### ISSUE TITLE
Can't login after install

### ISSUE THREAD

**Issue by stuartmunn** [cantino/huginn#1383]
Hi - I've followed the instructions in installation.md and have got to a point where the login screen is presented when I try the webpage, but I'm unable to login. When I try to create a huginn user with the db:seed command, I get the output below. This is on an Ubuntu server on AWS. I've sucessfully installed in on an ubuntu server at home. This has been driving me round the bend. Any help would be appreciated.

```
ubuntu@ip-xyz-xyz-xyz.xyz:/home/huginn/huginn$ sudo -u huginn -H bundle exec rake db:seed RAILS_ENV=production SEED_USERNAME=admin SEED_PASSWORD=password --trace
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
rake aborted!
EOFError: end of file reached
/usr/local/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
/usr/local/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
/usr/local/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/usr/local/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/usr/local/lib/ruby/2.2.0/net/smtp.rb:945:in `recv_response'
/usr/local/lib/ruby/2.2.0/net/smtp.rb:555:in `block in do_start'
/usr/local/lib/ruby/2.2.0/net/smtp.rb:955:in `critical'
/usr/local/lib/ruby/2.2.0/net/smtp.rb:555:in `do_start'
/usr/local/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.2.5.2/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.2.5.2/lib/action_mailer/base.rb:541:in `deliver_mail'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.2.5.2/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/devise-3.5.4/lib/devise/models/authenticatable.rb:170:in `send_devise_notification'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/devise-3.5.4/lib/devise/models/confirmable.rb:116:in `send_confirmation_instructions'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/devise-3.5.4/lib/devise/models/confirmable.rb:172:in `send_on_create_confirmation_instructions'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:228:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:506:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:506:in `block in call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:506:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:506:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/callbacks.rb:306:in `_create_record'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/timestamp.rb:57:in `_create_record'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/persistence.rb:504:in `create_or_update'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/callbacks.rb:302:in `create_or_update'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/persistence.rb:142:in `save!'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/validations.rb:43:in `save!'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:291:in `block in save!'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:220:in `transaction'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:291:in `save!'
/home/huginn/huginn/db/seeds.rb:16:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:547:in `load_seed'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
Tasks: TOP => db:seed
```

**Comment by dsander** [comment]
Hi @stuartmunn,

it looks like there is an issue with sending the confirmation email for the admin user. Is it possible you set `REQUIRE_CONFIRMED_EMAIL` to `true` without configuring the SMTP settings in your `.env` file?

**Comment by stuartmunn** [comment]
Thank you @dsander! I'd have spent days more looking for that. I've now got the admin user seeded and logged in.
