### ISSUE TITLE
Huginn gets unreachable after some time

### ISSUE THREAD

**Issue by e-alfred** [cantino/huginn#1420]
Hello,

I am running Huginn on Ubuntu 14.04 basically using the installation manual here and using self compiled Ruby 2.3: https://github.com/cantino/huginn/blob/master/doc/manual/installation.md

After some time, the Huginn instance gets unreachable and throws a 404 in the webbrowser. After using rake to restart it  works again (for some time). I have only the agents set up during installation running (xkcd, weather) Here is the log so far:

/home/huginn/huginn# tail -f log/unicorn.log

```
192.168.1.40 - - [11/Apr/2016:20:31:14 +0200] "HEAD / HTTP/1.0" 200 - 3.0495
E, [2016-04-11T20:44:37.896429 #28333] ERROR -- : worker=0 PID:13507 timeout (182s > 180s), killing
E, [2016-04-11T20:44:44.943190 #28333] ERROR -- : reaped #<Process::Status: pid 13507 SIGKILL (signal 9)> worker=0
192.168.1.11 - - [11/Apr/2016:20:45:22 +0200] "GET /404 HTTP/1.0" 404 728 39.2947
I, [2016-04-11T20:47:02.348021 #32493]  INFO -- : worker=0 ready
D, [2016-04-11T20:48:25.255397 #28333] DEBUG -- : waiting 91.0s after suspend/hibernation
E, [2016-04-11T20:52:59.852528 #28333] ERROR -- : worker=0 PID:32493 timeout (185s > 180s), killing
E, [2016-04-11T20:53:05.388482 #28333] ERROR -- : reaped #<Process::Status: pid 32493 SIGKILL (signal 9)> worker=0
192.168.1.11 - - [11/Apr/2016:20:53:21 +0200] "GET /404 HTTP/1.0" 404 728 14.0995
I, [2016-04-11T20:55:05.611723 #1862]  INFO -- : worker=0 ready
```

production.log:

```
I, [2016-04-11T20:59:47.987923 #2748]  INFO -- : [0bc1d494-8eea-43d4-b878-401ba8479553] Started GET "/favicon.ico" for 127.0.0.1 at 2016-04-11 20:59:47 +0200
F, [2016-04-11T20:59:47.992365 #2748] FATAL -- : [0bc1d494-8eea-43d4-b878-401ba8479553] 
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'

```

tail -f log/dj7-1/current 

```
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
ERROR: there is already one or more instance(s) of the program running
```

tail -f log/dj6-1/current 

```
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:119:in `block in run_process'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/application.rb:264:in `start_proc'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/controller.rb:73:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:117:in `run_process'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:93:in `daemonize'
```

**Comment by dsander** [comment]
Hi @e-alfred,

is it possible the server is running out of RAM? The last log output is missing the first part of the exception the beginning of a backtrace will always look something like this: `NoMethodError (undefined method 'name' for nil:NilClass):`
It looks like you are starting a few delayed job worker, how does your Procfile look?

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
