### ISSUE TITLE
error "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by vivagonna** [cantino/huginn#1461]
Hi,

I got an error "We're sorry, but something went wrong.", after I changed "message" field in Options of a TriggerAgent like this:

> "message":"**{{title}}**{{hovertext|remove:\t}}{{\r\n}}{{url}}"} 

(I'm a newbie at liquid syntax, don't laugh...)
The Agent page won't open with the error showing up. I end up to set the "message" to a safe value manually in database then it works well again. I just wondering what on earth triggered that error. Could anyone help?

BR
Hsiang

**Comment by brianpetro** [comment]
Use `{{ line_break }}` see https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid

**Comment by brianpetro** [comment]
`{{remove:\t}}` is probably also breaking things.

**Comment by vivagonna** [comment]
Hi, @brianpetro 

Thanks for you advices. I think I need to drill the syntax before I mess it up again...

BR

**Comment by hunhejj** [comment]
I tried to push the current master to heroku. Now I get this error message, after logging into my huginn app. I haven't pulled/pushed for at least 6 months. Here's what `heroku logs ` returned:

> 2016-04-30T18:33:29.521221+00:00 app[web.1]: New threaded worker PID: 226
2016-04-30T18:33:29.868781+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:29.868789+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:29.880146+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:29.880154+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:30.428239+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:30.428247+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:30.434443+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:30.434450+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:30.967816+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:30.967825+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:30.975655+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:30.975644+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:32.490953+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:32.490989+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:32.497857+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-04-30T18:33:32.497848+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-04-30T18:33:34.876753+00:00 heroku[router]: at=info method=GET path="/diagram" host=magical-huginn.herokuapp.com request_id=cf2f5255-5772-414d-ba68-dd0f9bbd7e3b fwd="80.98.247.41" dyno=web.1 connect=0ms service=59ms status=500 bytes=951
2016-04-30T18:33:34.832149+00:00 app[web.1]: [cf2f5255-5772-414d-ba68-dd0f9bbd7e3b] Started GET "/diagram" for 80.98.247.41 at 2016-04-30 11:33:34 -0700
2016-04-30T18:33:34.834131+00:00 app[web.1]: [cf2f5255-5772-414d-ba68-dd0f9bbd7e3b] Processing by DiagramsController#show as HTML
2016-04-30T18:33:34.887141+00:00 app[web.1]: [cf2f5255-5772-414d-ba68-dd0f9bbd7e3b] Completed 500 Internal Server Error in 53ms (ActiveRecord: 1.2ms)
2016-04-30T18:33:34.889001+00:00 app[web.1]: [cf2f5255-5772-414d-ba68-dd0f9bbd7e3b] 
2016-04-30T18:33:34.889009+00:00 app[web.1]: NameError (undefined local variable or method 'deactivated_at' for #\<User:0x007f0aec4cc838\>
2016-04-30T18:33:34.889011+00:00 app[web.1]: Did you mean?  deactivate!):
2016-04-30T18:33:34.889011+00:00 app[web.1]:   app/models/user.rb:47:in 'active?'
2016-04-30T18:33:34.889012+00:00 app[web.1]:   app/models/user.rb:65:in 'active_for_authentication?'
2016-04-30T18:33:34.889013+00:00 app[web.1]:   config/initializers/silence_worker_status_logger.rb:5:in 'call_with_silence_worker_status'
2016-04-30T18:33:34.889014+00:00 app[web.1]: 
2016-04-30T18:33:34.889015+00:00 app[web.1]: 
2016-04-30T18:33:35.822226+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in 'prepare': PG::UndefinedColumn: ERROR:  column agents.deactivated does not exist (ActiveRecord::StatementInvalid)
2016-04-30T18:33:35.822235+00:00 app[web.1]: LINE 1: ...terStreamAgent') AND "agents"."disabled" = $1 AND "agents"."...
2016-04-30T18:33:35.822236+00:00 app[web.1]:                                                              ^
2016-04-30T18:33:35.822238+00:00 app[web.1]: : SELECT "agents".* FROM "agents" WHERE "agents"."type" IN ('Agents::TwitterStreamAgent') AND "agents"."disabled" = $1 AND "agents"."deactivated" = 'f'
2016-04-30T18:33:35.822239+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in 'prepare_statement'
2016-04-30T18:33:35.822240+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in 'exec_cache'
2016-04-30T18:33:35.822243+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in 'execute_and_clear'
2016-04-30T18:33:35.822243+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in 'exec_query'
2016-04-30T18:33:35.822244+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:355:in 'select'
2016-04-30T18:33:35.822245+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in 'select_all'
2016-04-30T18:33:35.822246+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in 'select_all'
2016-04-30T18:33:35.822247+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/querying.rb:39:in 'find_by_sql'
2016-04-30T18:33:35.822248+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:639:in 'exec_queries'
2016-04-30T18:33:35.822248+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:515:in 'load'
2016-04-30T18:33:35.822249+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:243:in 'to_a'
2016-04-30T18:33:35.822281+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:132:in 'method_missing'
2016-04-30T18:33:35.822307+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:99:in 'method_missing'
2016-04-30T18:33:35.822308+00:00 app[web.1]: 	from /app/app/models/agents/twitter_stream_agent.rb:128:in 'setup_worker'
2016-04-30T18:33:35.822309+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:94:in 'block (2 levels) in load_workers'
2016-04-30T18:33:35.822312+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:62:in 'block in with_connection'
2016-04-30T18:33:35.822314+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in 'with_connection'
2016-04-30T18:33:35.822314+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:61:in 'with_connection'
2016-04-30T18:33:35.822316+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:93:in 'block in load_workers'
2016-04-30T18:33:35.822318+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:89:in 'each'
2016-04-30T18:33:35.822320+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:89:in 'load_workers'
2016-04-30T18:33:35.822322+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:69:in 'run_workers'
2016-04-30T18:33:35.822343+00:00 app[web.1]: 	from /app/lib/agent_runner.rb:39:in 'run'
2016-04-30T18:33:35.822344+00:00 app[web.1]: 	from bin/threaded.rb:13:in '\<top (required)\>'
2016-04-30T18:33:35.822345+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/runner.rb:60:in 'load'
2016-04-30T18:33:35.822345+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/runner.rb:60:in '\<top (required)\>'
2016-04-30T18:33:35.822347+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:123:in 'require'
2016-04-30T18:33:35.822348+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:123:in 'require_command!'
2016-04-30T18:33:35.822350+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:90:in 'runner'
2016-04-30T18:33:35.822371+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in '\<top (required)\>'
2016-04-30T18:33:35.822352+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in 'run_command!'
2016-04-30T18:33:35.822372+00:00 app[web.1]: 	from bin/rails:8:in 'require'
2016-04-30T18:33:35.822373+00:00 app[web.1]: 	from bin/rails:8:in '\<main\>'
2016-04-30T18:33:35.864969+00:00 app[web.1]: E, [2016-04-30T11:33:35.864877 #3] ERROR -- : reaped #\<Process::Status: pid 226 exit 1\> worker=unknown

Any ideas?

**Comment by cantino** [comment]
Maybe your current directory doesn't have a .git directory in it?  Is it a normal git repo?

**Comment by hunhejj** [comment]
I mean it was working _before_ (or if I did a `heroku rollback`), so I guess everything should be set up correctly on the remote repo.

**Comment by hunhejj** [comment]
And I do see the Huginn login page, I get the error message only afterwards.

**Comment by dsander** [comment]
Hi @hunhejj, you need to migrate the database after [updating Huginn on heroku](https://github.com/cantino/huginn/blob/master/doc/heroku/update.md): `heroku run rake db:migrate`

**Comment by hunhejj** [comment]
Thanks @dsander, this made the trick! I wasn't aware of that update page you are maintaining.
