### ISSUE TITLE
Looking to hire someone to deploy and configure huginn

### ISSUE THREAD

**Issue by daltonswayze** [cantino/huginn#1474]
Need someone to deploy huginn on a VPS, configure some alerts, and basic training.

**Comment by brianpetro** [comment]
Feel free to send me an email brian@angularjobs.com with what you are interested in accomplishing.

I manage a pretty complex huginn deployment and have taught a couple people the basics.

![huginn-5-3-16](https://cloud.githubusercontent.com/assets/1886014/14985569/1060fbf2-1116-11e6-90d3-a7d1f0d23d3c.png)

**Comment by cantino** [comment]
Holy crap @brianpetro, you're pushing Huginn so far beyond how I use it :wink:

**Comment by brianpetro** [comment]
@cantino awesome to hear!

It's not quite ready for a public writeup yet, however

if you or anyone else in the community is interested

I'd love to talk more about what I'm working on in private.

**Comment by TildeWill** [comment]
@daltonswayze if you don't mind your Huginn living in the public cloud, there is https://huginn.omniscope.io/ which only solves half of your problem.

**Comment by signallhill** [comment]
@brianpetro How is your huginn diagram showing with so much agents. Mine does not?

**Comment by brianpetro** [comment]
The only issue I can think of is having too many events in the DB so the
page request times out before the SQL requests are complete. To remedy
this, I set most agents to expire events after one day.

You may be able to set the timeout on your server to a higher number. More
RAM could also help.

**Comment by dsander** [comment]
@signallhill Are you using graphviz to render the diagram? Try installing it on your server and setting `USE_GRAPHVIZ_DOT=dot` in your `.env`

**Comment by signallhill** [comment]
@dsander will sudo apt-get install graphviz do to install it?

**Comment by dsander** [comment]
I believe so, yes.

**Comment by virtadpt** [comment]
It will.

By the way, you'l want to put the full path to dot (/usr/bin/dot) or it won't work the way you expect.

**Comment by signallhill** [comment]
@dsander and @virtadpt  - It worked, thanks

**Comment by signallhill** [comment]
@brianpetro May I know what cloud service, processor and OS you are using for your huginn setup.

**Comment by brianpetro** [comment]
Heroku hobby dynos. https://devcenter.heroku.com/articles/dyno-types
ᐧ

On Fri, May 13, 2016 at 11:25 AM, signallhill <notifications@github.com>
wrote:

> @brianpetro <https://github.com/brianpetro> May I know what cloud
> service, processor and OS you are using for your huginn setup.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cantino/huginn/issues/1474#issuecomment-219075978>
>



-- 
Brian Petro

**Comment by signallhill** [comment]
@brianpetro Is Huginn able to handle all events and processing that with 512? How often do the Agents run in the above scenario?

**Comment by brianpetro** [comment]
I generate more than 100k events using 4 resque workers on 2 heroku dynos.
Something runs almost every minute but I rarely have a list of queued
events for more than a few seconds.

**Comment by signallhill** [comment]
@brianpetro thats amazing,
1.  "4 resque workers" is this standard huginn setup or how is this achieved.

**Comment by brianpetro** [comment]
Here are some notes https://github.com/cantino/huginn/wiki/Resque-Setup

**Comment by signallhill** [comment]
Does it only work with heroku?

**Comment by cantino** [comment]
@brianpetro send me a note if you want to chat `andrew [@] andrewcantino.com`!

**Comment by signallhill** [comment]
@brianpetro After updating according to instruction for resque doing init script gives this error. 

LoadError: cannot load such file -- resque-web
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/huginn/huginn/config/application.rb:7:in `<top (required)>'
/home/huginn/huginn/Rakefile:5:in `require'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'

**Comment by brianpetro** [comment]
@signallhill try removing `if Rails.env.production?` from the first two
lines of the resque.rake file.

**Comment by signallhill** [comment]
@brianpetro Still getting the same thing. I am using AWS t2.micro (1 vCPU, 1 GB ram) with ubuntu. Couple of questions

1. On Procfile is this the web? - web: bundle exec unicorn -p $PORT -c config/unicorn.rb
2. Should resque.rake be in lib or lib/tasks? I am asking because all other rake files are there.

**Comment by brianpetro** [comment]
1. This looks correct.
2. Yes,  you are correct.  I updated the wiki.

**Comment by jemmasta** [comment]
Wow @brianpetro, speechless. :)

**Comment by signallhill** [comment]
@brianpetro Still getting the same error. Am I doing this correct?

1. SSH to the server.
2. production:check then production:stop
3. Update files according to your instructions
4. production:export

Thanks.

**Comment by brianpetro** [comment]
@signallhill I'm using heroku. My workflow doesn't look like that so I
can't help you :(
