### ISSUE TITLE
Error when fetching url: U+00E2 from UTF-8 to US-ASCII

### ISSUE THREAD

**Issue by mogorman** [cantino/huginn#1514]
probably not a real bug but not sure how to fix. this is the error i get from the threaded worker.  I am using postgresql.  otherwise this is the same config i had working with mysql previously.  So not sure what is wrong.

Error when fetching url: U+00E2 from UTF-8 to US-ASCII
/home/mog/work_huginn/huginn/app/models/agent_log.rb:18:in `write'
/home/mog/work_huginn/huginn/app/models/agent_log.rb:18:in `puts'
/home/mog/work_huginn/huginn/app/models/agent_log.rb:18:in `puts'
/home/mog/work_huginn/huginn/app/models/agent_log.rb:18:in `log_for_agent'
/home/mog/work_huginn/huginn/app/models/agent.rb:227:in `log'
/home/mog/work_huginn/huginn/app/concerns/dry_runnable.rb:74:in `log'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:516:in `block in extract_xml'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:457:in `block in extract_each'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:456:in `each'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:456:in `each_with_object'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:456:in `extract_each'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:486:in `extract_xml'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:328:in `handle_data'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:304:in `block in check_url'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:302:in `check_url'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:287:in `block in check_urls'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:286:in `each'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:286:in `check_urls'
/home/mog/work_huginn/huginn/app/models/agents/website_agent.rb:280:in `check'
/home/mog/work_huginn/huginn/app/concerns/sortable_events.rb:57:in `check'
/home/mog/work_huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:32:in `block in perform_now'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `block in tag_logger'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `tag_logger'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:31:in `perform_now'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:21:in `execute'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:84:in `block in invoke_job'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:81:in `invoke_job'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/nix/store/93n0p85c3nki9wd3743q611ky18d2blq-ruby-2.3.0-p0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/nix/store/93n0p85c3nki9wd3743q611ky18d2blq-ruby-2.3.0-p0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block in run'
/nix/store/93n0p85c3nki9wd3743q611ky18d2blq-ruby-2.3.0-p0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:229:in `run'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:306:in `block in reserve_and_run_one_job'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:306:in `reserve_and_run_one_job'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:213:in `block in work_off'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:212:in `times'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:212:in `work_off'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/nix/store/93n0p85c3nki9wd3743q611ky18d2blq-ruby-2.3.0-p0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute'
/home/mog/work_huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/ho

**Comment by mogorman** [comment]
i am able to produce and store other events. it seems to just be this unicode bug

**Comment by poonjh** [comment]
@mogorman  how do you fix the issue?   Thanks


I get the following error:


                      U+6613 from UTF-8 to US-ASCII
/home/huginn/huginn/app/models/agent_log.rb:16:in `write'
/home/huginn/huginn/app/models/agent_log.rb:16:in `puts'
/home/huginn/huginn/app/models/agent_log.rb:16:in `puts'
/home/huginn/huginn/app/models/agent_log.rb:16:in `log_for_agent'
/home/huginn/huginn/app/models/agent.rb:225:in `log'
/home/huginn/huginn/app/concerns/dry_runnable.rb:74:in `log'
/home/huginn/huginn/app/models/agents/de_duplication_agent.rb:61:in `handle'
/home/huginn/huginn/app/models/agents/de_duplication_agent.rb:50:in `block in receive'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/home/huginn/huginn/app/models/agents/de_duplication_agent.rb:49:in `receive'
/home/huginn/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
