### ISSUE TITLE
Error in WebsiteAgent using {{ _response_.headers.Content-Type }}

### ISSUE THREAD

**Issue by bleakstew** [cantino/huginn#1578]
Hi,
I am trying to fetch some headers returned from a web page using the {{ _response_.headers }} variable in my results. If I create an agent that uses {{ _response_.status }}, I get a successful result. However any reference to the {{ _response_.headers }} variables seems to fail. What am I dong wrong?

Here are my examples:

```
{
  "expected_update_period_in_days": "2",
  "url": "https://github.com/cantino/huginn",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "status": {
      "value": "{{ _response_.status }}",
      "css": "title"
    }
  }
}
```

Returns

```
[
  {
    "status": "200"
  }
]
```

But the following:

```
{
  "expected_update_period_in_days": "2",
  "url": "https://github.com/cantino/huginn",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "content-type": {
      "value": "{{ _response_.headers.Content-Type }}",
      "css": "title"
    }
  }
}
```

Returns the following error (as does any header like Date, Set-Cookie, or Content-Length):

```
Error log:

[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://github.com/cantino/huginn
[00:00:00] ERROR -- : Error when fetching url: Invalid expression: text/html; charset=utf-8
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:165:in `evaluate'
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:165:in `block in xpath'
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:156:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb:156:in `xpath'
/app/app/models/agents/website_agent.rb:498:in `block (2 levels) in extract_xml'
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
/app/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
/app/app/models/agents/website_agent.rb:497:in `map'
/app/app/models/agents/website_agent.rb:497:in `block in extract_xml'
/app/app/models/agents/website_agent.rb:457:in `block in extract_each'
/app/app/models/agents/website_agent.rb:456:in `each'
/app/app/models/agents/website_agent.rb:456:in `each_with_object'
/app/app/models/agents/website_agent.rb:456:in `extract_each'
/app/app/models/agents/website_agent.rb:486:in `extract_xml'
/app/app/models/agents/website_agent.rb:328:in `handle_data'
/app/app/models/agents/website_agent.rb:304:in `block in check_url'
/app/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
/app/app/models/agents/website_agent.rb:302:in `check_url'
/app/app/models/agents/website_agent.rb:287:in `block in check_urls'
/app/app/models/agents/website_agent.rb:286:in `each'
/app/app/models/agents/website_agent.rb:286:in `check_urls'
/app/app/models/agents/website_agent.rb:280:in `check'
/app/app/concerns/sortable_events.rb:57:in `check'
/app/app/concerns/dry_runnable.rb:31:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:38:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:198:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:137:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:30:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:196:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:237:in `block in action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:815:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/flash.rb:260:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/query_cache.rb:36:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:38:in `call_app'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `call'
/app/config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/static.rb:116:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
[00:00:00] INFO -- : Dry Run finished

```

**Comment by cantino** [comment]
Interesting, it looks like Liquid is trying to evaluate the result.

Does `{{ "" | append: _response_.headers.Content-Type }}` work?

/cc @knu

**Comment by cantino** [comment]
Odd.  @knu might have an idea what's going on.

**Comment by cantino** [comment]
Did you ever figure this out @bleakstew?

**Comment by bleakstew** [comment]
@cantino No. Sadly I don't have the expertise to troubleshoot the website agent code, so I just abandoned the use case I was working on.

**Comment by dsander** [comment]
Not sure if that was possible before, but now with the new template option you can do this:
```json
{
  "expected_update_period_in_days": "2",
  "url": "https://github.com/cantino/huginn",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": "title",
      "value": "./text()"
    }
  },
  "template": {
    "content-type": "{{ _response_.headers['Content-Type'] }}"
  }
}
```

**Comment by bleakstew** [comment]
@dsander Yes, using the template option does work. Now that I see that, I'm wondering if the use of the _response_ object through Liquid interpolation is only intended to be used in the template option. If so, I think the on-screen documentation of the Website agent not entirely clear on that point.

**Comment by cantino** [comment]
I think the response object was written longer ago, but does make most sense in the template. How would you suggest we update the docs?

**Comment by bleakstew** [comment]
@cantino My suggestion would be to replace the following line under the Liquid Templating heading.

Old:
"In Liquid templating, the following variables are available:"

New:
"The following variables are available for use within the `template` option, and will be Liquid interpolated:"

**Comment by knu** [comment]
Sorry for my absence.  To answer the original question, the `value` is expected to be an XPath expression, so an HTTP status code will be a valid expression because it is a number, but a value of the Content-Type header (`text/html; charset=utf-8`) won't make sense as XPath expression and that's what the error message says.

While using the `template` is the best solution, you could have said `{{ _response_.headers.Content-Type | to_xpath }}` so the resulted value would become an XPath string literal.

**Comment by bleakstew** [comment]
That explanation makes perfect sense. So it also looks like I can create a valid xpath expression just by wrapping the variable with single quotes like this `'{{ _response_.headers.Content-Type }}'`.

**Comment by knu** [comment]
Yes, you got it right.  The `to_xpath` filter handles quotes (even with `'` and `"` mixed) correctly, but in most cases wrapping a value with single quotes will do.

**Comment by cantino** [comment]
I just added this example to the `to_xpath` section on [the wiki](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid), thanks!

**Comment by cantino** [comment]
Okay to close this issue?
