### ISSUE TITLE
Email not sent

### ISSUE THREAD

**Issue by johndevs** [cantino/huginn#1585]
I'm getting an exception right after the email server has responded with OK. 

Here is the log:
```
Exception during check. * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot (Ubuntu) ready.
: /usr/lib/ruby/2.2.0/net/smtp.rb:964:in `check_response'
/usr/lib/ruby/2.2.0/net/smtp.rb:555:in `do_start'
/usr/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
/app/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/app/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/app/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/app/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.2.5.2/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.2.5.2/lib/action_mailer/base.rb:541:in `deliver_mail'
/app/vendor/bundle/ruby/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/app/vendor/bundle/ruby/2.2.0/gems/actionmailer-4.2.5.2/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/app/app/models/agents/email_digest_agent.rb:61:in `block in check'
/app/app/models/agents/email_digest_agent.rb:52:in `each'
/app/app/models/agents/email_digest_agent.rb:52:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:32:in `block in perform_now'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/app/vendor/bundle/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:23:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `block in tag_logger'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `tag_logger'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:31:in `perform_now'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:21:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:100:in `block in invoke_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:97:in `invoke_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block (2 levels) in run'
/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/usr/lib/ruby/2.2.0/timeout.rb:98:in `call'
/usr/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block in run'
/usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:223:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:207:in `block in work_off'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `times'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `work_off'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:169:in `block (4 levels) in start'
/usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:168:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:167:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.2.0
```

**Comment by y0zer** [comment]
I got the same error........ have you found the solution for this yet?

**Comment by cantino** [comment]
It looks like it's an IMAP connection instead of SMTP?
