### ISSUE TITLE
WebsiteAgent: Error when fetching url: unexpected '$' after '#<Nokogiri::CSS::Node:0x000000037331f8>'

### ISSUE THREAD

**Issue by zaubererty** [cantino/huginn#1600]
I'm not able to fetch any https url, I always get this wired $ issue.
I Run the latest docker image in single process mode

When I try a url with ':443' attached I'll get another fail result.

```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.clubcorner.ch/users/sign_in",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "authenticity_token": {
      "css": "//input[contains(@name, 'authenticity_token')",
      "value": "@value"
    },
    "utf8": {
      "css": "//input[contains(@name, 'utf8')",
      "value": "@value"
    }
  }
}
```

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://www.clubcorner.ch/users/sign_in
[00:00:00] ERROR -- : Error when fetching url: unexpected '$' after '#<Nokogiri::CSS::Node:0x000000037331f8>'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/css/parser_extras.rb:87:in `on_error'
/usr/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
/usr/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/css/parser_extras.rb:62:in `parse'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/css/parser_extras.rb:79:in `xpath_for'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/css.rb:23:in `xpath_for'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/searchable.rb:198:in `block in xpath_query_from_css_rule'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/searchable.rb:197:in `map'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/searchable.rb:197:in `xpath_query_from_css_rule'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/searchable.rb:192:in `block in css_internal'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/searchable.rb:192:in `map'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/searchable.rb:192:in `css_internal'
/app/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/searchable.rb:107:in `css'
/app/app/models/agents/website_agent.rb:489:in `block in extract_xml'
/app/app/models/agents/website_agent.rb:457:in `call'
/app/app/models/agents/website_agent.rb:457:in `block in extract_each'
/app/app/models/agents/website_agent.rb:456:in `each'
/app/app/models/agents/website_agent.rb:456:in `each_with_object'
/app/app/models/agents/website_agent.rb:456:in `extract_each'
/app/app/models/agents/website_agent.rb:486:in `extract_xml'
/app/app/models/agents/website_agent.rb:328:in `handle_data'
/app/app/models/agents/website_agent.rb:304:in `block in check_url'
/app/vendor/bundle/ruby/2.2.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
/app/app/models/agents/website_agent.rb:302:in `check_url'
/app/app/models/agents/website_agent.rb:287:in `block in check_urls'
/app/app/models/agents/website_agent.rb:286:in `each'
/app/app/models/agents/website_agent.rb:286:in `check_urls'
/app/app/models/agents/website_agent.rb:280:in `check'
/app/app/concerns/sortable_events.rb:57:in `check'
/app/app/concerns/dry_runnable.rb:31:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:39:in `create'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:198:in `process_action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:137:in `process'
/app/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:30:in `process'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:196:in `dispatch'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:237:in `block in action'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `serve'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:815:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/flash.rb:260:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/query_cache.rb:36:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:38:in `call_app'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `call'
/app/config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/static.rb:116:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
/app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
[00:00:00] INFO -- : Dry Run finished
```

**Comment by zaubererty** [comment]
found it, I missed to close the contains condition bracket
