### ISSUE TITLE
Issue with using wunderground for WeatherAgent?

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1622]
Getting errors when using wundeground for WeatherAgent, but no errors when using Forecastio. 

Forecastio set up as such, and works without issue:

```
{
  "service": "forecastio",
  "which_day": "0",
  "api_key": "apikeygoeshere",
  "location": "40.7354,-73.8783"
}
```

wunderground set up as such, and causes error:
```
{
  "service": "wunderground",
  "which_day": "0",
  "api_key": "apikeygoeshere",
  "location": "zmw:11373.1.99999"
}
```

i have also tried this alternate location per the instructions -- same error:

```
{
  "service": "wunderground",
  "which_day": "0",
  "api_key": "apikeygoeshere",
  "location": "US/NY/elmhurst"
}
```

the error backtrace is as follows: 
```
undefined method `[]' for nil:NilClass
/app/app/models/agents/weather_agent.rb:103:in `wunderground'
/app/app/models/agents/weather_agent.rb:116:in `model'
/app/app/models/agents/weather_agent.rb:77:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:32:in `block in perform_now'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/app/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `block in tag_logger'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `tag_logger'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:31:in `perform_now'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:21:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:100:in `block in invoke_job'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:97:in `invoke_job'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block (2 levels) in run'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block in run'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:223:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:207:in `block in work_off'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `times'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `work_off'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:169:in `block (4 levels) in start'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:168:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:167:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `loop'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `block in start'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:165:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'
```

**Comment by dsander** [comment]
Wunderground seems to have changed the way their site works, try using `zmw:11373.1.99999`as the location. I extracted the location from the source code of the website, we clearly need to improve the error message and the agent description.
The website source when visiting `https://www.wunderground.com/us/NY/elmhurst` includes `<i class="fi-star favorite-star " data-zmw="11373.1.99999"></i>` in the source which is the correct location.

**Comment by wasafiri** [comment]
That was the first thing i tried:

```
"location": "zmw:11373.1.99999"
```

Still results in the error.

**Comment by dsander** [comment]
```{
  "location": "zmw:11373.1.99999",
  "api_key": "key"
}```

works for me, maybe `whichday` is causing issues?

**Comment by wasafiri** [comment]
This is causing errors for me still:

```
{
  "service": "wunderground",
  "api_key": "b6b2324b92ddc806",
  "location": "zmw:11373.1.99999"
}
```

**Comment by dsander** [comment]
Odd, are you sure the API key is correct?

**Comment by wasafiri** [comment]
PEBKAC. Was using referral key instead of api-key.

**Comment by K1773R** [comment]
i've just been hit with this too, nasty...
