### ISSUE TITLE
Unable to run after upgrading OS

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#1665]
I upgraded from Ubuntu 15.1 to 16.0.4.1. Everything went smoothly during the upgrade, except now when I run ` sudo bundle exec rake production:check --trace` I get the following:

```
rake aborted!
LoadError: libmysqlclient.so.18: cannot open shared object file: No such file or directory - /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.20/lib/mysql2/mysql2.so
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.20/lib/mysql2.rb:31:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/huginn/huginn/config/application.rb:7:in `<top (required)>'
/home/huginn/huginn/Rakefile:5:in `require'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:686:in `raw_load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:96:in `block in load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:95:in `load_rakefile'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:79:in `block in run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
```

Navigating to `/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.20/lib/mysql2/` shows the file being there.

Any ideas on what could be wrong and how to fix it?

**Comment by dsander** [comment]
I suspect the mysql client libraries where updated and the gems c extension is still linked to the old version try forcing a reinstallation of the gems:

```
sudo -u huginn -H bundle install --force --deployment --without development test
```

**Comment by irfancharania** [comment]
That did the trick! Thanks Dominik!

Along the way, I had to update bundler 
`sudo gem install bundler`

Install json 1.8.3 separately
`sudo gem install json -v1.8.3`
`sudo bundle package`

and then re-run the command
