### ISSUE TITLE
Database connection timeouts on threaded.rb after a little while

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#1707]
@dsander, you might have suggestions on this.

I just switched my server from MySQL to PostgreSQL (which was an interesting exercise in editing the .sql dump from MySQL and fighting with upstart) and my Twitter agents have stopped working.  I'm seeing log entries like this:

```
(2016-09-24 12:18:31 -0700) Twitter News Event Source received: Bizarre NASA probe
Queuing schedule for every_2m
Queuing event propagation
Queuing schedule for every_1m
(2016-09-24 12:18:37 -0700) Twitter News Event Source received: NASA готовит сенс
 --> Twitter error: ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
	/home/huginn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	/home/huginn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	/home/huginn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
	/home/huginn/app/releases/20160922014509/lib/agent_runner.rb:61:in `with_connection'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:238:in `block (2 levels) in handle_status'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:236:in `each'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:236:in `block in handle_status'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:234:in `each'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:234:in `handle_status'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:169:in `block (2 levels) in run'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:196:in `block in stream!'
	/home/huginn/app/shared/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:296:in `parse_stream_line'
	/home/huginn/app/shared/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:227:in `block in receive_stream_data'
	/home/huginn/app/shared/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:226:in `each'
	/home/huginn/app/shared/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:226:in `receive_stream_data'
	/home/huginn/app/shared/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `call'
	/home/huginn/app/shared/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `<<'
	/home/huginn/app/shared/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `receive_data'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	/home/huginn/app/releases/20160922014509/app/models/agents/twitter_stream_agent.rb:164:in `run'
	/home/huginn/app/releases/20160922014509/app/concerns/long_runnable.rb:71:in `block in run!' at 2016-09-24 12:18:42 -0700 <--
 --> Sleeping for 15 seconds
--> Restarting Agents::TwitterStreamAgent-9-92d3a8e579f824b82184a3d62d32636219f2ecab at 2016-09-24 12:18:57 -0700 <--
Restarting Agents::TwitterStreamAgent-9-92d3a8e579f824b82184a3d62d32636219f2ecab
(2016-09-24 12:18:59 -0700) Twitter News Event Source received: @drewscanlon cortana start xbox race
 --> Twitter error: ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
	/home/huginn/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	/home/huginn/app/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
```

then after a bit

```
Restarting Agents::TwitterStreamAgent-9-92d3a8e579f824b82184a3d62d32636219f2ecab
 --> Twitter error: invalid status code: 420. at 2016-09-24 12:19:39 -0700 <--
 --> Sleeping for 15 seconds
--> Restarting Agents::TwitterStreamAgent-9-92d3a8e579f824b82184a3d62d32636219f2ecab at 2016-09-24 12:19:54 -0700 <--
Restarting Agents::TwitterStreamAgent-9-92d3a8e579f824b82184a3d62d32636219f2ecab
 --> Twitter error: invalid status code: 420. at 2016-09-24 12:19:55 -0700 <--
 --> Sleeping for 15 seconds
--> Restarting Agents::TwitterStreamAgent-9-92d3a8e579f824b82184a3d62d32636219f2ecab at 2016-09-24 12:20:10 -0700 <--
```

which I think is Twitter rate limiting the reconnects.

They start about 5-10 minutes after starting up the instance.  I pushed `DATABASE_POOL` up to 30 and it's still happening. Ideas on how I could debug?

(I have 3 TwitterStreamAgents and 2 TwitterUserAgents)

**Comment by dsander** [comment]
That's odd, I have not seen connection related errors for a long time, how is `max_connections` in `postgresql.conf` configured?

The amount of Agents should not matter, the `TwitterUserAgents` are ran by DJ and the `TwitterStreamAgent` combines multiple Agents into one connection to twitter and process the results sequentially, which should only acquire one connection at a time. 

I would start by checking the amount of open connection in postgres (`SELECT count(*) FROM pg_stat_activity;`).

**Comment by cantino** [comment]
Thanks, that was very helpful and helped me to figure out that I'm a moron and overwrote the database.yml with one that has a pool of 6. :face_palm:

**Comment by dsander** [comment]
Glad you figured it out, I was a bit worried we still had a threading issue 😄
