### ISSUE TITLE
Error when fetching url: source sequence is illegal/malformed utf-8" error.

### ISSUE THREAD

**Issue by jb0** [cantino/huginn#1742]
Hi, I'm having an issue with a Website Agent. It fails with a 
"Error when fetching url: source sequence is illegal/malformed utf-8" error.
The website does have some invalid tags in there, specifically the ending 
pre tag is missing ">".  See error bellow.

Is the bad HTML the issue? Any suggestions or workarounds?

I'm using the Docker container with posgres if that makes a difference.

Agent:

```
{
  "expected_update_period_in_days": "7",
  "url": "http://somafm.com/charts/bagel/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body_text": {
      "css": "#content",
      "value": ".//text()"
    }
  }
}
```

Error of Dry Run:

 ```
Def Pacts   (1070)\n\n\nTop Track Adds BY SPINS\n1. Port Juvee - Bleached Out Soda Pop (4)\n2. Conor Oberst - a Little Uncanny (4)\n3. Phantogram - You Don't Get Me High Anymore (4)\n4. Death Cab for Cutie - Million Dollar Loan (4)\n5. Conor Oberst - Tachycardia (4)\n6. Port Juvee - Mania (3)\n7. Black Marble - Frisk (3)\n8. Conor Oberst - Next of Kin (3)\n9. The Specials - a Message to You, Rudy (2)\n10. David Bowie - tvc15 (1)\n\n\nTop Album Adds\n1. David Bowie - Sound+Vision II (1)\n(10 tracks added from 1 albums)\n\n(This data is generated automatically from our logs, and has not been reviewed for accuracy by our staff.)\nPrevious Week Chart\n"]
[00:00:00] ERROR -- : Error when fetching url: source sequence is illegal/malformed utf-8
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/object/json.rb:34:in `to_json'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/object/json.rb:34:in `to_json'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/json/encoding.rb:55:in `to_json'
/usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
```

**Comment by knu** [comment]
Encoding detection seems to have failed.  As a workaround, try adding `"force_encoding": "iso-8859-1",` to the options.

**Comment by jb0** [comment]
Works great with that option added. Thank you!
