### ISSUE TITLE
RSS Agent Parsing error

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#1753]
I'm trying to parse the following feed:
http://www.timescolonist.com/cmlink/times-colonist-news-valid-rss-1.1995927

I've updated to the latest commit (950975d7a8f3d75490468645f9c05b61cf9e7204) and I'm getting this error:

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] ERROR -- : Failed to fetch http://www.timescolonist.com/cmlink/times-colonist-news-valid-rss-1.1995927 with message 'undefined method `display_name' for nil:NilClass
Did you mean?  display': ["/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/elements/address.rb:208:in `get_display_name'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/elements/address.rb:85:in `display_name'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/elements/address.rb:217:in `get_name'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/elements/address.rb:136:in `name'", "/home/huginn/huginn/lib/feedjira_extension.rb:48:in `content='", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/sax-machine-1.3.2/lib/sax-machine/handlers/sax_abstract_handler.rb:98:in `block in _end_element'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/sax-machine-1.3.2/lib/sax-machine/handlers/sax_abstract_handler.rb:98:in `each'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/sax-machine-1.3.2/lib/sax-machine/handlers/sax_abstract_handler.rb:98:in `_end_element'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/sax/document.rb:127:in `end_element_namespace'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/sax/parser.rb:112:in `parse_with'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/sax/parser.rb:112:in `parse_memory'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/sax/parser.rb:84:in `parse'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/sax-machine-1.3.2/lib/sax-machine/handlers/sax_nokogiri_handler.rb:10:in `sax_parse'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/sax-machine-1.3.2/lib/sax-machine/sax_document.rb:11:in `parse'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/sax-machine-1.3.2/lib/sax-machine/sax_document.rb:39:in `parse'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/feedjira-2.0.0/lib/feedjira/feed_utilities.rb:16:in `parse'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/feedjira-2.0.0/lib/feedjira/feed.rb:4:in `parse_with'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/feedjira-2.0.0/lib/feedjira/feed.rb:9:in `parse'", "/home/huginn/huginn/app/models/agents/rss_agent.rb:134:in `block in check_urls'", "/home/huginn/huginn/app/models/agents/rss_agent.rb:130:in `each'", "/home/huginn/huginn/app/models/agents/rss_agent.rb:130:in `check_urls'", "/home/huginn/huginn/app/models/agents/rss_agent.rb:121:in `check'", "/home/huginn/huginn/app/concerns/dry_runnable.rb:31:in `dry_run!'", "/home/huginn/huginn/app/controllers/agents/dry_runs_controller.rb:41:in `create'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:188:in `process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rescue.rb:20:in `process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:126:in `process'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionview-5.0.0.1/lib/action_view/rendering.rb:30:in `process'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:190:in `dispatch'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:262:in `dispatch'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `each'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:38:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:36:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'", "/home/huginn/huginn/config/initializers/silence_worker_status_logger.rb:3:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `public_send'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `method_missing'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/tempfile_reaper.rb:15:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/common_logger.rb:33:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/chunked.rb:54:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/content_length.rb:15:in `call'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'", "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `load'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `kernel_load'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:27:in `run'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:332:in `exec'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:20:in `dispatch'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:11:in `start'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/exe/bundle:34:in `block in <top (required)>'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'", "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.5/exe/bundle:26:in `<top (required)>'", "/usr/local/bin/bundle:23:in `load'", "/usr/local/bin/bundle:23:in `<main>'"]
[00:00:00] INFO -- : Fetched http://www.timescolonist.com/cmlink/times-colonist-news-valid-rss-1.1995927 and created 0 event(s).
[00:00:00] INFO -- : Dry Run finished

```

It used to work before, and I can't say for sure after which commit it stopped working as I only recently realized I haven't been getting any events.

Any ideas?

**Comment by knu** [comment]
Looks like a bug in my implementation.  Will look at it.

**Comment by knu** [comment]
I didn't expect calling Mail::Address#name would raise an error, and it may be a bug on the mail gem's side, but I'll add a workaround anyway.

**Comment by knu** [comment]
@irfancharania The above PR should fix the problem.  Could you try it?

**Comment by knu** [comment]
There's a PR for the issue with the mail gem: https://github.com/mikel/mail/pull/605

**Comment by irfancharania** [comment]
@knu Thanks! It works!

**Comment by knu** [comment]
Thanks for the confirmation.

**Comment by irfancharania** [comment]
OK, thanks for looking into it!
