### ISSUE TITLE
HTTP 500 error in webhook POST call

### ISSUE THREAD

**Issue by ali-sattari** [cantino/huginn#1819]
Hi,
I am trying to integrate Grafana webhook notification with Huginn's webhook to transfer alerts.

Here is a sample request made by Grafana (captured using nc):
```
POST /users/1/web_requests/24/yot4olOwk0 HTTP/1.0
X-Forwarded-For: xxx.xxx.xxx.xxx
Host: huginn.xxxx.ir
Connection: close
Content-Length: 312
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

{"evalMatches":[{"value":100,"metric":"High value","tags":null},{"value":200,"metric":"Higher Value","tags":null}],"imageUrl":"http://grafana.org/assets/img/blog/mixed_styles.png","ruleId":0,"ruleName":"Test notification","ruleUrl":"http://mon.xxxx.ir/","state":"alerting","title":"[Alerting] Test notification"}
``` 

And here is Huginn's error in stdout upon receiving above request:
```
foreman stdout | 21:35:44 web.1  | Error during failsafe response: undefined method `symbol' for nil:NilClass
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb:63:in `parse_formatted_parameters'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/request.rb:366:in `block in POST'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch_header'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/request.rb:365:in `POST'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/parameters.rb:35:in `parameters'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/mime_negotiation.rb:63:in `block in formats'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch_header'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/mime_negotiation.rb:61:in `formats'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/public_exceptions.rb:22:in `call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
21:35:44 web.1  |   /app/config/initializers/silence_worker_status_logger.rb:3:in `call'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
foreman stdout | 21:35:44 web.1  |   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
21:35:44 web.1  |   /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
foreman stdout | 21:35:44 web.1  |   /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
21:35:44 web.1  |   /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

And webhook agent's config in Huginn:
```
{
  "secret": "xxxxx",
  "expected_receive_period_in_days": "5",
  "verbs": "post,get,put",
  "payload_path": ".",
  "code": "200"
}
```

I double checked Huginn's generated webhook URL on both ends, and I am using Huginn's webhook in a different PHP script using curl for different data with success.

What's wrong with this POST request that results in 500 internal server error in Huginn?

**Comment by cantino** [comment]
Hey @ali-sattari, that looks like an error in Rack or Rails, which Huginn uses. I think it's this: https://github.com/rails/rails/issues/24827  Can you add a `Content-Type` to the request?

**Comment by ali-sattari** [comment]
@cantino I could replicate this using curl with and without 'Content-type' header, with value of 'text/json' it works perfectly.

I will pass this to Grafana team as the Content-type should be an essential header for web hook calls.

Thanks for your response.
