### ISSUE TITLE
RoutingError for assets and REST calls

### ISSUE THREAD

**Issue by tvierling** [cantino/huginn#1836]
Old version (was working): c1095330ea0aed32d171bb5f98bb1c75af659546
Current version: 65cea03062dfc4aa7d0ebdacf2edde5a78e75f82

Ruby 2.2.6 (PPA for Ubuntu 12.04), Bundler 1.7.4.

To isolate this problem, testing by running standalone-foreground with `bundle exec rails server -p 3000`.

`.env` contains `RAILS_ENV=production`. No other custom settings there besides token, a randomized invitation code, SMTP server info, and `EMAIL_FROM_ADDRESS`.

I've changed `config/initializers/silence_worker_status_logger.rb` to comment out the `:prepend` so I get stack traces below.

At first I was seeing this:
```
I, [2016-12-21T22:11:09.358284 #30551]  INFO -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] Started GET "/assets/application-2f3d02fc585c540fafb5b6cd72f4480f7f1b5d26ff8055f68a1c524c743d211b.js" for 127.0.0.1 at 2016-12-21 22:11:09 -0800
F, [2016-12-21T22:11:09.868157 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b]   
F, [2016-12-21T22:11:09.868277 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] ActionController::RoutingError (No route matches [GET] "/assets/application-2f3d02fc585c540fafb5b6cd72f4480f7f1b5d26ff8055f68a1c524c743d211b.js"):
F, [2016-12-21T22:11:09.868336 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b]   
F, [2016-12-21T22:11:09.868439 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
F, [2016-12-21T22:11:09.868490 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
F, [2016-12-21T22:11:09.868535 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
F, [2016-12-21T22:11:09.868579 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
F, [2016-12-21T22:11:09.868623 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
F, [2016-12-21T22:11:09.868667 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
F, [2016-12-21T22:11:09.868710 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
F, [2016-12-21T22:11:09.868753 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
F, [2016-12-21T22:11:09.868803 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
F, [2016-12-21T22:11:09.868848 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
F, [2016-12-21T22:11:09.868891 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
F, [2016-12-21T22:11:09.868934 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
F, [2016-12-21T22:11:09.868977 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
F, [2016-12-21T22:11:09.869020 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
F, [2016-12-21T22:11:09.869063 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
F, [2016-12-21T22:11:09.869119 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] /usr/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
F, [2016-12-21T22:11:09.869163 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] /usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
F, [2016-12-21T22:11:09.869202 #30551] FATAL -- : [be4fc623-8a16-40e1-a2d5-eefef4d42e7b] /usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

even though I did precompile the assets (and they exist in public/assets, readable by the rails server). To work around this temporarily, I have changed `config/environments/production.rb` to comment out `config.assets.compile = false`.

This allowed me to login, but much functionality still didn't work; I start to see additional failures, like this when trying to re-emit an event:
```
I, [2016-12-21T22:11:06.086593 #30551]  INFO -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] Started GET "/events/80454/reemit" for 127.0.0.1 at 2016-12-21 22:11:06 -0800
F, [2016-12-21T22:11:06.112285 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8]   
F, [2016-12-21T22:11:06.112453 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] ActionController::RoutingError (No route matches [GET] "/events/80454/reemit"):
F, [2016-12-21T22:11:06.112511 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8]   
F, [2016-12-21T22:11:06.112591 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_
exceptions.rb:53:in `call'
F, [2016-12-21T22:11:06.112657 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_e
xceptions.rb:31:in `call'
F, [2016-12-21T22:11:06.112777 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_ap
p'
F, [2016-12-21T22:11:06.112820 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block i
n call'
F, [2016-12-21T22:11:06.112864 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.
rb:70:in `block in tagged'
F, [2016-12-21T22:11:06.112930 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.
rb:26:in `tagged'
F, [2016-12-21T22:11:06.112978 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.
rb:70:in `tagged'
F, [2016-12-21T22:11:06.113032 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
F, [2016-12-21T22:11:06.113074 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/reques
t_id.rb:24:in `call'
F, [2016-12-21T22:11:06.113114 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
F, [2016-12-21T22:11:06.113155 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
F, [2016-12-21T22:11:06.113195 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/execut
or.rb:12:in `call'
F, [2016-12-21T22:11:06.113245 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
F, [2016-12-21T22:11:06.113288 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
F, [2016-12-21T22:11:06.113328 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
F, [2016-12-21T22:11:06.113367 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] /usr/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
F, [2016-12-21T22:11:06.113407 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] /usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
F, [2016-12-21T22:11:06.113446 #30551] FATAL -- : [d767b8ce-686e-4cd2-a7fc-c76e254737c8] /usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

So apparently something isn't routing requests correctly at all. I noticed the Rails 5 update in the changelog, as well as Rails 5 being built when I did the update process. This is my first suspect, but I'm not Rails-experienced enough to know where to look intuitively.

What additional config and debugging can I provide to help figure this out?

**Comment by dsander** [comment]
Hi @tvierling,

can you double check that `sudo -u huginn -H bundle exec rake assets:clean assets:precompile tmp:cache:clear RAILS_ENV=production` ran without errors? Please revert `config/environments/production.rb` back to the default before and restart Huginn afterwards.
The second error happened because the Javascript files are not loaded, so it's related to the assets not being precompiled.

**Comment by tvierling** [comment]
> even though I did precompile the assets (and they exist in public/assets, readable by the rails server).

Yes, I already did that as noted by the above. (And did it again just now with no change, reverting production.rb in the process.)

Without the special hack to production.rb, the UI looks as with #970, but the precompiled assets *are* there under public/. Rails simply isn't finding them for any reason I can deduce.

I even went as far as to `strace -e trace=open,access` the unicorn (and now plain standalone webrick-based) process, and the filesystem isn't being consulted for the assets at all; there are no attempted open calls on them.

**Comment by dsander** [comment]
Which CSS and JS file is requested in the HTML `head` and do the digests match a file in the public directory?

**Comment by cantino** [comment]
Hi @tvierling, is it okay if we close out this issue?

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!

**Comment by tvierling** [comment]
Thanks. This was intermittent so I eventually gave up and built the docker multi-process variant.
