### ISSUE TITLE
Web Agent Error

### ISSUE THREAD

**Issue by Voleking** [cantino/huginn#1901]
Hi, I created a Web Agent and It worked perfectly. However I got this error currently. The agent works fine on other [server](http://muginn.arukascloud.io). I wonder whether the site is blocking my domain?
```
[00:00:00] ERROR -- : Error when fetching url: Failed: #<Faraday::Response:0x007f73b82bfba0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="" @url=#<URI::HTTP http://www.biquege.com/yinianyongheng/> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Huginn - https://github.com/cantino/huginn", "Accept-Encoding"=>"gzip,deflate"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x007f73b82bfba0 ...> @response_headers={} @status=0>>
/app/app/models/agents/website_agent.rb:346:in `check_url'
/app/app/models/agents/website_agent.rb:333:in `block in check_urls'
/app/app/models/agents/website_agent.rb:332:in `each'
/app/app/models/agents/website_agent.rb:332:in `check_urls'
/app/app/models/agents/website_agent.rb:326:in `check'
/app/app/concerns/sortable_events.rb:75:in `check'
/app/app/concerns/dry_runnable.rb:31:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/abstract_controller/base.rb:188:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/abstract_controller/base.rb:126:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/actionview-5.0.1/lib/action_view/rendering.rb:30:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal.rb:190:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_controller/metal.rb:262:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/journey/router.rb:26:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:38:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/rack/logger.rb:36:in `call_app'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/rack/logger.rb:24:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/rack/logger.rb:24:in `call'
/app/config/initializers/silence_worker_status_logger.rb:3:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:522:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[00:00:00] INFO -- : Dry Run finished
```

**Comment by dsander** [comment]
Hi @Voleking,

I think status `0` means the site did not respond at all. Can you reach the url via a browser? For me the DNS resolution for `biquege.com` fails.

**Comment by Voleking** [comment]
@dsander Oh yes, it's the website problem. Sorry to bother you for such stupid question.

**Comment by Voleking** [comment]
@dsander Oh yes, it's the website problem. Sorry to bother you for such a stupid question.
You are one the most active developer I have ever seen.

**Comment by Voleking** [comment]
Hi, I changed to the right url and this agent worked fine in the last few weeks. However, I get this error again now. Even if the DNS resolution seems well on my VPS.
```
~$ dig m.biquge.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> m.biquge.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61776
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;m.biquge.com.			IN	A

;; ANSWER SECTION:
m.biquge.com.		299	IN	A	162.159.211.81
m.biquge.com.		299	IN	A	162.159.210.81

;; Query time: 6 msec
;; SERVER: 2001:4860:4860::8844#53(2001:4860:4860::8844)
;; WHEN: Wed Mar 01 18:36:53 CST 2017
;; MSG SIZE  rcvd: 73
```

**Comment by HiIcy** [comment]
oh,I also met the problem,but I could reach the url via a browser.and the url is `http://walkginkgo.com/`.
so ,How I should do ?

**Comment by dsander** [comment]
@HiIcy If the website is reachable from your Huginn instance you are probably getting a different error. Can you please open a new issue and attach the Agent's error log?

**Comment by HiIcy** [comment]
@dsander  Oh,I mean  that I can reach  `http://walkginkgo.com/` by browser.But  when I try to make a Web agent,even the most simple example wasn't success and the error log as your output!

**Comment by dsander** [comment]
@HiIcy You are getting `@status=0` in the error message as well? That means either the domain does not resolve or the website is not reachable from your Huginn instance, which could be caused by a network issue or a firewall on your system or the targets website.
