### ISSUE TITLE
Docker image does not start when using external PostgreSQL

### ISSUE THREAD

**Issue by ckir** [cantino/huginn#1921]
When I start the image using external MySql like

```
docker run --rm --name huginn \
    -p 3000:3000 \
    -e DATABASE_ADAPTER=mysql2 \
    -e DATABASE_HOST=db4free.net \
    -e DATABASE_PORT=3306 \
    -e DATABASE_NAME=d2i454kcn7i0kp \
    -e DATABASE_USERNAME=pofjnbukbwemck \
    -e DATABASE_PASSWORD=<don't give your password away>\
    cantino/huginn
```

works fine, but when I use external PostgreSQL like 

```
docker run --rm --name huginn \
    -p 3000:3000 \
    -e DATABASE_ADAPTER=postgresql \
    -e DATABASE_HOST=ec2-54-197-230-161.compute-1.amazonaws.com \
    -e DATABASE_PORT=5432 \
    -e DATABASE_NAME=d2i454kcn7i0kp \
    -e DATABASE_USERNAME=pofjnbukbwemck \
    -e DATABASE_PASSWORD=<don't give your password away> \
    -e DATABASE_ENCODING=utf8 \
    -e DATABASE_RECONNECT=true \
    -e DATABASE_POOL=5 \
    -e ON_HEROKU=true \
    cantino/huginn
```

It gives me

```
2017-03-05 09:36:53,194 CRIT Set uid to user 0
2017-03-05 09:36:53,194 WARN Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
2017-03-05 09:36:53,194 WARN Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
2017-03-05 09:36:53,228 INFO RPC interface 'supervisor' initialized
2017-03-05 09:36:53,228 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-03-05 09:36:53,228 INFO supervisord started with pid 1
2017-03-05 09:36:54,232 INFO spawned: 'stdout' with pid 193
2017-03-05 09:36:54,234 INFO spawned: 'bootstrap' with pid 194
2017-03-05 09:36:54,241 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-03-05 09:36:54,243 INFO exited: bootstrap (exit status 1; not expected)
2017-03-05 09:36:55,309 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=ec2-54-197-230-161.compute-1.amazonaws.com
bootstrap stdout | DATABASE_ADAPTER 'postgresql' is not supported internally. Please provide DATABASE_HOST.
```

Any ideas ?

**Comment by alias1** [comment]
I'd have to check, but is the adapter name just "postgres" rather than "postgresql"?

Get Outlook for iOS




On Sun, Mar 5, 2017 at 8:59 PM +1100, "Costas Kirgoussios" <notifications@github.com> wrote:












When I start the image using external MySql like
docker run --rm --name huginn \
    -p 3000:3000 \
    -e DATABASE_ADAPTER=mysql2 \
    -e DATABASE_HOST=db4free.net \
    -e DATABASE_PORT=3306 \
    -e DATABASE_NAME=d2i454kcn7i0kp \
    -e DATABASE_USERNAME=pofjnbukbwemck \
    -e DATABASE_PASSWORD=<don't give your password away>\
    cantino/huginn



works fine, but when I use external PostgreSQL like
docker run --rm --name huginn \
    -p 3000:3000 \
    -e DATABASE_ADAPTER=postgresql \
    -e DATABASE_HOST=ec2-54-197-230-161.compute-1.amazonaws.com \
    -e DATABASE_PORT=5432 \
    -e DATABASE_NAME=d2i454kcn7i0kp \
    -e DATABASE_USERNAME=pofjnbukbwemck \
    -e DATABASE_PASSWORD=<don't give your password away> \
    -e DATABASE_ENCODING=utf8 \
    -e DATABASE_RECONNECT=true \
    -e DATABASE_POOL=5 \
    -e ON_HEROKU=true \
    cantino/huginn



It gives me


2017-03-05 09:36:53,194 CRIT Set uid to user 0

2017-03-05 09:36:53,194 WARN Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing

2017-03-05 09:36:53,194 WARN Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing

2017-03-05 09:36:53,228 INFO RPC interface 'supervisor' initialized

2017-03-05 09:36:53,228 CRIT Server 'unix_http_server' running without any HTTP authentication checking

2017-03-05 09:36:53,228 INFO supervisord started with pid 1

2017-03-05 09:36:54,232 INFO spawned: 'stdout' with pid 193

2017-03-05 09:36:54,234 INFO spawned: 'bootstrap' with pid 194

2017-03-05 09:36:54,241 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2017-03-05 09:36:54,243 INFO exited: bootstrap (exit status 1; not expected)

2017-03-05 09:36:55,309 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

bootstrap stdout | DATABASE_HOST=ec2-54-197-230-161.compute-1.amazonaws.com

bootstrap stdout | DATABASE_ADAPTER 'postgresql' is not supported internally. Please provide DATABASE_HOST.


Any ideas ?

**Comment by dsander** [comment]
Hi @ckir,

you are right, this is a bug in the multi process image, for now your can work around it by using `POSTGRES_PORT_5432_TCP_ADDR` instead of `DATABASE_HOST`.

**Comment by ckir** [comment]
Hi @dsander,

I tried the workaround like

docker run --rm --name huginn \
    -p 3000:3000 \
    -e DATABASE_ADAPTER=postgresql \
    -e POSTGRES_PORT_5432_TCP_ADDR=ec2-54-197-230-161.compute-1.amazonaws.com \
    -e DATABASE_PORT=5432 \
    -e DATABASE_NAME=d2i454kcn7i0kp \
    -e DATABASE_USERNAME=pofjnbukbwemck \
    -e DATABASE_PASSWORD=<don't give your password away> \
    -e DATABASE_ENCODING=utf8 \
    -e DATABASE_RECONNECT=true \
    -e DATABASE_POOL=5 \
    -e ON_HEROKU=true \
    -e AGENT_LOG_LENGTH=20 \
    cantino/huginn

but it gives me
```
bootstrap stdout | DATABASE_HOST=ec2-54-197-230-161.compute-1.amazonaws.com
foreman stderr | FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"utf8", "reconnect"=>true, "database"=>"d2i454kcn7i0kp", "pool"=>5, "username"=>"pofjnbukbwemck", "password"=>"<don't give your password away>", "host"=>"ec2-54-197-230-161.compute-1.amazonaws.com", "port"=>5432, "socket"=>"/tmp/mysql.sock", "strict"=>false}
foreman stderr | rake aborted!
PG::ConnectionBad: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
```
Please note: It tries to connect to database  "postgres" not "d2i454kcn7i0kp"

**Comment by dsander** [comment]
It seems like rails is trying to create the database even if it still exists and your database user does not have the permission to do that. 

Can you try the image `huginnbuilder/huginn:pr-1922 ` and set the `DO_NOT_CREATE_DATABASE` environment variable to something?

**Comment by ckir** [comment]
Hi @dsander,

Image huginnbuilder/huginn:pr-1922 started like

docker run --rm --name huginn \
    -p 3000:3000 \
    -e DATABASE_ADAPTER=postgresql \
    -e POSTGRES_PORT_5432_TCP_ADDR=ec2-54-197-230-161.compute-1.amazonaws.com \
    -e DATABASE_PORT=5432 \
    -e DATABASE_NAME=d2i454kcn7i0kp \
    -e DATABASE_USERNAME=pofjnbukbwemck \
    -e DATABASE_PASSWORD=<don't give your password away>  \
    -e DATABASE_ENCODING=utf8 \
    -e DATABASE_RECONNECT=true \
    -e DATABASE_POOL=5 \
    -e ON_HEROKU=true \
    -e AGENT_LOG_LENGTH=20 \
    -e DO_NOT_CREATE_DATABASE=true \
    huginnbuilder/huginn:pr-1922

gives me

2017-03-06 22:29:47,952 CRIT Set uid to user 0
2017-03-06 22:29:47,952 WARN Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
2017-03-06 22:29:47,952 WARN Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
2017-03-06 22:29:48,080 INFO RPC interface 'supervisor' initialized
2017-03-06 22:29:48,080 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-03-06 22:29:48,080 INFO supervisord started with pid 1
2017-03-06 22:29:49,084 INFO spawned: 'stdout' with pid 143
2017-03-06 22:29:49,086 INFO spawned: 'bootstrap' with pid 144
2017-03-06 22:29:49,119 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-03-06 22:29:49,316 INFO spawned: 'foreman' with pid 146
2017-03-06 22:29:49,326 INFO success: foreman entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-03-06 22:29:49,336 INFO exited: bootstrap (exit status 0; expected)
2017-03-06 22:29:50,338 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=ec2-54-197-230-161.compute-1.amazonaws.com
foreman stderr | rake aborted!
NameError: uninitialized constant Rack::LiveReload
foreman stderr | /app/config/environments/development.rb:4:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/railtie.rb:209:in `instance_eval'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/railtie.rb:209:in `configure'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/railtie.rb:181:in `configure'
/app/config/environments/development.rb:3:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:599:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:599:in `block in <class:Engine>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:44:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/railtie.rb:193:in `public_send'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/railtie.rb:193:in `method_missing'
/app/config/environment.rb:5:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:328:in `require_environment!'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
2017-03-06 22:30:01,320 INFO exited: foreman (exit status 1; not expected)

and no tables created in the database

**Comment by dsander** [comment]
@ckir I honestly can't tell you why it makes a difference but it works for me without the `ON_HEROKU` environment variable.

**Comment by alias1** [comment]
@dsander Haven't looked too deeply into `ON_HEROKU`, but it seems to have some interesting quirks (and has sort of outlived it's naming IMO) Was thinking after I get done with the docker stuff, maybe looking into a small refactor of it, check where it's used, and call it something more relevant (probably with a legacy mapping of `ON_HEROKU`->`new name`) As best I can tell, it's main uses seem to be around the dotfile/env var usage, and forcing to postgres DB.

(Not necessarily relevant to this thread, but reminded me of a thing I was thinking about)

**Comment by dsander** [comment]
@ckir Feel free the reopen the issue if the latest docker image still has problems for your use case.
