### ISSUE TITLE
Questions about how schedule and propagate work

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#1956]
Suppose `AgentA -> AgentB`, while Agent B is a WebsiteAgent, its Schedule is `Every 5h`, and `Propagate immediately` is Yes.

Now, AgentA emit a new event X containing `URL` to AgentB. Because propagate immediately, B execute immediately as expected to fetch URL AgentA gave, but encounter 404 or timeout (log below), resulting in the failure to get the specified webpage.

So my confusion is: (in the premise of no new event A gave)
* B will still fetch that url every 5h, and once not 404 and timeouts anymore, it will get the specified webpage?
* or B will not fetch this URL anymore, until A emit a new event?

In my Huginn instance, it seems that AgentB do not fetch this url anymore, after encounter the error the first time. 
Is it normal?

![](http://onuia4d7l.bkt.clouddn.com/2017_04_07_20170407112213.png)
![](http://onuia4d7l.bkt.clouddn.com/2017_04_07_20170407112450.png)
timeout log:
```
Error when fetching url: execution expired (Delayed::Worker.max_run_time is only 120 seconds)
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/ethon-0.7.1/lib/ethon/easy/operations.rb:23:in `easy_perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/ethon-0.7.1/lib/ethon/easy/operations.rb:23:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/typhoeus-0.6.9/lib/typhoeus/request/operations.rb:16:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/typhoeus-0.6.9/lib/typhoeus/request/cacheable.rb:18:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/typhoeus-0.6.9/lib/typhoeus/request/block_connection.rb:31:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/typhoeus-0.6.9/lib/typhoeus/request/stubbable.rb:23:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/typhoeus-0.6.9/lib/typhoeus/request/before.rb:26:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/typhoeus-0.6.9/lib/typhoeus/adapters/faraday.rb:68:in `perform_request'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/typhoeus-0.6.9/lib/typhoeus/adapters/faraday.rb:58:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/gzip.rb:24:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/home/huginn/huginn/app/concerns/web_request_concern.rb:26:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
/home/huginn/huginn/app/models/agents/website_agent.rb:344:in `check_url'
/home/huginn/huginn/app/models/agents/website_agent.rb:333:in `block in check_urls'
/home/huginn/huginn/app/models/agents/website_agent.rb:332:in `each'
/home/huginn/huginn/app/models/agents/website_agent.rb:332:in `check_urls'
/home/huginn/huginn/app/models/agents/website_agent.rb:430:in `block (2 levels) in receive'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:62:in `interpolate_with'
/home/huginn/huginn/app/models/agents/website_agent.rb:413:in `block in receive'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/relation/delegation.rb:38:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/relation/delegation.rb:38:in `each'
/home/huginn/huginn/app/models/agents/website_agent.rb:412:in `receive'
/home/huginn/huginn/app/concerns/sortable_events.rb:99:in `receive'
/home/huginn/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/execution.rb:34:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/logging.rb:44:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/execution.rb:33:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/execution.rb:22:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/reloader.rb:68:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/reloader.rb:67:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.0.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesuppor
```

**Comment by dsander** [comment]
How is your `WebsiteAgent` configured? It will both run when receiving and event and when it's scheduled to run. If you are using something like `{{url}}` for the Agents url configuration the url will be empty when running on schedule and thus do nothing.

**Comment by waldens** [comment]
@dsander Thanks! `{{url}}` is indeed the point!
```
{
  "expected_update_period_in_days": "20",
  "url_from_event": "{{ url }}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "link": {
      "css": "#pageList #pageLink",
      "value": "@href"
    }
  },
  "template": {
    "url": "{{ url | to_uri: _response_.url }}"
  }
}
```
Once timeout, it will not re-fetch, resulting in this period was directly skipped.

![](http://onuia4d7l.bkt.clouddn.com/2017_04_09_20170409200837.png)

This is really a problem, but not an urgent and important one for me. So close this for now.
Thanks for @dsander 's explanation. Help me so many times already!

**Comment by dsander** [comment]
Glad I could help! You can use a `CommanderAgent` which will receive the event from `Agent A` as well and reconfigures the `url` of the `WebsiteAgent` to the current value. The WebsiteAgent will then fetch the configured url during the next scheduled run times.
