### ISSUE TITLE
"Run Event propagation" job stuck

### ISSUE THREAD

**Issue by axsuul** [cantino/huginn#1972]
It appears my **Run Event propagation** is stuck in `/jobs`. How do I fix this? I've tried restarting both the background worker and web app with no effect.

<img width="1148" alt="2017-04-18 at 11 11 pm" src="https://cloud.githubusercontent.com/assets/187961/25165635/54a5c0b0-248c-11e7-884f-e18eec964858.png">

**Comment by cantino** [comment]
Hey @axsuul, that's odd. It'd be nice to see what's happening with that stuck job. Do you see anything in your logs?

How are you running Huginn? You could definitely unstick this by executing `delete from delayed_jobs;` on your SQL server.

**Comment by budric** [comment]
I have the same issue after upgrading to e3f79bf84bb6d2593aef563133edcaa32ae47d38.  After >10 hours event propagation gets stuck.  Restarting huginn machine entirely makes it run for a while.  I see events being processed but then next day it's stuck.

I also added another delayed_job in Procfile (2 in total from 1), but that did not fix the issue.

Nothing seems to be eating up CPU.

I reviewed the logs and this is the only thing that seems relevant - other 
```
I, [2017-04-28T06:48:04.526608 #145]  INFO -- : 2017-04-28T06:48:04-0700: [Worker(host:huginn pid:145)] Error while reserving job: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use
```

**Comment by dsander** [comment]
@budric Try to increase the `DATABASE_POOL` variable in your `.env` file. I am using `30` without having issues but that depends a bit on the amount of Agents that are used.

**Comment by budric** [comment]
@dsander I modified .env file and ran rake production:export for changes to take effect.  The huginn-jobs-1 could not be stopped - presumably this is the one that's stuck propagating events.  Here's --trace output if that helps pin down the problem in any way.

Aside from restarting the machine it doesn't want to go down.

```
$>sudo bundle exec rake production:export --trace
** Invoke production:export (first_time)
** Invoke production:check (first_time)
** Execute production:check
** Execute production:export
** Execute production:stop
Stopping huginn ...
ok: down: huginn-web-1: 150s, normally up
rake aborted!
'sv stop huginn-jobs-1' exited with a non-zero return value: timeout: run: huginn-jobs-1: (pid 145) 107999s, want down, got TERM
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:33:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/huginn/huginn/lib/tasks/production.rake:57:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => production:export
```

**Comment by dsander** [comment]
When the process doesn't stop gracefully try: `sudo bundle exec rake production:force_stop`

**Comment by budric** [comment]
@dsander, thanks.  Increasing the DATABASE_POOL to 30 seems to have fixed the problem.  It's been up over the weekend and events are still being propagated.

**Comment by dsander** [comment]
Nice, let's hope it stays that way :)

**Comment by JonTheNiceGuy** [comment]
I have the same issue as this. I'm running Huginn on Docker, with the following `docker-compose.yml` file:

```
version: '3'

services:
  web:
    image: huginn/huginn
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./mysql-data:/var/lib/mysql
    env_file: .env
```

My `.env` file has the following lines:

```
PORT=3000
RAILS_ENV=production
FORCE_SSL=true
IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS=false
SMTP_DELIVERY_METHOD=sendmail
RAILS_ENV=production
DATABASE_POOL=60

DOMAIN=<hidden>
APP_SECRET_TOKEN=<hidden>
INVITATION_CODE=<hidden>
EMAIL_FROM_ADDRESS=<hidden>
TWITTER_OAUTH_KEY=<hidden>
TWITTER_OAUTH_SECRET=<hidden>
GITHUB_OAUTH_KEY=<hidden>
GITHUB_OAUTH_SECRET=<hidden>
DROPBOX_OAUTH_KEY=<hidden>
DROPBOX_OAUTH_SECRET=<hidden>
```

I'm unable to run `bundle exec rake production:export --trace` as I get the following:

```
** Invoke production:export (first_time)
** Invoke production:check (first_time)
** Execute production:check
[ FAIL ] Please install runit:

sudo apt-get install runit
```

In my jobs page, I get this:

![image](https://user-images.githubusercontent.com/228671/97968045-06c8ac00-1db6-11eb-9a85-fb1f924e9392.png)


This is the total of my agents, right now:

![image](https://user-images.githubusercontent.com/228671/97968095-1811b880-1db6-11eb-9bf3-1b509947d064.png)

Any thoughts? Happy to do some basic diagnostics!

**Comment by sibbl** [comment]
I'm having the same issues with the Docker and MariaDB setup.

Increasing the `DATABASE_POOL` didn't help.

The Docker logs show nothing and inside the Docker container, the existing directory `/app/logs` is completely empty.

`bundle exec rake production:export` also exits with `[ FAIL ] Please install runit:`

Any more ideas?

**Comment by daviddavo** [comment]
Same problem here using default docker container (only one container with everything)

Perhaps connecting to an external DB could solve the problem.

Another thing that would be nice would be to add better health checks to the container like: "If there are more than 50 jobs on the queue, the container is unhealthy". Then, the docker swarm should restart it.
