### ISSUE TITLE
can't stop jobs

### ISSUE THREAD

**Issue by SamPeng87** [cantino/huginn#1988]
when i run stop,

‘’‘
rake aborted!
'sv stop huginn-jobs-1' exited with a non-zero return value: timeout: run: huginn-jobs-1: (pid 18212) 42578s, want down, got TERM
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:33:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => production:stop
'''

i have one rss agent job，this fetch feed has error，then block all other job。so，I want restart huginn.but dont' stop this.

**Comment by SamPeng87** [comment]
delete not useful
disable not useful

**Comment by dsander** [comment]
When the process is stuck you can use `sudo bundle exec rake production:force_stop` to forcefully kill the process.

**Comment by wuhgit** [comment]
> 
> 
> When the process is stuck you can use `sudo bundle exec rake production:force_stop` to forcefully kill the process.

@dsander
Could you tell me how to stop job in docker?
I run huginn in docker , There is a job stuck. I almost tried all the solutions. even stop huginn image or stop docker service, after restart this image , this task still stuck there

**Comment by dsander** [comment]
@wuhgit If you stopped the docker images the Job is only stuck in the database. The only way to remove it is to manually delete the database row.

```
# get a shell inside the docker container (replace huginn with the name or id of the container)
docker exec -it huginn /bin/bash

# source the environment file
source .env

# get a rails console
bundle exec rails console

# inside the rails console delete  the job 
Delayed::Job.where('locked_at IS NOT NULL AND locked_by IS NOT NULL AND failed_at IS NULL').destroy_all

**Comment by wuhgit** [comment]
> 
> 
> @wuhgit If you stopped the docker images the Job is only stuck in the database. The only way to remove it is to manually delete the database row.
> 
> ```
> # get a shell inside the docker container (replace huginn with the name or id of the container)
> docker exec -it huginn /bin/bash
> 
> # source the environment file
> source .env
> 
> # get a rails console
> bundle exec rails console
> 
> # inside the rails console delete  the job 
> Delayed::Job.where('locked_at IS NOT NULL AND locked_by IS NOT NULL AND failed_at IS NULL').destroy_all
> ```

Thanks!
maybe I will try this next time , I stop the Mysql service and power off vps, after reboot ,everything work as normal now

**Comment by XeroAlpha** [comment]
> Delayed::Job.where('locked_at IS NOT NULL AND locked_by IS NOT NULL AND failed_at IS NULL').destroy_all

It just hide the running jobs from jobs list. Queueing jobs are still keep queueing.

![image](https://user-images.githubusercontent.com/22394706/128821778-bee3db20-aae4-4c6d-87f8-4c289bd1ab48.png)
