### ISSUE TITLE
Huginn setup fails while bundling nokogiri

### ISSUE THREAD

**Issue by shahamit** [cantino/huginn#497]
While following the novice setup guide, my installation fails at the bundle step. After installing mysql2 it seems to fail at bundling nokogiri step. I am installing huginn on CentOS 7. Below are the logs

```
Building nokogiri using packaged libraries.
Building libxml2-2.8.0 for nokogiri with the following patches applied:
        - 0001-Fix-parser-local-buffers-size-problems.patch
        - 0002-Fix-entities-local-buffers-size-problems.patch
        - 0003-Fix-an-error-in-previous-commit.patch
        - 0004-Fix-potential-out-of-bound-access.patch
        - 0005-Detect-excessive-entities-expansion-upon-replacement.patch
        - 0006-Do-not-fetch-external-parsed-entities.patch
        - 0007-Enforce-XML_PARSER_EOF-state-handling-through-the-pa.patch
        - 0008-Improve-handling-of-xmlStopParser.patch
        - 0009-Fix-a-couple-of-return-without-value.patch
        - 0010-Keep-non-significant-blanks-node-in-HTML-parser.patch
        - 0011-Do-not-fetch-external-parameter-entities.patch
************************************************************************
IMPORTANT!  Nokogiri builds and uses a packaged version of libxml2.

If this is a concern for you and you want to use the system library
instead, abort this installation process and reinstall nokogiri as
follows:

    gem install nokogiri -- --use-system-libraries

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

However, note that nokogiri does not necessarily support all versions
of libxml2.

For example, libxml2-2.9.0 and higher are currently known to be broken
and thus unsupported by nokogiri, due to compatibility problems and
XPath optimization bugs.
************************************************************************

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

/usr/local/share/gems/gems/mini_portile-0.6.0/lib/mini_portile.rb:279:in `block in execute': Failed to complete patch task (RuntimeError)
        from /usr/local/share/gems/gems/mini_portile-0.6.0/lib/mini_portile.rb:271:in `chdir'
        from /usr/local/share/gems/gems/mini_portile-0.6.0/lib/mini_portile.rb:271:in `execute'
        from extconf.rb:282:in `block in patch'
        from extconf.rb:279:in `each'
        from extconf.rb:279:in `patch'
        from /usr/local/share/gems/gems/mini_portile-0.6.0/lib/mini_portile.rb:108:in `cook'
        from extconf.rb:253:in `block in process_recipe'
        from extconf.rb:154:in `tap'
        from extconf.rb:154:in `process_recipe'
        from extconf.rb:423:in `<main>'

Gem files will remain installed in /usr/local/share/gems/gems/nokogiri-1.6.3.1 for inspection.
Results logged to /usr/local/share/gems/gems/nokogiri-1.6.3.1/ext/nokogiri/gem_make.out
An error occurred while installing nokogiri (1.6.3.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.3.1'` succeeds before bundling.
```

How should I proceed?

**Comment by va1t** [comment]
fixed this by doing this

<code>sudo yum install patch</code>
or
You could also install build-essential package to make sure you have the basic tools used for compiling.
<code>sudo yum install build-essential</code>

:D

**Comment by cantino** [comment]
Glad it's working!
