### ISSUE TITLE
SlackAgent is throwing "getaddrinfo: Name or service not known" error.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#637]
I'm doing an experimental integration with a Slack channel (generating events with ManualAgent) and I'm not able to send any messages to the integration channel.  Here's the agent in question (specifics redacted)

```
{
  "team_name": "Team Name",
  "auth_token": "{% credential slack_api_key %}",
  "channel": "#misc",
  "username": "TestBot",
  "message": "{{message}}",
  "webhook": "https://hooks.slack.com/services/foo/bar/baz"
}
```
Here's the stack trace from log message (and thanks again for being able to see the whole thing!):
```
Exception during receive. getaddrinfo: Name or service not known: /home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:879:in `open'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:67:in `timeout'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:852:in `start'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1369:in `request'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/rest-client-1.6.8/lib/restclient/net_http_ext.rb:51:in `request'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/slack-notifier-1.0.0/lib/slack-notifier/default_http_client.rb:20:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/slack-notifier-1.0.0/lib/slack-notifier/default_http_client.rb:8:in `post'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/slack-notifier-1.0.0/lib/slack-notifier.rb:23:in `ping'
/home/drwho/huginn/app/models/agents/slack_agent.rb:70:in `block in receive'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/delegation.rb:46:in `each'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/delegation.rb:46:in `each'
/home/drwho/huginn/app/models/agents/slack_agent.rb:68:in `receive'
/home/drwho/huginn/app/models/agent.rb:387:in `async_receive'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:82:in `block in timeout'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `catch'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `timeout'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:150:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'
```

I SSH'd into the machine in question and I can successfully resolve hooks.slack.com to an IP address.  I suspect that I may have messed something up (does the Slack Ruby class allow rooms that start with #?) but I'm not sure.  I can reproduce this pretty reliably.

**Comment by virtadpt** [comment]
@knu Any luck?

**Comment by virtadpt** [comment]
I haven't had this problem for a couple of months, so I'm wondering if it wasn't problems on Slack's side of things.  At work some other code was having difficulty with Slack integration if I recall correctly, so this might not have been a bug in Huginn at all (though an error message instead of a stack trace would have been better UX - "{{agent.name}} was unable to resolve the hostname of the Slack server {{webhook_url}} - please contact the Slack helpdesk to open a ticket.")

**Comment by virtadpt** [comment]
This ticket's been a no-op for months.  It seems to have been a glitch in Slack's public DNS zones.  Let's close it out.

**Comment by cantino** [comment]
Sounds good, thanks.
