### ISSUE TITLE
Wrong timezone name results in failure to start

### ISSUE THREAD

**Issue by PAStheLoD** [cantino/huginn#660]
Hello!

Instead of the required Cityname I tried the usual Continent/Cityname (instead of running the rake task for it), and foreman start resulted in this:

```
sudo -u hug -H bundle exec foreman start                                                                                                                  
06:38:11 web.1  | started with pid 30252
06:38:11 jobs.1 | started with pid 30254
06:38:13 jobs.1 | ## Include the `twitter`, `omniauth-twitter`, and `cantino-twitter-stream` gems in your Gemfile to use Twitter Agents.
06:38:13 jobs.1 | Exception no implicit conversion of nil into String:
06:38:13 jobs.1 | /home/hug/huginn/lib/huginn_scheduler.rb:117:in `+'
06:38:13 jobs.1 | /home/hug/huginn/lib/huginn_scheduler.rb:117:in `run!'
06:38:13 jobs.1 | bin/threaded.rb:37:in `block (2 levels) in <top (required)>'
06:38:13 jobs.1 | bin/threaded.rb:16:in `safely'
06:38:13 jobs.1 | bin/threaded.rb:35:in `block in <top (required)>'
06:38:13 jobs.1 | 
06:38:13 jobs.1 | Terminating myself ...
06:38:13 jobs.1 | Exiting...
06:38:13 jobs.1 | 
06:38:13 jobs.1 | Twitter stream stopped ...
06:38:13 jobs.1 | bin/threaded.rb:10:in `stop': private method `stop' called for nil:NilClass (NoMethodError)
06:38:13 jobs.1 |       from bin/threaded.rb:21:in `rescue in safely'
06:38:13 jobs.1 |       from bin/threaded.rb:15:in `safely'
06:38:13 jobs.1 |       from bin/threaded.rb:35:in `block in <top (required)>'
06:38:13 jobs.1 | exited with code 1
06:38:13 system | sending SIGTERM to all processes
06:38:13 web.1  | terminated by SIGTERM
```

The twitter stream related error is a bug too (because I do have the required gems and bundler list shows them too).

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
