### ISSUE TITLE
Need help with text regexp (Website Agent)

### ISSUE THREAD

**Issue by brunoqc** [cantino/huginn#673]
I'm trying to extract versions (ideally only the latest) from a changelog. I tested the regex on http://rubular.com/r/n4gGUMvGCl

Here's the JSON on the agent detail page :

```json
{
  "expected_update_period_in_days": "2",
  "url": "https://rt-n56u.googlecode.com/git/changes.eng.txt",
  "type": "text",
  "mode": "all",
  "extract": {
    "version": {
      "regexp": "(?m:^([^\\n:]+):?\\n[-]{6})",
      "index": "0"
    }
  }
}
```

When fetching I get :

```
Error when fetching url: undefined group name reference: 0
/app/app/models/agents/website_agent.rb:299:in `[]'
/app/app/models/agents/website_agent.rb:299:in `block (2 levels) in extract_text'
/app/app/models/agents/website_agent.rb:298:in `scan'
/app/app/models/agents/website_agent.rb:298:in `block in extract_text'
/app/app/models/agents/website_agent.rb:282:in `call'
/app/app/models/agents/website_agent.rb:282:in `block in extract_each'
/app/app/models/agents/website_agent.rb:281:in `each'
/app/app/models/agents/website_agent.rb:281:in `each_with_object'
/app/app/models/agents/website_agent.rb:281:in `extract_each'
/app/app/models/agents/website_agent.rb:295:in `extract_text'
/app/app/models/agents/website_agent.rb:183:in `block (2 levels) in check_url'
/app/vendor/bundle/ruby/2.0.0/gems/liquid-2.6.1/lib/liquid/context.rb:112:in `stack'
/app/app/models/agents/website_agent.rb:162:in `block in check_url'
/app/app/models/agents/website_agent.rb:157:in `each'
/app/app/models/agents/website_agent.rb:157:in `check_url'
/app/app/models/agents/website_agent.rb:151:in `check'
/app/app/models/agent.rb:425:in `async_check'
```

**Comment by cantino** [comment]
Is this something you'd like to take a crack at?

**Comment by brunoqc** [comment]
Yes.

**Comment by cantino** [comment]
Let me know how I can help.

**Comment by HyShai** [comment]
This is currently a bug - when editing the JSON in the json-editor it adds quotes around the numbers, therefore it blows up in `validate_extract_options!` [here](https://github.com/cantino/huginn/blob/master/app/models/agents/website_agent.rb#L233) `when String` because it thinks it's a string.

**Comment by cantino** [comment]
Hey @HyShai, can you show an example of the regex that is a number?  Or I think I'm misunderstanding.

**Comment by HyShai** [comment]
This was the result of entering the `index` via the json-editor

```
{
  "expected_update_period_in_days": "2",
  "url": "http://google.com",
  "type": "text",
  "mode": "on_change",
  "extract": {
    "title": {
      "regexp": "(.+)",
      "index": "0"
    }
  }
}
```
The `index` will be passed as a string, not an integer.

**Comment by cantino** [comment]
Hey @HyShai, thanks for clarifying!  Could you tell me if #884 fixes this for you?

**Comment by HyShai** [comment]
yup, seems to be fixed- thanks!

**Comment by cantino** [comment]
Great!
