### ISSUE TITLE
bin/setup_heroku fails if you supply an account password with a semicolon in it

### ISSUE THREAD

**Issue by panicsteve** [cantino/huginn#696]
If you enter a password containing a semicolon when prompted by this script, it does not seem to get properly escaped, and only the portion up to the semicolon is used.  If this is less than 8 characters, it will fail with a "password is too short" as shown in the transcript below.

(Email address and password redacted for obvious reasons)

----

```
(... other setup happens here ...)
Okay, what is your email address? xxx@xxx.com
And what username would you like to login as? xxx
Finally, what password would you like to use? 
Just a moment...
ERROR:

Running `rake db:seed SEED_EMAIL=xxx@xxx.com SEED_USERNAME=xxx SEED_PASSWORD=xxx` attached to terminal... up, run.3041
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Password is too short (minimum is 8 characters)
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in `save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `block in save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `save!'
/app/db/seeds.rb:10:in `<top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.1.8/lib/rails/engine.rb:543:in `load_seed'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:200:in `load_seed'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:174:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by cantino** [comment]
Ack, thanks for letting me know!
