### ISSUE TITLE
bundle exec rake db:create fails database access the first time

### ISSUE THREAD

**Issue by Pimmetje** [cantino/huginn#724]
I am still new to Huginn and Ruby. I followed the novice start guild. Installed a mysql server and after 
bundle exec rake db:create
i have to type my password (shown on console) but it does not use it. 
```
bundle exec rake db:create
Access denied for user 'root'@'localhost' (using password: NO)Please provide the root password for your mysql installation
>password
Mysql2::Error: Can't create database 'huginn_development'; database exists: CREATE DATABASE `huginn_development` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/lib/gems/1.9.1/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:371:in `create_database'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/mysql_database_tasks.rb:28:in `rescue in create'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/mysql_database_tasks.rb:15:in `create'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:88:in `create'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:102:in `block in create_current'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:225:in `block in each_current_configuration'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each_current_configuration'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:101:in `create_current'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_development", "pool"=>5, "username"=>"root", "password"=>nil, "host"=>nil, "port"=>nil, "socket"=>"/var/run/mysqld/mysqld.sock"}
Access denied for user 'root'@'localhost' (using password: NO)Please provide the root password for your mysql installation
>password
Mysql2::Error: Can't create database 'huginn_test'; database exists: CREATE DATABASE `huginn_test` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/lib/gems/1.9.1/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:371:in `create_database'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/mysql_database_tasks.rb:28:in `rescue in create'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/mysql_database_tasks.rb:15:in `create'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:88:in `create'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:102:in `block in create_current'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:225:in `block in each_current_configuration'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each_current_configuration'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:101:in `create_current'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_test", "pool"=>5, "username"=>"root", "password"=>nil, "socket"=>"/var/run/mysqld/mysqld.sock", "port"=>nil}
```
password is the password of the db. 

What am i doing wrong here?

**Comment by cantino** [comment]
Looks like you already ran the command and so the db already exists?

```
Mysql2::Error: Can't create database 'huginn_development'; database exists: CREATE DATABASE `huginn_development` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`
```

**Comment by Pimmetje** [comment]
Thanks for the respone, i think it was late for me. 

But the part that got me confused. 
```
user@huginn:~/huginn$ bundle exec rake db:create
Access denied for user 'root'@'localhost' (using password: NO)Please provide the root password for your mysql installation
>password
Access denied for user 'root'@'localhost' (using password: NO)Please provide the root password for your mysql installation
>password
```
I had to type the password two times. Without any conformation it was successful..

**Comment by Pimmetje** [comment]
Next step:
```
user@huginn:~/huginn$ bundle exec rake db:migrate
rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: NO)
/var/lib/gems/1.9.1/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `connect'
/var/lib/gems/1.9.1/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `initialize'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:87:in `connection'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/migration.rb:909:in `initialize'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/migration.rb:807:in `new'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/migration.rb:807:in `up'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/migration.rb:785:in `migrate'
/var/lib/gems/1.9.1/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
I think i have to put my MySQL password somewhere. But thats missing in the guild i think. (Or i am still not awake ;))

**Comment by Pimmetje** [comment]
I clearly wasn't awake when i tried it. I have to change the mysql password in the .env file. (maybe at it as a note) Also the script asking for the password is a bit confusing. It should complain about it not being set in the config.

**Comment by cantino** [comment]
Glad you got it figured out!

**Comment by keshavm021** [comment]
thanks @cantino the same problem happen with me.
