### ISSUE TITLE
550 Cannot receive from specified address <(my email)>: Unauthenticated senders not allowed

### ISSUE THREAD

**Issue by Nateliason** [cantino/huginn#763]
Any idea how I fix this problem so that I can email myself alerts?

**Comment by Nateliason** [comment]
I entered my email during the setup in terminal, never added a password or other credentials though. Is there some way to authenticate your email address as a service?

**Comment by cantino** [comment]
Maybe the sendgrid credentials didn't get setup correctly?  Do you have a verified Heroku account (has a credit card number in it)?

**Comment by Nateliason** [comment]
Oh Heroku isn't verified, let me do that

**Comment by Nateliason** [comment]
Same problem

**Comment by cantino** [comment]
See if the sendgrid addon is setup for the huginn heroku project with their web UI.

**Comment by Nateliason** [comment]
Okay, added that, do I need to refresh the app or something?

**Comment by cantino** [comment]
You may need to set the sendgrid details in the ENV, or it may just work.

**Comment by Nateliason** [comment]
Kk I set the variables, I'll let you know if this fixes it

**Comment by Nateliason** [comment]
Still doesn't work, here's the error output:

/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/smtp.rb:951:in `check_response'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/smtp.rb:920:in `getok'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/smtp.rb:835:in `mailfrom'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/smtp.rb:662:in `send_message'
/app/vendor/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:113:in `block in deliver!'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/smtp.rb:521:in `start'
/app/vendor/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/app/vendor/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/app/vendor/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/app/vendor/bundle/ruby/2.0.0/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.0.0/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:541:in `deliver_mail'
/app/vendor/bundle/ruby/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/app/vendor/bundle/ruby/2.0.0/gems/actionmailer-4.2.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/performable_mailer.rb:7:in `perform'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'

**Comment by cantino** [comment]
You may need to show us the values in `heroku config` (but please anonymize anything sensitive!)

**Comment by cantino** [comment]
Did you solve this issue?

**Comment by sea-grass** [comment]
I had this issue as well. When initially setting up my Heroku app, my account was not verified, so SendGrid wasn't setup. I tried some other things after validating my account and it still wasn't working. Finally, I performed the following steps and got it working:

My solution was the following:

 1. Verify my Heroku account
 2. Make sure to remove the SendGrid add-on via the Heroku UI
 3. Remove all mail-related config variables using `heroku config:unset` in the Heroku CLI
 4. Run `bin/setup_heroku` again
 5. Answer yes when prompted to add the SendGrid add-on

After those steps, the email config variables are all properly set and the SendGrid add-on is added to my app. Sending emails from Huginn works.

**Comment by cantino** [comment]
Thanks @sea-grass!  Would you mind adding this to our wiki?

**Comment by erebor** [comment]
Sounds like this issue is solved. Could the issue be closed?
