### ISSUE TITLE
"Exception during receive. Event(#70191681695620) expected, got Event(#70191632320580):"

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#792]
Instances of the Change Detect Agent appear to be working, but also throw exceptions of the form "Exception during receive. Event(#70191681695620) expected, got Event(#70191632320580):" along with the following stack trace:
```
Exception during receive. Event(#70191681695620) expected, got Event(#70191632320580): /home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/associations/association.rb:216:in `raise_on_type_mismatch!'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/associations/belongs_to_association.rb:12:in `replace'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/associations/singular_association.rb:17:in `writer'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/associations/builder/association.rb:123:in `outbound_event='
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/attribute_assignment.rb:54:in `public_send'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:67:in `block in assign_attributes'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `each'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `assign_attributes'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/core.rb:281:in `initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/inheritance.rb:61:in `new'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/inheritance.rb:61:in `new'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/reflection.rb:5:in `build_association'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:5:in `build_record'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:42:in `block in create_record'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:182:in `transaction'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:41:in `create_record'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:30:in `create!'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:64:in `create!'
/home/drwho/huginn/app/models/agent_log.rb:20:in `log_for_agent'
/home/drwho/huginn/app/models/agent.rb:203:in `log'
/home/drwho/huginn/app/models/agents/change_detector_agent.rb:57:in `handle'
/home/drwho/huginn/app/models/agents/change_detector_agent.rb:46:in `block in receive'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/home/drwho/huginn/app/models/agents/change_detector_agent.rb:45:in `receive'
/home/drwho/huginn/app/models/agent.rb:399:in `async_receive'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/performable_method.rb:30:in `perform'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `call'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'
```
These stack traces consistently appear in sets of five, one after another after another without any measureable delay (at least, from what I can tell from the Logs tab).  They also result in five end results being emitted at a time (from Email Agent instances).

Source agents (Website Agent) are only emitting one event at a time, verified on their own Logs tabs.

**Comment by cantino** [comment]
Looks like this? http://stackoverflow.com/a/17667722/303661

We should get you running in production mode.

**Comment by virtadpt** [comment]
It does, now that you mention it.

I'll do some research on that tomorrow.

**Comment by cantino** [comment]
@dsander's suggestion of running just the delayed_jobs in production is
also a good one.

**Comment by virtadpt** [comment]
I can turn that back on.  Since rebuilding I've been using the default threaded.rb job runner.  It might also fix the "unauthorized" errors the Twiter agents have been throwing, possibly because they were exceeding the allowed CPS.

**Comment by virtadpt** [comment]
In Procfile, disable the first "web" and "jobs" lines and re-enable the last four lines ("web", "schedule", "twitter", "dj")?  Possibly go back to two "dj" lines?
.env:
```
RAILS_ENV=production
```
Run:
```
rake assets:precompile
```
...and restart Huginn?  Does this sound about right?

**Comment by dsander** [comment]
I have prepended `export RAILS_ENV=production; ` before each bundle exec call to start the background workers, but I am not 100% sure its needed.

If you do not have nginx or apache running in front of unicorn you might also need set `RAILS_SERVE_STATIC_FILES` to something in your `.env`

**Comment by virtadpt** [comment]
I do have Nginx standing in front of it, serving static content and doing SSL termination (as well as HTTP Basic Auth for Huginn).

Is setting `RAILS_ENV=production` in .env not sufficient?

**Comment by dsander** [comment]
It might be, but I did not test it.

**Comment by virtadpt** [comment]
Testing the hypothesis I outlined above and using what I found here (http://stackoverflow.com/questions/13979760/rails-deploying-first-app-production-mode) did not work.  I've reverted to development mode.

**Comment by virtadpt** [comment]
To restore full functionality, I had to shut Huginn down and manually delete the public/assets/ directory before restarting because the menubar wasn't functioning correctly (specifically, drop-downs weren't working).
