### ISSUE TITLE
Basic huginn installation (threw docker) take 90% CPU all the time with 0 agent running

### ISSUE THREAD

**Issue by gissehel** [cantino/huginn#795]
With a basic installation docker based, the process threaded.rb takes 90% of CPU.

## Steps to reproduce
* Just launch `sudo docker run -d --name huginn cantino/huginn`
* use `ps`/`top`/`htop` on host to monitor processes (from hosts and from containers)
* Initialisation process and database migration doesn't take much CPU, then the main server and threaded.rb starts. One of the threads from threaded.rb takes 90% of CPU while I can't find which one with the tools I have.

## Context
* **CPU** : `Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz` (4 cores)
* **Memory** : 32 GB
* CPU almost not used by other processes

reproduced on another environnement with same CPU but 16 GB Ram.

**Comment by cantino** [comment]
@ianblenke, do you have any ideas about this?

**Comment by ianblenke** [comment]
Indeed, threaded.rb does seem to merrily spin. If I strace it, it seems to be constantly stat()ing "/etc/localtime" trying to discover the timezone. I can bypass that stat() check by specifying TZ=UTC+0, but that only kicks the can down the road to the real problem: a futex() is timing out - there is a ruby thread deadlock going on. Do we have some kind of resource contention between ruby threads that may be causing this?

**Comment by cantino** [comment]
Weird.  @dsander, could this be Rufus?

**Comment by dsander** [comment]
I can't really debug my docker container on OSX (boot2docker does not have strace installed and running strace inside the container is somehow not permitted), but it looks like the cause is Rufus.

Inside the container I changed `/tmp/foreman.sh` to call `exec sudo -u huginn -EH bundle exec rails runner bin/schedule.rb TZ=UTC+0` and that process is still consuming almost 100% of the cpu. When I just run delayed job everything looks find.

However I have no idea how to fix it since its running fine without docker.

**Comment by ianblenke** [comment]
To run strace, start the container up as privileged:

```console
docker run -d --privileged --name huginn -e TZ=UTC+0 cantino/huginn
```

Then get an interactive bash shell in that container process namespace:

```consoledocker exec -ti huginn /bin/bash -li
root@17f2f6334003:/#
```

You can now get strace:

```console
root@17f2f6334003:/# apt-get update && apt-get install strace
```

Run top to find the pid of the ruby-2.1 process that is spinning:

```console
root@17f2f6334003:/# TERM=vt100 top
```

With the pid, you can now strace it:

```console
root@17f2f6334003:/# strace -f -p 435
```

It is just this repeating over and over again:

```console
[pid   451] futex(0x7ff7b80017b4, FUTEX_WAIT_BITSET_PRIVATE, 1108527, {965916, 600097333}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid   451] futex(0x7ff7b8001830, FUTEX_WAKE_PRIVATE, 1) = 0
[pid   451] clock_gettime(CLOCK_MONOTONIC, {965916, 600509464}) = 0
[pid   451] clock_gettime(CLOCK_REALTIME, {1429675868, 395797897}) = 0
[pid   451] clock_gettime(CLOCK_MONOTONIC, {965916, 601042521}) = 0
[pid   451] clock_gettime(CLOCK_MONOTONIC, {965916, 601129893}) = 0
[pid   451] futex(0x7ff7b80017b4, FUTEX_WAIT_BITSET_PRIVATE, 1108529, {965916, 601129893}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid   451] futex(0x7ff7b8001830, FUTEX_WAKE_PRIVATE, 1) = 0
[pid   451] clock_gettime(CLOCK_MONOTONIC, {965916, 601499164}) = 0
[pid   451] clock_gettime(CLOCK_REALTIME, {1429675868, 396756204}) = 0
[pid   451] clock_gettime(CLOCK_MONOTONIC, {965916, 601987793}) = 0
[pid   451] clock_gettime(CLOCK_MONOTONIC, {965916, 602127983}) = 0
```

You can cntl-c to stop that output.

My understanding is that this is a threading deadlock. 

To see where in the ruby it is deadlocking, time for some gdb:

```console
root@17f2f6334003:/# apt-get install -y gdb
...
root@17f2f6334003:/# gdb -p 435
...
(gdb) call (void)rb_backtrace()
(gdb)
```

That actually triggered a backtrace to stdout, which is visible in the docker logs for that container:

```
docker logs --tail=83 huginn
foreman stdout | 04:17:26 jobs.1 | 	from bin/threaded.rb:43:in `block in <top (required)>'
04:17:26 jobs.1 | 	from bin/threaded.rb:16:in `safely'
04:17:26 jobs.1 | 	from bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:162:in `block (2 levels) in start'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:297:in `reload!'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:60:in `cleanup!'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:60:in `new'
04:17:26 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:66:in `initialize'
foreman stdout | 04:18:02 jobs.1 | Queuing event propagation
foreman stdout | 04:18:02 jobs.1 | { 70350961342800 rufus-scheduler intercepted an error:
foreman stdout | 04:18:02 jobs.1 |   70350961342800   job:
foreman stdout | 04:18:02 jobs.1 |   70350961342800     Rufus::Scheduler::EveryJob "1m" {}
foreman stdout | 04:18:02 jobs.1 |   70350961342800   error:
foreman stdout | 04:18:02 jobs.1 |   70350961342800     70350961342800
foreman stdout | 04:18:02 jobs.1 |   70350961342800     NoMethodError
foreman stdout | 04:18:02 jobs.1 | Queuing schedule for every_1m
foreman stdout | 04:18:02 jobs.1 |   70350961342800     undefined method `cannot_be_scheduled!' for #<Class:0x007ff7b82af370>
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/app/models/agents/scheduler_agent.rb:7:in `<class:SchedulerAgent>'
04:18:02 jobs.1 |   70350961342800       /app/app/models/agents/scheduler_agent.rb:4:in `<module:Agents>'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/app/models/agents/scheduler_agent.rb:3:in `<top (required)>'
04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/lib/huginn_scheduler.rb:84:in `schedule_scheduler_agents'
04:18:02 jobs.1 |   70350961342800       /app/lib/huginn_scheduler.rb:143:in `block in run!'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `call'
04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `do_call'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in `call'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
foreman stdout | 04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `loop'
04:18:02 jobs.1 |   70350961342800       /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
foreman stdout | 04:18:02 jobs.1 |   70350961342800   tz:
foreman stdout | 04:18:02 jobs.1 |   70350961342800     ENV['TZ']: UTC+0
04:18:02 jobs.1 |   70350961342800     Time.now: 2015-04-22 04:18:02 +0000
foreman stdout | 04:18:02 jobs.1 |   70350961342800   scheduler:
foreman stdout | 04:18:02 jobs.1 |   70350961342800     object_id: 76608720
04:18:02 jobs.1 |   70350961342800     opts:
foreman stdout | 04:18:02 jobs.1 |   70350961342800       {:frequency=>""}
04:18:02 jobs.1 |   70350961342800       frequency: 0.0
04:18:02 jobs.1 |   70350961342800       scheduler_lock: #<Rufus::Scheduler::NullLock:0x0000000921e5e0>
04:18:02 jobs.1 |   70350961342800       trigger_lock: #<Rufus::Scheduler::NullLock:0x0000000921e5b8>
04:18:02 jobs.1 |   70350961342800     uptime: 597.454890347 (9m57s454)
foreman stdout | 04:18:02 jobs.1 |   70350961342800     down?: false
04:18:02 jobs.1 |   70350961342800     threads: 4
04:18:02 jobs.1 |   70350961342800       thread: #<Thread:0x0000000921e568>
04:18:02 jobs.1 |   70350961342800       thread_key: rufus_scheduler_76608720
04:18:02 jobs.1 |   70350961342800       work_threads: 3
foreman stdout | 04:18:02 jobs.1 |   70350961342800         active: 2
foreman stdout | 04:18:02 jobs.1 |   70350961342800         vacant: 1
04:18:02 jobs.1 |   70350961342800         max_work_threads: 28
04:18:02 jobs.1 |   70350961342800       mutexes: {}
04:18:02 jobs.1 |   70350961342800     jobs: 40
04:18:02 jobs.1 |   70350961342800       at_jobs: 0
04:18:02 jobs.1 |   70350961342800       in_jobs: 0
foreman stdout | 04:18:02 jobs.1 |   70350961342800       every_jobs: 15
04:18:02 jobs.1 |   70350961342800       interval_jobs: 0
foreman stdout | 04:18:02 jobs.1 |   70350961342800       cron_jobs: 25
04:18:02 jobs.1 |   70350961342800     running_jobs: 2
04:18:02 jobs.1 |   70350961342800     work_queue: 0
04:18:02 jobs.1 | } 70350961342800 .
foreman stdout | 04:19:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler.rb:561:in `block in start'
foreman stdout | 04:19:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler.rb:582:in `trigger_jobs'
```

Hope this helps.

**Comment by dsander** [comment]
@ianblenke Thanks a lot for the detailed instructions! I was missing the `--privileged` option.

The PR fixes the issue with the rufus scheduler using a lot of CPU, do you think we still need to specify the `TZ` in the `Dockerfile`? I guess it would now still do the `stat` call, but less frequently.

**Comment by dsander** [comment]
Build a new docker image with the PR applied and the strace is totally quiet, which is a good but not quite what I expected.

**Comment by gissehel** [comment]
I confirm I can't reproduce the problem with the docker image.

**Comment by cantino** [comment]
I just got back from a trip to RailsConf.  Thank you @ianblenke d n @dsander for your hard work diagnosing and fixing this!
