### ISSUE TITLE
"A copy of TwitterStream has been removed from the module tree but is still active!"

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#799]
The backgrounded jobs thread throws the following seemingly harmless exception every time the two minute scheduler runs:
```
15:54:29 jobs.1 | Exception A copy of TwitterStream has been removed from the module tree but is still active!:
15:54:29 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:479:in `load_missing_constant'
15:54:29 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
15:54:29 jobs.1 | /home/drwho/huginn/lib/twitter_stream.rb:102:in `run'
15:54:29 jobs.1 | bin/threaded.rb:29:in `block (2 levels) in <top (required)>'
15:54:29 jobs.1 | bin/threaded.rb:16:in `safely'
15:54:29 jobs.1 | bin/threaded.rb:27:in `block in <top (required)>'
15:54:29 jobs.1 | 
15:54:29 jobs.1 | Waiting for a couple of minutes...
```

**Comment by dsander** [comment]
Fixed by #806
