### ISSUE TITLE
jsonpath v0.5.6 doesn't deal with empty strings well.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#807]
In JSON documents having an empty string ( "" ) is considered valid, for example:
```
"source_amount": {
    "currency": "USD",
    "value": "100",
    "issuer": ""
}
```
However, the jsonpath gem drops the following stack trace when it sees empty strings:
```
19:19:14 jobs.1 | Agent#517: Error when fetching url: no implicit conversion of nil into String
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/jsonpath-0.5.6/lib/jsonpath.rb:15:in `initialize'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/jsonpath-0.5.6/lib/jsonpath.rb:15:in `new'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/jsonpath-0.5.6/lib/jsonpath.rb:15:in `initialize'
19:19:14 jobs.1 | /home/drwho/huginn/lib/utils.rb:59:in `new'
19:19:14 jobs.1 | /home/drwho/huginn/lib/utils.rb:59:in `values_at'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:303:in `block in extract_json'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:297:in `call'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:297:in `block in extract_each'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:296:in `each'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:296:in `each_with_object'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:296:in `extract_each'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:302:in `extract_json'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:195:in `block in check_url'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/liquid-2.6.2/lib/liquid/context.rb:112:in `stack'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:173:in `check_url'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:164:in `block in check_urls'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:163:in `each'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:163:in `check_urls'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agents/website_agent.rb:157:in `check'
19:19:14 jobs.1 | /home/drwho/huginn/app/models/agent.rb:437:in `async_check'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/performable_method.rb:30:in `perform'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
19:19:14 jobs.1 | /home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
19:19:14 jobs.1 | /home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
19:19:14 jobs.1 | /home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
19:19:14 jobs.1 | /home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
19:19:14 jobs.1 | /home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
19:19:14 jobs.1 | bin/threaded.rb:47:in `block (2 levels) in <top (required)>'
19:19:14 jobs.1 | bin/threaded.rb:17:in `safely'
19:19:14 jobs.1 | bin/threaded.rb:44:in `block in <top (required)>'
```
All things considered this seems pretty harmless but it can also make it difficult to isolate bugs in other agents running at the same time.  What if there was a way (and there may not be - ECANTFIX is fine) to turn of stack traces like this?

**Comment by cantino** [comment]
Really?  What's the json path you're using?

**Comment by virtadpt** [comment]
For the following JSONpath, if there has been no transaction the strings are empty:
```
"extract": {
    "transaction_timestamp": {
      "value": "$.payments.[*].timestamp"
    },
    "source_account": {
      "value": "$.payments.[*].source_account"
    },
    "destination_account": {
      "value": "$.payments.[*].destination_account"
    },
    "source_value": {
      "value": "$.payments.[*].source_amount.value"
    },
    "source_currency": {
      "value": "$.payments.[*].source_amount.currency"
    },
    "destination_value": {
      "value": "$.payments.[*].destination_amount.value"
    },
    "destination_currency": {
      "value": "$.payments.[*].destination_amount.currency"
    },
    "direction": {
      "value": "$.payments.[*].direction"
    },
    "transaction_hash": {
      "value": "$.payments.[*].hash"
    }
  }
```

**Comment by cantino** [comment]
Which extraction is blowing it up?

**Comment by virtadpt** [comment]
All of them.  If there are no recent transactions, the value of every key in "extract" will be empty (i.e., "").

**Comment by cantino** [comment]
@virtadpt, what URL is that JSONPath fetching?  I'd like to try it locally.  Maybe you could give me the Scenario JSON?

**Comment by virtadpt** [comment]
The scenario JSON is a couple of megabytes in size, so getting it to you will be problematic.  However, here is a URL that triggers this bug on a semi-reliable basis: https://api.ripple.com/v1/accounts/rrrrrrrrrrrrrrrrrrrrBZbvji/payments

**Comment by cantino** [comment]
Haha, so after playing with this for like 45 minutes, I realized you need to use `path` instead of `value`. :hamster: 

#831 should prevent this in the future.

**Comment by virtadpt** [comment]
When I have time I'll update my install and give it a spin.

**Comment by cantino** [comment]
@virtadpt You can just switch your usage from `value` to `path` now and it should work.  My addition is just a validation.

**Comment by virtadpt** [comment]
I've made the change, and it was like night and day. Thanks!

**Comment by cantino** [comment]
Great!
