### ISSUE TITLE
"hostname does not match the server certificate" error when sending mail

### ISSUE THREAD

**Issue by vintz** [cantino/huginn#810]
When trying to send a mail via huginn on my (personal) mail server, i always get this error:
```  hostname does not match the server certificate
/usr/lib/ruby/1.9.1/openssl/ssl-internal.rb:129:in `post_connection_check'
/usr/lib/ruby/1.9.1/net/smtp.rb:585:in `tlsconnect'
/usr/lib/ruby/1.9.1/net/smtp.rb:560:in `do_start'
/usr/lib/ruby/1.9.1/net/smtp.rb:519:in `start'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/var/lib/gems/1.9.1/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/1.9.1/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:541:in `deliver_mail'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/var/lib/gems/1.9.1/gems/actionmailer-4.2.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/performable_mailer.rb:7:in `perform'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'```

I checked my mail server for an error in the configuration and didn't find anything. 
I checked with www.checktls.com and everything seems ok.

Any suggestion about what I did wrong?

**Comment by vintz** [comment]
Here is the SMTP_AUTHENTICATION part of my .env

```
SMTP_DOMAIN=geekmachine.info
SMTP_USER_NAME=huginn
SMTP_PASSWORD=*******
SMTP_SERVER=mail.geekmachine.info
SMTP_ENABLE_STARTTLS_AUTO=false
SMTP_PORT=25
SMTP_AUTHENTICATION=plain
```

**Comment by dsander** [comment]
That's odd, can you try to set `SMTP_DOMAIN` to `mail.geekmachine.info`?

**Comment by vintz** [comment]
I tried it and the result is the same.

**Comment by dsander** [comment]
Does running `openssl s_client -connect mail.geekmachine.info:25 -starttls smtp` on your huginn server output `Verify return code: 0 (ok)`?

**Comment by vintz** [comment]
Good pick. The output is ```Verify return code: 20 (unable to get local issuer certificate)```

Any idea what I should do?

**Comment by dsander** [comment]
Which unix distribution are you using? Debian derivatives have a `ca-certificates` package which you might need to upgrade.

**Comment by vintz** [comment]
I'm on a Debian. And my ca-certificates package is up to date. 

28 avril 2015 14:06 "Dominik Sander"  a écrit:
	Which unix distribution are you using? Debian derivatives have a ca-certificates package which you might need to upgrade.

**Comment by dsander** [comment]
First I tested it from OSX which worked, but I am getting the same result like you do on an ubuntu server. The problem seems to be the missing the [intermediate](https://wiki.gandi.net/en/ssl/intermediate) certificate. If you do not have control over the mailserver you can change the [smtp.yml](https://github.com/cantino/huginn/blob/master/config/smtp.yml#L26) file and add 

`openssl_verify_mode: none`

**Comment by vintz** [comment]
I just tried to add ```openssl_verify_mode: none``` and it doesn't work. I've got the same error message. 

I tried to add the missing intermediate certificate to my mail server and the error message keep happening.

**Comment by dsander** [comment]
I am now getting `21 (unable to verify the first certificate)`, it's strange that the òpenssl_verify_mode` setting does not work.

**Comment by cantino** [comment]
Seems like it would work -- https://github.com/rails/docrails/commit/a1639ad7524127be0a9e9398dc2ccc8c6629adee -- unless there error is in the mail server?

**Comment by vintz** [comment]
The problem is more than probably in the mail server. I'm trying to reconfigurate it from scratch to find my mistake.

**Comment by vintz** [comment]
Just for information: i tried to send via smtp.gmail.com and I have the same error message.
I can't find anything wrong.

**Comment by cantino** [comment]
Oh weird.  Perhaps something odd with your system...?  But setting `openssl_verify_mode: none` in all sections of the yaml really should work.

**Comment by vintz** [comment]
Thank you for your help. I found a workaround (a php webservice to send email). I'll try to resolve the problem when I'll have more time for it. For now, the problem is "solved"
