### ISSUE TITLE
foreman quits without starting server

### ISSUE THREAD

**Issue by e-alfred** [cantino/huginn#824]
Hello,

if I follow the novice guide (installed ruby using rvm) an then try "foreman start", I get this:

```
21:06:52 web.1  | started with pid 17084
21:06:52 jobs.1 | started with pid 17085
21:06:59 web.1  | bin/rails:6: warning: already initialized constant APP_PATH
21:06:59 web.1  | /home/alfred/huginn/bin/rails:6: warning: previous definition of APP_PATH was here
21:06:59 web.1  | Usage: rails COMMAND [ARGS]
21:06:59 web.1  | 
21:06:59 web.1  | The most common rails commands are:
21:06:59 web.1  |  generate    Generate new code (short-cut alias: "g")
21:06:59 web.1  |  console     Start the Rails console (short-cut alias: "c")
21:06:59 web.1  |  server      Start the Rails server (short-cut alias: "s")
21:06:59 web.1  |  dbconsole   Start a console for the database specified in config/database.yml
21:06:59 web.1  |              (short-cut alias: "db")
21:06:59 web.1  |  new         Create a new Rails application. "rails new my_app" creates a
21:06:59 web.1  |              new application called MyApp in "./my_app"
21:06:59 web.1  | 
21:06:59 web.1  | In addition to those, there are:
21:06:59 web.1  |  destroy      Undo code generated with "generate" (short-cut alias: "d")
21:06:59 web.1  |  plugin new   Generates skeleton for developing a Rails plugin
21:06:59 web.1  |  runner       Run a piece of code in the application environment (short-cut alias: "r")
21:06:59 web.1  | 
21:06:59 web.1  | All commands can be run with -h (or --help) for more information.
21:06:59 web.1  | exited with code 0
21:06:59 system | sending SIGTERM to all processes
21:06:59 jobs.1 | terminated by SIGTERM
```

If I try to start ruby console in the huginn directory I get this:

```
rails console
/home/alfred/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- guard/guard (LoadError)
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/guard-livereload-1.4.0/lib/guard/livereload.rb:2:in `<top (required)>'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/runtime.rb:85:in `require'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/runtime.rb:85:in `rescue in block in require'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/runtime.rb:68:in `block in require'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `each'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `require'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler.rb:134:in `require'
	from /home/alfred/huginn/config/application.rb:5:in `<top (required)>'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:82:in `require'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:82:in `preload'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /home/alfred/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/alfred/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/alfred/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

My versions are:

```
$ gem -v
2.4.7
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
$ rails -v
Rails 4.2.1
```

I cloned Huginn today, if that matters.

**Comment by cantino** [comment]
Hey @e-alfred!  Could you try `bundle exec foreman start` and see if that works better than just `foreman start`?

**Comment by e-alfred** [comment]
Hello,

```bundle exec foreman start``` gives me that:

```
bundle exec foreman start
07:34:54 web.1  | started with pid 5587
07:34:54 jobs.1 | started with pid 5589
07:35:02 web.1  | bin/rails:6: warning: already initialized constant APP_PATH
07:35:02 web.1  | /home/alfred/huginn/bin/rails:6: warning: previous definition of APP_PATH was here
07:35:02 web.1  | Usage: rails COMMAND [ARGS]
07:35:02 web.1  | 
07:35:02 web.1  | The most common rails commands are:
07:35:02 web.1  |  generate    Generate new code (short-cut alias: "g")
07:35:02 web.1  |  console     Start the Rails console (short-cut alias: "c")
07:35:02 web.1  |  server      Start the Rails server (short-cut alias: "s")
07:35:02 web.1  |  dbconsole   Start a console for the database specified in config/database.yml
07:35:02 web.1  |              (short-cut alias: "db")
07:35:02 web.1  |  new         Create a new Rails application. "rails new my_app" creates a
07:35:02 web.1  |              new application called MyApp in "./my_app"
07:35:02 web.1  | 
07:35:02 web.1  | In addition to those, there are:
07:35:02 web.1  |  destroy      Undo code generated with "generate" (short-cut alias: "d")
07:35:02 web.1  |  plugin new   Generates skeleton for developing a Rails plugin
07:35:02 web.1  |  runner       Run a piece of code in the application environment (short-cut alias: "r")
07:35:02 web.1  | 
07:35:02 web.1  | All commands can be run with -h (or --help) for more information.
07:35:02 web.1  | exited with code 0
07:35:02 system | sending SIGTERM to all processes
07:35:02 jobs.1 | terminated by SIGTERM
```

**Comment by cantino** [comment]
What kind of computer / OS are you on?

**Comment by e-alfred** [comment]
It is Ubuntu 14.04.2 on a Virtualbox VM.

**Comment by cantino** [comment]
That's so strange.  You ran `bundle` before this?  You didn't restrict to only some bundler groups or something, I assume?

**Comment by virtadpt** [comment]
Are you running Rails from the APT repository, or are you using something like RVM to install an isolated copy of the Rails environment?

**Comment by e-alfred** [comment]
Hello,

i tried to run it first with the version from the local repositories (1.9.3), then using rvm and a newer version because it complained about the old version.

I resolved the problem by reinstalling the VM and using chef solo to deploy Huginn. It runs great so far.

Thank you

Alfred

**Comment by cantino** [comment]
Great!
