### ISSUE TITLE
ImapFolderAgent throws an "undefined method 'scrub' for nil:NilClass" exception.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#842]
From time to time the ImapFolderAgent throws an exception "undefined method 'scrub' for nil:NilClass" exception.  I'm not entirely certain what the criteria for this are - at first I thought it was due to the agent looking for a message in the IMAP queue and not finding it, but the other ImapFolderAgent instances don't do this when they don't find anything.  First comment will contain the Error Backtrace.

**Comment by virtadpt** [comment]
```
undefined method `scrub' for nil:NilClass
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:512:in `scrubbed'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:300:in `block in check'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:386:in `block (3 levels) in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:385:in `each'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:385:in `block (2 levels) in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:338:in `each'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:338:in `block in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:444:in `open'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:327:in `each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:234:in `check'
/home/drwho/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/execution.rb:32:in `block in perform_now'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/logging.rb:23:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/logging.rb:43:in `block in tag_logger'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/logging.rb:43:in `tag_logger'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `block in simple'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `block in around'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_perform_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/execution.rb:31:in `perform_now'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/execution.rb:21:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/activejob-4.2.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `call'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
bin/threaded.rb:49:in `block (2 levels) in <top (required)>'
bin/threaded.rb:19:in `safely'
bin/threaded.rb:46:in `block in <top (required)>'
```

**Comment by knu** [comment]
@virtadpt There probably was a mail without a Subject field, judging from the second line of the backtrace.  I've patched the scrubbed() method so it won't choke with such a mail.  Please try out the tip of the master branch.

**Comment by virtadpt** [comment]
I've updated to 1e57f3a4572f041be01e0a533d24c417235ab752.  I'll let you know what I see.

**Comment by virtadpt** [comment]
Nope.  I haven't seen this exception since.  I think that fixed it.

**Comment by cantino** [comment]
Great!
