### ISSUE TITLE
Agents won't run

### ISSUE THREAD

**Issue by Edu115** [cantino/huginn#864]
Hi,

For some reason, after following [this](https://gist.github.com/mjhea0/b6b58eefc38985380ff9#file-install_huginn_locally-md), whenever I try and run an agent, nothing happens.
There's also nothing in the logs about the agents, just the web.1 reporting.

Also, very weird is that the "Next run" is always in the past.

![image](https://cloud.githubusercontent.com/assets/665222/8209565/e3bbd590-150d-11e5-947d-b83a2f7f749b.png)

Any idea what the problem is?

**Comment by dsander** [comment]
Hi @Edu115, how does your [Procfile](https://github.com/cantino/huginn/blob/master/Procfile) look? When you are using the default file the output of `foreman start` should look something like this:

```
20:13:16 web.1  | started with pid 54307
20:13:16 jobs.1 | started with pid 54308
```

**Comment by Edu115** [comment]
Hi @dsander, it looks exactly like that. It is just like the default one.

However, I just uncommented the old version with separate processes, and it seems to fix it, the jobs ran successfully!
I would still prefer to use the threaded version, but I guess this is good enough.

**Comment by dsander** [comment]
That's odd. Have you tried starting the threaded worker without using foreman? 
You can just run `bundle exec rails runner bin/threaded.rb` in a console.

**Comment by Edu115** [comment]
Just tried, jobs just stay pending.

I've just noticed that the behaviour is similar to this: 
https://github.com/cantino/huginn/issues/795

In fact, running strace, I can see the same clock_gettime loop going on.
However, I'm not using a docker image or nothing like that.

**Comment by dsander** [comment]
#795 was caused by SCHEDULER_FREQUENCY being not set. If you are using the default .env and use a relatively recent version of Huginn that should not be an issue.

Do you mind sharing your (redacted) `.env`?

**Comment by t4meg** [comment]
Hi, 

I have a quite similar issue, agents stay in queue.
In the console, here is the output:

>bin/threaded.rb:49:in `block (2 levels) in <top (required)>'
bin/threaded.rb:19:in `safely'
bin/threaded.rb:46:in `block in <top (required)>'

**Comment by Edu115** [comment]
@dsander here's the env file

 ```
# ==== Required configuration settings for Huginn ====

# Replace the following with the output from "rake secret"
APP_SECRET_TOKEN=[REDACTED]

# This is the domain where your Huginn instance will be running. The default should work
# for development, but it needs to be changed to your Huginn domain when you deploy to a
# production environment (e.g., yourdomain.com, possibly including a port).
DOMAIN=[REDACTED]

# Optionally set an asset host
# ASSET_HOST=http://assets.example.com

############################
#      Database Setup      #
############################

DATABASE_ADAPTER=mysql2
#DATABASE_ENCODING=utf8
DATABASE_RECONNECT=true
DATABASE_NAME=huginn_development
DATABASE_POOL=10
DATABASE_USERNAME=root
DATABASE_PASSWORD=[REDACTED]
#DATABASE_HOST=your-domain-here.com
#DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock

# MySQL only: If you are running a MySQL server >=5.5.3, you should
# set DATABASE_ENCODING to utf8mb4 instead of utf8 so that the
# database can hold 4-byte UTF-8 characters like emoji.
DATABASE_ENCODING=utf8mb4

# ==== Additional required production settings ====

# Configure Rails environment.  This should only be needed in production and may cause errors in development.
# RAILS_ENV=production

# Should Rails force all requests to use SSL?
FORCE_SSL=false

############################
#     Allowing Signups     #
############################

# This invitation code will be required for users to signup with your Huginn installation.
# You can see its use in user.rb.  PLEASE CHANGE THIS!
INVITATION_CODE=[REDACTED]

#############################
#    Email Configuration    #
#############################

# Outgoing email settings.  To use Gmail or Google Apps, put your Google Apps domain or gmail.com
# as the SMTP_DOMAIN and your Gmail username and password as the SMTP_USER_NAME and SMTP_PASSWORD.
#
# PLEASE NOTE: In order to enable emails locally (e.g., when not in the production Rails environment),
# you must also set SEND_EMAIL_IN_DEVELOPMENT to true below.
#
# If you have trouble with port 587 on Gmail, you can also try setting
# SMTP_AUTHENTICATION to login and the SMTP_PORT to 465.

SMTP_DOMAIN=[REDACTED]
SMTP_USER_NAME=[REDACTED]
SMTP_PASSWORD=[REDACTED]
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# Send emails when running in the development Rails environment.
SEND_EMAIL_IN_DEVELOPMENT=true

# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=[REDACTED]

###########################
#      Agent Logging      #
###########################

# Number of lines of log messages to keep per Agent
AGENT_LOG_LENGTH=200

########################################################################################################
#    OAuth Configuration                                                                               #
#  More information at the wiki: https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications #
########################################################################################################

TWITTER_OAUTH_KEY=
TWITTER_OAUTH_SECRET=

THIRTY_SEVEN_SIGNALS_OAUTH_KEY=
THIRTY_SEVEN_SIGNALS_OAUTH_SECRET=

GITHUB_OAUTH_KEY=
GITHUB_OAUTH_SECRET=

TUMBLR_OAUTH_KEY=
TUMBLR_OAUTH_SECRET=

DROPBOX_OAUTH_KEY=
DROPBOX_OAUTH_SECRET=

WUNDERLIST_OAUTH_KEY=
WUNDERLIST_OAUTH_SECRET=

#############################
#  AWS and Mechanical Turk  #
#############################

# AWS Credentials for MTurk
AWS_ACCESS_KEY_ID="your aws access key id"
AWS_ACCESS_KEY="your aws access key"

# Set AWS_SANDBOX to true if you're developing Huginn code.
AWS_SANDBOX=false

########################
#   Various Settings   #
########################

# Specify the HTTP backend library for Faraday, commonly used by
# WebsiteAgent, RssAgent and PostAgent.  You can change this depending
# on the performance and stability you need for your service.  Any
# choice other than "typhoeus", "net_http", or "em_http" should
# require you to bundle a corresponding gem via Gemfile.
FARADAY_HTTP_BACKEND=typhoeus

# Specify the default User-Agent header value for HTTP requests made
# by Agents that allow overriding the User-Agent header value.
DEFAULT_HTTP_USER_AGENT="Huginn - https://github.com/cantino/huginn"

# Allow JSONPath eval expresions. i.e., $..price[?(@ < 20)]
# You should not allow this on a shared Huginn box because it is not secure.
ALLOW_JSONPATH_EVAL=false

# Enable this setting to allow insecure Agents like the ShellCommandAgent.  Only do this
# when you trust everyone using your Huginn installation.
ENABLE_INSECURE_AGENTS=false

# Enable this setting to allow second precision schedule in
# SchedulerAgent.  By default, the use of the "second" field is
# restricted so that any value other than a single zero (which means
# "on the minute") is disallowed to prevent abuse of service.
ENABLE_SECOND_PRECISION_SCHEDULE=false

# Specify the scheduler frequency in seconds (default: 0.3).
# Increasing this value will help reduce the use of system resources
# at the expense of time accuracy.
SCHEDULER_FREQUENCY=0.3

# Use Graphviz for generating diagrams instead of using Google Chart
# Tools.  Specify a dot(1) command path built with SVG support
# enabled.
#USE_GRAPHVIZ_DOT=dot

# Timezone. Use `rake time:zones:local` or `rake time:zones:all` to get your zone name
TIMEZONE="Amsterdam"

# Number of failed jobs to keep in the database
FAILED_JOBS_TO_KEEP=100

# Maximum runtime of background jobs in minutes
DELAYED_JOB_MAX_RUNTIME=20

# Amount of seconds for delayed_job to sleep before checking for new jobs
DELAYED_JOB_SLEEP_DELAY=10
```

Could it be the timezone?

**Comment by knu** [comment]
Hmm, seems this is occurring frequently on my instance also.  Even worse, jobs keep being queued while the worker does not dequeue at all.  So, I'm guessing something in the job queue may be getting DelayedJob to stall.  Once this occurs, restarting bin/threaded.rb never works until I manually clear out the job queue by executing DelayedJob.destroy_all.
I've switched to the non-threaded version and it seems to be working so far.

**Comment by dsander** [comment]
Hi @t4meg, your problem looks like a different one, do you mind creating a new issue including the full bac trace if you have one?

@Edu115 Your `.env` looks ok to me. Does the `strace` show anything else abnormal? I think three `clock_gettime` calls per second (due to `SCHEDULER_FREQUENCY` beeing set to 0.3) would be fine.

@knu  That sounds odd, I think we did not change anything in the threaded worker for some time. Since a few weeks am running my `agent-runner` branch and never had any problems with the threaded worker before that.

**Comment by virtadpt** [comment]
I just ran into it - woke up this morning to over 4,300 stuck processes.  I eventually figured out which three agents were hanging up the job queue and disabled them, but I still have over 3,000 to go until it's completely clear.  I'm running the latest checkout from this morning and the threaded agent runner in development mode.

**Comment by cantino** [comment]
This doesn't seem to have happened in a while.  Okay to close?
