### ISSUE TITLE
WebsiteAgent: regex problem

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#897]
Im trying to parse a website with regex, unfortunately it errors out after matching the first extract/index.

log:
[0]
```
Fetching http://mattmahoney.net/dc/zpaq.html
```
[1]
```
Extracting text at (?mi-x:^<a href=(?<file>[a-z0-9\.]+)>zpaq [v]?(?<version>[0-9\.]+)<\/a>, (?<date>[a-z]{3,4}[\.|\,]?[ ]?[0-9]{1,2}[\.|\,]?[ ]?[0-9]{4})\. (?<changelog>.*?)(?=<br>)): ["zpaq.205.zip", "zpaq300.zip", "zpaq301.zip", "zpaq400.zip", "zpaq401.zip", "zpaq402.zip", "zpaq403.zip", "zpaq404.zip", "zpaq500.zip", "zpaq600.zip", "zpaq601.zip", "zpaq602.zip", "zpaq603.zip", "zpaq604.zip", "zpaq605.zip", "zpaq606.zip", "zpaq607.zip", "zpaq616.zip", "zpaq617.zip", "zpaq618.zip", "zpaq619.zip", "zpaq620.zip", "zpaq621.zip", "zpaq622.zip", "zpaq623.zip", "zpaq624.zip", "zpaq626.zip", "zpaq627.zip", "zpaq629.zip", "zpaq630.zip", "zpaq631.zip", "zpaq633.zip", "zpaq634.zip", "zpaq635.zip", "zpaq636.zip", "zpaq637.zip", "zpaq638.zip", "zpaq639.zip", "zpaq640.zip", "zpaq641.zip", "zpaq642.zip", "zpaq643.zip", "zpaq644.zip", "zpaq645.zip", "zpaq646.zip", "zpaq647.zip", "zpaq648.zip", "zpaq649.zip", "zpaq650.zip", "zpaq651.zip", "zpaq652.zip", "zpaq653.zip", "zpaq654.zip", "zpaq655.zip", "zpaq656.zip", "zpaq657.zip", "zpaq658.zip", "zpaq659.zip", "zpaq660.zip", "zpaq700.zip", "zpaq701.zip", "zpaq702.zip", "zpaq703.zip", "zpaq704.zip", "zpaq705.zip"]
```
[2]
```
Error when fetching url: can't convert nil into String
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:304:in `initialize'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:304:in `new'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:304:in `block in extract_text'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:290:in `call'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:290:in `block in extract_each'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:289:in `each'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:289:in `each_with_object'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:289:in `extract_each'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:303:in `extract_text'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:190:in `block in check_url'
/var/lib/gems/1.9.1/gems/liquid-2.6.1/lib/liquid/context.rb:112:in `stack'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:169:in `check_url'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:160:in `block in check_urls'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:159:in `each'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:159:in `check_urls'
/home/k1773r/git/huginn/app/models/agents/website_agent.rb:153:in `check'
/home/k1773r/git/huginn/app/models/agent.rb:424:in `async_check'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:150:in `start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

agent config:
```
{
  "expected_update_period_in_days": "31",
  "url": "http://mattmahoney.net/dc/zpaq.html",
  "type": "text",
  "mode": "on_change",
  "extract": {
    "file": {
      "regexp": "(?mi:^<a href=(?<file>[a-z0-9\\.]+)>zpaq [v]?(?<version>[0-9\\.]+)<\\/a>, (?<date>[a-z]{3,4}[\\.|\\,]?[ ]?[0-9]{1,2}[\\.|\\,]?[ ]?[0-9]{4})\\. (?<changelog>.*?)(?=<br>))",
      "index": "file"
    },
    "version": {
      "regex": "(?mi:^<a href=(?<file>[a-z0-9\\.]+)>zpaq [v]?(?<version>[0-9\\.]+)<\\/a>, (?<date>[a-z]{3,4}[\\.|\\,]?[ ]?[0-9]{1,2}[\\.|\\,]?[ ]?[0-9]{4})\\. (?<changelog>.*?)(?=<br>))",
      "index": "version"
    },
    "date": {
      "regex": "(?mi:^<a href=(?<file>[a-z0-9\\.]+)>zpaq [v]?(?<version>[0-9\\.]+)<\\/a>, (?<date>[a-z]{3,4}[\\.|\\,]?[ ]?[0-9]{1,2}[\\.|\\,]?[ ]?[0-9]{4})\\. (?<changelog>.*?)(?=<br>))",
      "index": "date"
    },
    "changelog": {
      "regex": "(?mi:^<a href=(?<file>[a-z0-9\\.]+)>zpaq [v]?(?<version>[0-9\\.]+)<\\/a>, (?<date>[a-z]{3,4}[\\.|\\,]?[ ]?[0-9]{1,2}[\\.|\\,]?[ ]?[0-9]{4})\\. (?<changelog>.*?)(?=<br>))",
      "index": "changelog"
    }
  }
}
```

**Comment by knu** [comment]
Try replacing "regex" in the "version", "date" and "changelog" subhashes with "regexp".

The latest master has a new validation function that would detect this kind of typo.

**Comment by K1773R** [comment]
oh my... thanks. what a silly mistake.
