### ISSUE TITLE
TumblrPublishAgent error

### ISSUE THREAD

**Issue by mikalauskas** [cantino/huginn#942]
some people just set app to use simple_oauth-0.2.0
http://stackoverflow.com/questions/26295611/ruby-simpleoauth-error

ps: deployed in heroku
```
                       SimpleOAuth: Found extra option keys not matching ATTRIBUTE_KEYS:
  [:api_host]
/app/vendor/bundle/ruby/2.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:92:in `attributes'
/app/vendor/bundle/ruby/2.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:77:in `signed_attributes'
/app/vendor/bundle/ruby/2.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:83:in `normalized_attributes'
/app/vendor/bundle/ruby/2.0.0/gems/simple_oauth-0.3.1/lib/simple_oauth/header.rb:65:in `to_s'
/app/vendor/bundle/ruby/2.0.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/oauth.rb:41:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
/app/vendor/bundle/ruby/2.0.0/gems/tumblr_client-0.8.4/lib/tumblr/request.rb:34:in `post'
/app/vendor/bundle/ruby/2.0.0/gems/tumblr_client-0.8.4/lib/tumblr/post.rb:85:in `video'
/app/app/models/agents/tumblr_publish_agent.rb:159:in `publish_post'
/app/app/models/agents/tumblr_publish_agent.rb:107:in `block in receive'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation/delegation.rb:46:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.2/lib/active_record/relation/delegation.rb:46:in `each'
/app/app/models/agents/tumblr_publish_agent.rb:102:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/execution.rb:32:in `block in perform_now'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:343:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/logging.rb:23:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/logging.rb:43:in `block in tag_logger'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/logging.rb:43:in `tag_logger'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:342:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:342:in `block in simple'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:497:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:497:in `block in around'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:776:in `_run_perform_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/execution.rb:31:in `perform_now'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/execution.rb:21:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/activejob-4.2.2/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
bin/threaded.rb:49:in `block (2 levels) in <top (required)>'
bin/threaded.rb:19:in `safely'
bin/threaded.rb:46:in `block in <top (required)>'
                     
```

**Comment by cantino** [comment]
Sorry, what does this have to do with Huginn?  I don't see a mention there, but I might be missing it.
