### ISSUE TITLE
bundle exec error

### ISSUE THREAD

**Issue by kingqiu** [cantino/huginn#948]
Hi guys, I've tried to install the latest version of huginn in CentOS 7 by following the Novice setup guide and the Quick start. I've successfully accomplished the steps mentioned in Novice setup guide. Then I've got the following error during running "bundle exec rake db:create":

rake aborted!
LoadError: cannot load such file -- nokogiri/nokogiri
/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:29:in `require'
/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:29:in `rescue in <top (required)>'
/usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:25:in `<top (required)>'
/usr/local/share/gems/gems/rturk-2.12.1/lib/rturk/parsers/response.rb:1:in `require'
/usr/local/share/gems/gems/rturk-2.12.1/lib/rturk/parsers/response.rb:1:in `<top (required)>'
/usr/local/share/gems/gems/rturk-2.12.1/lib/rturk.rb:36:in `require'
/usr/local/share/gems/gems/rturk-2.12.1/lib/rturk.rb:36:in `block in <top (required)>'
/usr/local/share/gems/gems/rturk-2.12.1/lib/rturk.rb:36:in `each'
/usr/local/share/gems/gems/rturk-2.12.1/lib/rturk.rb:36:in `<top (required)>'
/usr/local/share/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
/usr/local/share/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/share/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
/usr/local/share/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/share/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
/usr/local/share/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
/usr/local/share/gems/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
/huginn/huginn/config/application.rb:5:in `<top (required)>'
/huginn/huginn/Rakefile:5:in `require'
/huginn/huginn/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

The nokogiri version is gems as 1.6.6.2 when I run "bundle" in previous step. And the ruby version in this environment is 'ruby 2.0.0p598 (2014-11-13) [x86_64-linux]'. Any thoughts of how to resolve the issue?
Thanks!

**Comment by kingqiu** [comment]
Hi, the issue was resolved by following the the post of https://github.com/cantino/huginn/issues/126 

It complained about "nokogiri/nokogiri" not being found, I did "cp /usr/local/share/gems1.9/gems/nokogiri-1.6.0/ext/nokogiri/nokogiri.so /usr/local/share/gems1.9/gems/nokogiri-1.6.0/lib/nokogiri/“
