### ISSUE TITLE
exception in weather agent

### ISSUE THREAD

**Issue by kingqiu** [cantino/huginn#953]
Hi, I've got the following error message after setting a weather agent:

undefined method `[]' for nil:NilClass
/home/huginn/huginn/app/models/agents/weather_agent.rb:95:in `wunderground'
/home/huginn/huginn/app/models/agents/weather_agent.rb:108:in `model'
/home/huginn/huginn/app/models/agents/weather_agent.rb:179:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.2/lib/active_job/execution.rb:32:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'

My configurations are listed here:
{
  "service": "wunderground",
  "which_day": 1,
  "location": "Australia/New_South_Wales/Sydney",
  "api_key": "exxxxxxxxxxxxxxx"
}

I'm sure the api key is correct. Do I miss anything? Thanks.

**Comment by kingqiu** [comment]
Seems like the issue is the location string. While I use the SF code of "94103", it's fine.
