### ISSUE TITLE
Twitter Stream invalid status code: 401

### ISSUE THREAD

**Issue by nxfifteen** [cantino/huginn#961]
I'm trying to setup a Twitter stream agent but having some problems.

I've created by app in apps.twitter.com [as per](https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications) and copied the Consumer Key to TWITTER_OAUTH_KEY and Consumer Secret to TWITTER_OAUTH_SECRET in my _.env_ file but I cant use any of the Twitter agents.

If I try the Twitter Publish Agent comes back with error "Could not authenticate you." and if I enable the Twitter Stream Agent I get a 401 error when restarting foreman:

```sh
$ bundle exec foreman start
12:43:05 web.1  | started with pid 6648
12:43:05 jobs.1 | started with pid 6650
12:43:07 web.1  | Warning: You're using Rubygems 2.0.14 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
12:43:07 jobs.1 | Warning: You're using Rubygems 2.0.14 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
12:43:11 jobs.1 | Found 1 agent(s).  Loading them now...
12:43:12 jobs.1 |  --> Twitter error: invalid status code: 401. <--
```
What's confusing is I can go into the Your Services tab and authenticate my Twitter account without getting any error messages.

Can anyone point me in the right direction for what I'm doing wrong

**Comment by cantino** [comment]
Welcome @nxfifteen!  After setting up the OAuth application, did you authenticate with Twitter via the Services page in your Huginn instance?

**Comment by nxfifteen** [comment]
yeah without any errors, that's the bit I cant understand

**Comment by cantino** [comment]
So you have an authenticated Twitter service at /services, it's selected in your Twitter Agent, but you get 401 errors in the console.  That's very surprising.

**Comment by nxfifteen** [comment]
I went back and deleted the account from the services pane and added it again, this time I took a copy of what appears in the command line

I've taken out some of sanitised the output, I can't see anything obviously standing out except the token and secret values stored are different from those twitter returned - but I assume that's normal behavour?

Is there a way to get more detailed debug logs? 

```sh
08:04:54 web.1  | Started GET "/auth/twitter" for 82.0.0.0 at 2015-08-09 08:04:54 +0100
08:04:54 web.1  | I, [2015-08-09T08:04:54.758424 #24089]  INFO -- omniauth: (twitter) Request phase initiated.
08:05:24 web.1  | 
08:05:24 web.1  | 
08:05:24 web.1  | Started GET "/auth/twitter/callback?oauth_token=8SKjowAAAAAA[REDACTED]&oauth_verifier=3DfCEqvCn[REDACTED]" for 82.0.0.0 at 2015-08-09 08:05:24 +0100
08:05:24 web.1  | I, [2015-08-09T08:05:24.769669 #24089]  INFO -- omniauth: (twitter) Callback phase initiated.
08:05:26 web.1  | Processing by OmniauthCallbacksController#twitter as HTML
08:05:26 web.1  |   Parameters: {"oauth_token"=>"8SKjowAAAAAA[REDACTED]", "oauth_verifier"=>"3DfCEqvCn[REDACTED]"}
08:05:26 web.1  | Geokit is using the domain: me.uk
08:05:26 web.1  |   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
08:05:26 web.1  |   Service Load (0.7ms)  SELECT  `services`.* FROM `services` WHERE `services`.`user_id` = 1 AND `services`.`provider` = 'twitter' AND `services`.`uid` = '225113688'  ORDER BY services.name asc LIMIT 1
08:05:26 web.1  |    (0.1ms)  BEGIN
08:05:26 web.1  |   SQL (0.2ms)  INSERT INTO `services` (`user_id`, `provider`, `uid`, `token`, `secret`, `name`, `options`, `created_at`, `updated_at`) VALUES (1, 'twitter', '225113688', '225113688-UMr7Lyso[REDACTED]', '6XyFFXacw[REDACTED]', 'nxfifteen', '---\n:name: nxfifteen\n', '2015-08-09 07:05:26', '2015-08-09 07:05:26')
08:05:26 web.1  |    (13.5ms)  COMMIT
08:05:26 web.1  | Redirected to http://127.0.0.1/services
08:05:26 web.1  | Completed 302 Found in 26ms (ActiveRecord: 15.0ms)
```

**Comment by nxfifteen** [comment]
I don't know if this is related but, I also can't get email to send while in development mode

I have SEND_EMAIL_IN_DEVELOPMENT set to true but huginn never attempts to send emails

**Comment by cantino** [comment]
It does look like the call succeeded.

The only idea that I have is that mention of `spring` in your first post.  Maybe you should try quitting it.  See if running `spring stop` helps.

**Comment by nxfifteen** [comment]
I've disabled `spring` but with no success. I've also completely deleted my twitter app and started again from the beginning

I can now no longer sign in to Twitter from the services page, I'm getting the error bellow.

Can I just check my `.env` setup:
TWITTER_OAUTH_KEY should be the same as __Consumer Key (API Key)__
TWITTER_OAUTH_SECRET should be __Consumer Secret (API Secret)__
TWITTER_CONSUMER_KEY and TWITTER_CONSUMER_SECRET should both be left blank?

Is the right or should I be setting TWITTER_CONSUMER_KEY and TWITTER_CONSUMER_SECRET to something from the apps.twitter.com page?

```sh
21:43:35 web.1  | I, [2015-08-11T21:43:35.715223 #6168]  INFO -- omniauth: (twitter) Request phase initiated.
21:43:35 web.1  | 
21:43:35 web.1  | OAuth::Unauthorized - 401 Authorization Required:
21:43:35 web.1  |   oauth (0.4.7) lib/oauth/consumer.rb:216:in `token_request'
21:43:35 web.1  |   oauth (0.4.7) lib/oauth/consumer.rb:136:in `get_request_token'
21:43:35 web.1  |   omniauth-oauth (1.0.1) lib/omniauth/strategies/oauth.rb:29:in `request_phase'
21:43:35 web.1  |   omniauth-twitter (1.0.1) lib/omniauth/strategies/twitter.rb:60:in `request_phase'
21:43:35 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:215:in `request_call'
21:43:35 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:183:in `call!'
21:43:35 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
21:43:35 web.1  |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
21:43:35 web.1  |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/etag.rb:24:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/head.rb:13:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
21:43:35 web.1  |   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
21:43:35 web.1  |   activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
21:43:35 web.1  |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
21:43:35 web.1  |   activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
21:43:35 web.1  |   activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
21:43:35 web.1  |   activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
21:43:35 web.1  |   activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
21:43:35 web.1  |   better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
21:43:35 web.1  |   better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
21:43:35 web.1  |   better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
21:43:35 web.1  |   railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
21:43:35 web.1  |   railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
21:43:35 web.1  |   activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
21:43:35 web.1  |   activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
21:43:35 web.1  |   activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
21:43:35 web.1  |   railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
21:43:35 web.1  |   config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'
21:43:35 web.1  |   quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
21:43:35 web.1  |   activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
21:43:35 web.1  |   actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
21:43:35 web.1  |   railties (4.2.2) lib/rails/engine.rb:518:in `call'
21:43:35 web.1  |   railties (4.2.2) lib/rails/application.rb:164:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
21:43:35 web.1  |   rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
21:43:35 web.1  |   /usr/local/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
21:43:35 web.1  |   /usr/local/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
21:43:35 web.1  |   /usr/local/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
21:43:35 web.1  | 
21:43:36 web.1  | 
21:43:36 web.1  | 
21:43:36 web.1  | Started POST "/__better_errors/69956543205240/variables" for [MYIPADDRESS] at 2015-08-11 21:43:36 +0100
```

**Comment by virtadpt** [comment]
This jumped out at me:
```12:43:07 web.1  | Warning: You're using Rubygems 2.0.14 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.```
Try upgrading?

**Comment by nxfifteen** [comment]
Yeah I'm now running `ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]` with Spring disabled.

I'm working on the idea it might be something wrong with the OS setup it's self. So I'm installing huginn on a clean virtual machine to see if I can get it to work there. If it works on the virtual machine then at lest I know its something to do with my server configuration rather than my huginn setup or .env file

**Comment by cantino** [comment]
Sorry this hasn't been working well!

You should only be setting `TWITTER_OAUTH_KEY` and `TWITTER_OAUTH_SECRET` in your `.env` file.  Mine looks like:

```
TWITTER_OAUTH_KEY=thM5C...
TWITTER_OAUTH_SECRET=BtkxxW...
```

**Comment by cantino** [comment]
You're not putting quotes in there, right?

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
